In [ ]:
!git clone -b phase25b-maira2-feasibility \
    https://github.com/gvasu-2023/Evidence-State-Radiology.git \
    /content/Evidence-State-Radiology

Cloning into '/content/Evidence-State-Radiology'...
remote: Enumerating objects: 394, done.
remote: Counting objects: 100% (394/394), done.
remote: Compressing objects: 100% (270/270), done.
remote: Total 394 (delta 142), reused 348 (delta 96), pack-reused 0 (from 0)
Receiving objects: 100% (394/394), 1.25 MiB | 11.29 MiB/s, done.
Resolving deltas: 100% (142/142), done.

In [ ]:
%cd /content/Evidence-State-Radiology

!git log --oneline -5

/content/Evidence-State-Radiology
5907f33 (HEAD -> phase25b-maira2-feasibility, origin/phase25b-maira2-feasibility) feat: add phases 17-25 reliability evaluation and MAIRA-2 feasibility
c4552c2 (origin/main, origin/HEAD) feat: freeze validated six-state benchmark
c094e8e feat: generate phase16c evidence-state benchmark
1f9c55a feat: select phase16b IU-Xray benchmark
fd65a6d feat: audit expanded IU-Xray benchmark

In [ ]:
from pathlib import Path

ROOT = Path("/content/Evidence-State-Radiology")

print("Repository:", ROOT.exists())

for directory in [
    "src/generation",
    "src/evaluation",
    "results/tables",
    "tests",
]:
    p = ROOT / directory
    print(f"{directory}: {p.exists()}")

Repository: True
src/generation: True
src/evaluation: True
results/tables: True
tests: True

In [ ]:
print("\nGeneration source files:")
for p in sorted((ROOT / "src" / "generation").glob("*.py")):
    print(" ", p.name)

print("\nEvaluation source files:")
for p in sorted((ROOT / "src" / "evaluation").glob("*.py")):
    print(" ", p.name)

Generation source files:
  __init__.py
  baseline.py
  run_baseline.py
  run_baseline_experiment.py
  run_iu_baseline.py
  test_context_conditioning.py

Evaluation source files:
  __init__.py
  analyze_conditions.py
  analyze_evidence_states.py
  audit_baseline.py
  audit_context_completeness.py
  audit_phase11_dataset.py
  build_reference_candidates.py
  claim_evaluator.py
  claim_extractor.py
  claim_patterns.py
  evaluate_abstention_metrics.py
  evaluate_analyzer.py
  evaluate_analyzer_phase12b.py
  evaluate_analyzer_phase12c.py
  evaluate_chexpert_f1.py
  evaluate_gated_generation.py
  evaluate_phase11_paired.py
  evaluate_phase13a_gate.py
  evaluate_phase13b_gated_reports.py
  evaluate_radgraph_f1.py
  evaluate_reference_factuality.py
  evaluate_reliability_gate.py
  evaluate_risk_coverage.py
  evaluate_unsupported_claims.py
  metrics.py
  run_phase15_evaluation.py
  run_phase19_claim_evaluation.py
  run_phase20_metrics.py
  run_phase21_risk_coverage.py
  run_phase22_statistics.py
  run_phase23_qualitative_analysis.py
  run_phase24_consolidation.py
  run_phase24_figures.py

In [ ]:
from pathlib import Path
import pandas as pd
import hashlib

ROOT = Path("/content/Evidence-State-Radiology")

# Check the frozen Phase 16 benchmark
BENCHMARK = ROOT / "results" / "tables" / "phase16_perturbations.csv"

print("Benchmark:", BENCHMARK)
print("Exists:", BENCHMARK.exists())

if BENCHMARK.exists():
    df = pd.read_csv(BENCHMARK)

    print("\nShape:", df.shape)
    print("Columns:")
    print(df.columns.tolist())

    print("\nConditions:")
    print(df["condition"].value_counts().sort_index())

    print("\nUnique studies:", df["uid"].nunique())

    print("\nFrontal images:", df["frontal_image"].nunique())

    print("\nBenchmark SHA-256:")

    h = hashlib.sha256()
    with open(BENCHMARK, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)

    print(h.hexdigest())

Benchmark: /content/Evidence-State-Radiology/results/tables/phase16_perturbations.csv
Exists: True

Shape: (600, 20)
Columns:
['sample_id', 'uid', 'condition', 'evidence_state', 'original_context', 'perturbed_context', 'frontal_image', 'lateral_image', 'findings', 'impression', 'comparison', 'source_context_uid', 'source_context_sample_id', 'removed_evidence_text', 'evidentiary_incomplete_method', 'conflict_target', 'conflict_method', 'conflict_source_text', 'generation_status', 'generation_failure_reason']

Conditions:
condition
conflicting               100
evidentiary_incomplete    100
insufficient              100
irrelevant                100
sufficient                100
syntactic_incomplete      100
Name: count, dtype: int64

Unique studies: 100

Frontal images: 96

Benchmark SHA-256:
2f73429a2620296d0a7a83454f9ca071ac9a38e829f28907ce27af101bc31488

In [ ]:
EXCLUDED_NO_FRONTAL = {74, 597, 803, 885}

eligible = df[~df["uid"].isin(EXCLUDED_NO_FRONTAL)].copy()

print("Eligible records:", len(eligible))
print("Eligible studies:", eligible["uid"].nunique())

print("\nRecords per condition:")
print(eligible["condition"].value_counts().sort_index())

print("\nExcluded records:")
print(df[df["uid"].isin(EXCLUDED_NO_FRONTAL)][
    ["uid", "condition", "frontal_image"]
].to_string(index=False))

Eligible records: 576
Eligible studies: 96

Records per condition:
condition
conflicting               96
evidentiary_incomplete    96
insufficient              96
irrelevant                96
sufficient                96
syntactic_incomplete      96
Name: count, dtype: int64

Excluded records:
 uid              condition frontal_image
  74             sufficient           NaN
  74   syntactic_incomplete           NaN
  74 evidentiary_incomplete           NaN
  74             irrelevant           NaN
  74            conflicting           NaN
  74           insufficient           NaN
 597             sufficient           NaN
 597   syntactic_incomplete           NaN
 597 evidentiary_incomplete           NaN
 597             irrelevant           NaN
 597            conflicting           NaN
 597           insufficient           NaN
 803             sufficient           NaN
 803   syntactic_incomplete           NaN
 803 evidentiary_incomplete           NaN
 803             irrelevant           NaN
 803            conflicting           NaN
 803           insufficient           NaN
 885             sufficient           NaN
 885   syntactic_incomplete           NaN
 885 evidentiary_incomplete           NaN
 885             irrelevant           NaN
 885            conflicting           NaN
 885           insufficient           NaN

In [ ]:
DEV_STUDIES = [
    195, 227, 253, 282,
    290, 317, 458, 494,
    577, 783, 793, 936,
    960, 965, 1025, 1165
]

dev = eligible[eligible["uid"].isin(DEV_STUDIES)].copy()
evaluation = eligible[~eligible["uid"].isin(DEV_STUDIES)].copy()

print("Development:")
print("  records:", len(dev))
print("  studies:", dev["uid"].nunique())

print("\nDevelopment condition counts:")
print(dev["condition"].value_counts().sort_index())

print("\nEvaluation:")
print("  records:", len(evaluation))
print("  studies:", evaluation["uid"].nunique())

print("\nEvaluation condition counts:")
print(evaluation["condition"].value_counts().sort_index())

print("\nStudy overlap:")
print(set(dev["uid"]) & set(evaluation["uid"]))

Development:
  records: 96
  studies: 16

Development condition counts:
condition
conflicting               16
evidentiary_incomplete    16
insufficient              16
irrelevant                16
sufficient                16
syntactic_incomplete      16
Name: count, dtype: int64

Evaluation:
  records: 480
  studies: 80

Evaluation condition counts:
condition
conflicting               80
evidentiary_incomplete    80
insufficient              80
irrelevant                80
sufficient                80
syntactic_incomplete      80
Name: count, dtype: int64

Study overlap:
set()

In [ ]:
SPLIT_DIR = ROOT / "results" / "tables" / "phase26d"
SPLIT_DIR.mkdir(parents=True, exist_ok=True)

split_rows = []

for uid in sorted(eligible["uid"].unique()):
    split_rows.append({
        "study_id": int(uid),
        "split": "development" if uid in DEV_STUDIES else "evaluation"
    })

split_df = pd.DataFrame(split_rows)

SPLIT_PATH = SPLIT_DIR / "phase26d_maira2_split.csv"
split_df.to_csv(SPLIT_PATH, index=False)

print("Saved:")
print(SPLIT_PATH)
print("\nShape:", split_df.shape)
print(split_df["split"].value_counts())

Saved:
/content/Evidence-State-Radiology/results/tables/phase26d/phase26d_maira2_split.csv

Shape: (96, 2)
split
evaluation     80
development    16
Name: count, dtype: int64

In [ ]:
from pathlib import Path
import pandas as pd

SPLIT_PATH = Path(
    "/content/Evidence-State-Radiology/"
    "results/tables/phase26d/phase26d_maira2_split.csv"
)

split = pd.read_csv(SPLIT_PATH)

print(split)
print("\nSHA-256:")
import hashlib

h = hashlib.sha256()
with open(SPLIT_PATH, "rb") as f:
    for chunk in iter(lambda: f.read(1024 * 1024), b""):
        h.update(chunk)

print(h.hexdigest())

    study_id        split
0         32   evaluation
1         36   evaluation
2         44   evaluation
3         49   evaluation
4         53   evaluation
..       ...          ...
91      1114   evaluation
92      1165  development
93      1172   evaluation
94      1173   evaluation
95      1205   evaluation

[96 rows x 2 columns]

SHA-256:
b7e37147cc59e6477f5d93ab9c826a967ac75c0883b014693197cf7a1d07a8aa

In [ ]:
!pip install -q \
    "transformers==4.51.3" \
    "accelerate>=1.2,<2" \
    "pillow" \
    "protobuf" \
    "sentencepiece" \
    "bitsandbytes"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 75.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 16.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 40.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 105.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.29.0 requires huggingface-hub<3.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
diffusers 0.40.0 requires huggingface-hub<2.0,>=1.23.0, but you have huggingface-hub 0.36.2 which is incompatible.

In [ ]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "VRAM:",
        round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
        "GB"
    )

PyTorch: 2.11.0+cu130
CUDA available: True
GPU: Tesla T4
VRAM: 14.56 GB

In [ ]:
import transformers

print("Transformers:", transformers.__version__)

Transformers: 4.51.3

In [ ]:
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

print("HF token available:", HF_TOKEN is not None)

HF token available: True

In [ ]:
from transformers import AutoProcessor

MODEL_ID = "microsoft/maira-2"

processor = AutoProcessor.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    token=HF_TOKEN,
)

print("Processor loaded:", type(processor).__name__)

processor_config.json:   0%|          | 0.00/405 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/611 [00:00<?, ?B/s]

processing_maira2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/maira-2:
- processing_maira2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

preprocessor_config.json:   0%|          | 0.00/560 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/552 [00:00<?, ?B/s]

Processor loaded: Maira2Processor

In [ ]:
import torch

from transformers import (
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    device_map={"": 0},
    quantization_config=quantization_config,
    token=HF_TOKEN,
)

model.eval()

print("Model class:", type(model).__name__)
print("Model loaded successfully.")

config.json: 0.00B [00:00, ?B/s]

configuration_maira2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/maira-2:
- configuration_maira2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_maira2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/maira-2:
- modeling_maira2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]

model-00006-of-00006.safetensors:   0%|          | 0.00/3.14G [00:00<?, ?B/s]

model-00003-of-00006.safetensors:   0%|          | 0.00/4.86G [00:00<?, ?B/s]

model-00005-of-00006.safetensors:   0%|          | 0.00/4.86G [00:00<?, ?B/s]

model-00002-of-00006.safetensors:   0%|          | 0.00/4.86G [00:00<?, ?B/s]

model-00001-of-00006.safetensors:   0%|          | 0.00/4.96G [00:00<?, ?B/s]

model-00004-of-00006.safetensors:   0%|          | 0.00/4.86G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/6 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/179 [00:00<?, ?B/s]

Model class: Maira2ForConditionalGeneration
Model loaded successfully.

In [ ]:
from pathlib import Path
import pandas as pd

ROOT = Path("/content/Evidence-State-Radiology")

BENCHMARK = ROOT / "results" / "tables" / "phase16_perturbations.csv"

benchmark = pd.read_csv(BENCHMARK)

uid = 195

rows = benchmark[benchmark["uid"] == uid].copy()

print(rows[
    [
        "sample_id",
        "uid",
        "condition",
        "perturbed_context",
        "frontal_image",
        "findings",
        "impression",
    ]
].to_string(index=False))

sample_id  uid              condition                                perturbed_context                                   frontal_image                                                                              findings                                impression
   IU_195  195             sufficient XXXX-year-old female with coughing and wheezing. external_data/IU-Xray/images/IU_195_frontal.jpg Clear lungs bilaterally. No pneumothorax or pleural effusion. Normal cardiac contours 1. No acute cardiopulmonary abnormalities
   IU_195  195   syntactic_incomplete                        XXXX-year-old female with external_data/IU-Xray/images/IU_195_frontal.jpg Clear lungs bilaterally. No pneumothorax or pleural effusion. Normal cardiac contours 1. No acute cardiopulmonary abnormalities
   IU_195  195 evidentiary_incomplete                  XXXX-year-old female, wheezing. external_data/IU-Xray/images/IU_195_frontal.jpg Clear lungs bilaterally. No pneumothorax or pleural effusion. Normal cardiac contours 1. No acute cardiopulmonary abnormalities
   IU_195  195             irrelevant                              Chest pain, dyspnea external_data/IU-Xray/images/IU_195_frontal.jpg Clear lungs bilaterally. No pneumothorax or pleural effusion. Normal cardiac contours 1. No acute cardiopulmonary abnormalities
   IU_195  195            conflicting                  The patient has a pneumothorax. external_data/IU-Xray/images/IU_195_frontal.jpg Clear lungs bilaterally. No pneumothorax or pleural effusion. Normal cardiac contours 1. No acute cardiopulmonary abnormalities
   IU_195  195           insufficient                                              NaN external_data/IU-Xray/images/IU_195_frontal.jpg Clear lungs bilaterally. No pneumothorax or pleural effusion. Normal cardiac contours 1. No acute cardiopulmonary abnormalities

In [ ]:
uid195 = benchmark[benchmark["uid"] == 195].iloc[0]

print("Frontal image reference:")
print(uid195["frontal_image"])

print("\nImage exists locally:")

image_ref = str(uid195["frontal_image"])

candidates = [
    ROOT / image_ref,
    ROOT / "external_data" / "IU-Xray" / image_ref,
    Path("/content") / image_ref,
]

for p in candidates:
    print(p, "->", p.exists())

Frontal image reference:
external_data/IU-Xray/images/IU_195_frontal.jpg

Image exists locally:
/content/Evidence-State-Radiology/external_data/IU-Xray/images/IU_195_frontal.jpg -> False
/content/Evidence-State-Radiology/external_data/IU-Xray/external_data/IU-Xray/images/IU_195_frontal.jpg -> False
/content/external_data/IU-Xray/images/IU_195_frontal.jpg -> False

In [ ]:
from pathlib import Path

for p in [
    Path("/content/IU-Xray-source"),
    Path("/content/IU-Xray"),
    Path("/content"),
]:
    print("\n", p)
    if p.exists():
        matches = list(p.rglob("*.parquet"))
        print("Parquet files:", len(matches))
        for x in matches[:10]:
            print(" ", x)

 /content/IU-Xray-source

 /content/IU-Xray

 /content
Parquet files: 0

In [ ]:
from pathlib import Path

SOURCE_ROOT = Path("/content/IU-Xray-source")
DATA_DIR = SOURCE_ROOT / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

print(DATA_DIR)

/content/IU-Xray-source/data

In [ ]:
!wget -q --show-progress \
"https://huggingface.co/datasets/ykumards/open-i/resolve/main/data/train-00000-of-00005-c80629f6027d8eb1.parquet" \
-O /content/IU-Xray-source/data/train-00000-of-00005-c80629f6027d8eb1.parquet

!wget -q --show-progress \
"https://huggingface.co/datasets/ykumards/open-i/resolve/main/data/train-00001-of-00005-07e6c158a3f56170.parquet" \
-O /content/IU-Xray-source/data/train-00001-of-00005-07e6c158a3f56170.parquet

!wget -q --show-progress \
"https://huggingface.co/datasets/ykumards/open-i/resolve/main/data/train-00002-of-00005-653f05c8b15c22c6.parquet" \
-O /content/IU-Xray-source/data/train-00002-of-00005-653f05c8b15c22c6.parquet

!wget -q --show-progress \
"https://huggingface.co/datasets/ykumards/open-i/resolve/main/data/train-00003-of-00005-1d66a487a8489b7f.parquet" \
-O /content/IU-Xray-source/data/train-00003-of-00005-1d66a487a8489b7f.parquet

!wget -q --show-progress \
"https://huggingface.co/datasets/ykumards/open-i/resolve/main/data/train-00004-of-00005-208b7d689f1c7b70.parquet" \
-O /content/IU-Xray-source/data/train-00004-of-00005-208b7d689f1c7b70.parquet

/content/IU-Xray-so 100%[===================>] 405.48M  20.2MB/s    in 7.0s
/content/IU-Xray-so 100%[===================>] 398.66M  46.2MB/s    in 6.9s
/content/IU-Xray-so 100%[===================>] 396.41M  43.9MB/s    in 10s
/content/IU-Xray-so 100%[===================>] 396.53M   112MB/s    in 4.5s
/content/IU-Xray-so 100%[===================>] 401.69M  89.9MB/s    in 5.1s

In [ ]:
from pathlib import Path

parquets = sorted(DATA_DIR.glob("*.parquet"))

print("Parquet files:", len(parquets))

for p in parquets:
    print(f"{p.name}: {p.stat().st_size:,} bytes")

Parquet files: 5
train-00000-of-00005-c80629f6027d8eb1.parquet: 425,182,167 bytes
train-00001-of-00005-07e6c158a3f56170.parquet: 418,023,741 bytes
train-00002-of-00005-653f05c8b15c22c6.parquet: 415,669,328 bytes
train-00003-of-00005-1d66a487a8489b7f.parquet: 415,787,300 bytes
train-00004-of-00005-208b7d689f1c7b70.parquet: 421,207,075 bytes

In [ ]:
import pandas as pd
from PIL import Image
from io import BytesIO

TARGET_UID = 195
found = False

for parquet in parquets:
    print("Checking:", parquet.name)

    table = pd.read_parquet(
        parquet,
        columns=["uid", "img_frontal"]
    )

    matches = table[table["uid"] == TARGET_UID]

    if len(matches) == 0:
        continue

    row = matches.iloc[0]
    image_bytes = row["img_frontal"]

    print("Found UID:", TARGET_UID)
    print("Image bytes:", len(image_bytes))

    output_dir = ROOT / "external_data" / "IU-Xray" / "images"
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / "IU_195_frontal.jpg"

    with open(output_path, "wb") as f:
        f.write(image_bytes)

    print("Saved:", output_path)

    with Image.open(output_path) as img:
        print("Format:", img.format)
        print("Dimensions:", img.size)
        print("Mode:", img.mode)

    found = True
    break

if not found:
    raise RuntimeError("UID 195 was not found in any Parquet shard.")

Checking: train-00000-of-00005-c80629f6027d8eb1.parquet
Found UID: 195
Image bytes: 382593
Saved: /content/Evidence-State-Radiology/external_data/IU-Xray/images/IU_195_frontal.jpg
Format: JPEG
Dimensions: (2048, 2059)
Mode: L

In [ ]:
image_path = (
    ROOT
    / "external_data"
    / "IU-Xray"
    / "images"
    / "IU_195_frontal.jpg"
)

print("Exists:", image_path.exists())
print("Size:", image_path.stat().st_size, "bytes")

Exists: True
Size: 382593 bytes

In [ ]:
from pathlib import Path
from PIL import Image
import pandas as pd

ROOT = Path("/content/Evidence-State-Radiology")

benchmark = pd.read_csv(
    ROOT / "results" / "tables" / "phase16_perturbations.csv"
)

uid195_rows = benchmark[benchmark["uid"] == 195].copy()

image_path = ROOT / "external_data" / "IU-Xray" / "images" / "IU_195_frontal.jpg"

frontal_image = Image.open(image_path).convert("RGB")

print("Image:", image_path)
print("Image size:", frontal_image.size)
print()

print(
    uid195_rows[
        ["sample_id", "condition", "perturbed_context"]
    ].to_string(index=False)
)

Image: /content/Evidence-State-Radiology/external_data/IU-Xray/images/IU_195_frontal.jpg
Image size: (2048, 2059)

sample_id              condition                                perturbed_context
   IU_195             sufficient XXXX-year-old female with coughing and wheezing.
   IU_195   syntactic_incomplete                        XXXX-year-old female with
   IU_195 evidentiary_incomplete                  XXXX-year-old female, wheezing.
   IU_195             irrelevant                              Chest pain, dyspnea
   IU_195            conflicting                  The patient has a pneumothorax.
   IU_195           insufficient                                              NaN

In [ ]:
import torch

conflict_context = uid195_rows.loc[
    uid195_rows["condition"] == "conflicting",
    "perturbed_context"
].iloc[0]

print("Conflict context:")
print(conflict_context)

processed_context = processor.format_and_preprocess_reporting_input(
    current_frontal=frontal_image,
    current_lateral=None,
    prior_frontal=None,
    indication=conflict_context,
    technique=None,
    comparison=None,
    prior_report=None,
    return_tensors="pt",
    get_grounding=False,
).to("cuda")

processed_visual = processor.format_and_preprocess_reporting_input(
    current_frontal=frontal_image,
    current_lateral=None,
    prior_frontal=None,
    indication=None,
    technique=None,
    comparison=None,
    prior_report=None,
    return_tensors="pt",
    get_grounding=False,
).to("cuda")

print("Context input:")
for k, v in processed_context.items():
    if hasattr(v, "shape"):
        print(k, tuple(v.shape))

print("\nVisual input:")
for k, v in processed_visual.items():
    if hasattr(v, "shape"):
        print(k, tuple(v.shape))

Conflict context:
The patient has a pneumothorax.
Context input:
input_ids (1, 1462)
attention_mask (1, 1462)
pixel_values (1, 3, 518, 518)

Visual input:
input_ids (1, 1455)
attention_mask (1, 1455)
pixel_values (1, 3, 518, 518)

In [ ]:
with torch.inference_mode():
    official_output = model.generate(
        **processed_context,
        max_new_tokens=128,
        use_cache=True,
    )

official_text = processor.decode(
    official_output[0],
    skip_special_tokens=True
)

print("OFFICIAL MAIRA-2")
print(official_text)
print("Token count:", official_output.shape[1])

OFFICIAL MAIRA-2
You are an expert radiology assistant tasked with interpreting a chest X-ray study.  USER:  Given the current frontal image only<image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image><image> Provide a description of the findings in the radiology study in comparison to the prior frontal image. INDICATION: The patient has a pneumothorax. TECHNIQUE: N/A COMPARISON: N/A  ASSISTANT:  A single-view chest x-ray demonstrates a normal heart size. There is no acute consolidation, effusion or pneumothorax seen. No adenopathy is appreciated.
Token count: 1507

In [ ]:
with torch.inference_mode():
    context_forward = model(
        **processed_context,
        use_cache=True,
    )

    visual_forward = model(
        **processed_visual,
        use_cache=True,
    )

context_cache = context_forward.past_key_values
visual_cache = visual_forward.past_key_values

context_logits = context_forward.logits[:, -1, :]
visual_logits = visual_forward.logits[:, -1, :]

print("Context cache:", type(context_cache).__name__)
print("Visual cache:", type(visual_cache).__name__)

print("Context logits:", tuple(context_logits.shape))
print("Visual logits:", tuple(visual_logits.shape))

Context cache: DynamicCache
Visual cache: DynamicCache
Context logits: (1, 32207)
Visual logits: (1, 32207)

In [ ]:
import torch

def two_stream_decode_no_copy(
    model,
    context_cache,
    visual_cache,
    context_logits,
    visual_logits,
    lambda_value=0.0,
    max_new_tokens=128,
):
    """
    Two-stream contrastive decoding for MAIRA-2.

    Context stream:
        image + clinical context

    Visual stream:
        image only

    At every generation step:
        adjusted_logits =
            context_logits
            - lambda * (context_logits - visual_logits)

    The selected token is appended to both streams.

    lambda=0 must exactly reproduce ordinary
    context-conditioned MAIRA-2 greedy generation.
    """

    device = context_logits.device

    # First generated token from the initial prompt caches.
    adjusted_logits = (
        context_logits
        - lambda_value * (context_logits - visual_logits)
    )

    next_token = torch.argmax(
        adjusted_logits,
        dim=-1,
        keepdim=True,
    )

    generated_tokens = [next_token]

    # Continue autoregressively.
    for _ in range(max_new_tokens - 1):

        # Feed the previously selected token into BOTH streams.
        context_outputs = model(
            input_ids=next_token,
            past_key_values=context_cache,
            use_cache=True,
        )

        visual_outputs = model(
            input_ids=next_token,
            past_key_values=visual_cache,
            use_cache=True,
        )

        context_cache = context_outputs.past_key_values
        visual_cache = visual_outputs.past_key_values

        context_logits = context_outputs.logits[:, -1, :]
        visual_logits = visual_outputs.logits[:, -1, :]

        adjusted_logits = (
            context_logits
            - lambda_value * (
                context_logits - visual_logits
            )
        )

        next_token = torch.argmax(
            adjusted_logits,
            dim=-1,
            keepdim=True,
        )

        generated_tokens.append(next_token)

    return torch.cat(generated_tokens, dim=1)

In [ ]:
with torch.inference_mode():
    context_forward = model(
        **processed_context,
        use_cache=True,
    )

    visual_forward = model(
        **processed_visual,
        use_cache=True,
    )

context_cache_test = context_forward.past_key_values
visual_cache_test = visual_forward.past_key_values

context_logits_test = context_forward.logits[:, -1, :]
visual_logits_test = visual_forward.logits[:, -1, :]

print("Fresh caches ready.")
print("Context cache:", type(context_cache_test).__name__)
print("Visual cache:", type(visual_cache_test).__name__)

Fresh caches ready.
Context cache: DynamicCache
Visual cache: DynamicCache

In [ ]:
with torch.inference_mode():
    custom_output = two_stream_decode_no_copy(
        model=model,
        context_cache=context_cache_test,
        visual_cache=visual_cache_test,
        context_logits=context_logits_test,
        visual_logits=visual_logits_test,
        lambda_value=0.0,
        max_new_tokens=128,
    )

custom_text = processor.decode(
    custom_output[0],
    skip_special_tokens=True,
)

print("CUSTOM TWO-STREAM λ=0")
print(custom_text)

print()
print("Official token shape:", tuple(official_output.shape))
print("Custom token shape:  ", tuple(custom_output.shape))

print(
    "Exact token equivalence:",
    torch.equal(official_output, custom_output)
)

print(
    "Exact text equivalence:",
    official_text == custom_text
)

CUSTOM TWO-STREAM λ=0
A single-view chest x-ray demonstrates a normal heart size. There is no acute consolidation, effusion or pneumothorax seen. No adenopathy is appreciated.ss a small right apical pneumothorax. This finding was not seen on the prior examination.s a small right apical pneumothorax. This finding was not seen on the prior examination.s a small right apical pneumothorax. This finding was not seen on the prior examination.s a small right apical pneum

Official token shape: (1, 1507)
Custom token shape:   (1, 128)
Exact token equivalence: False
Exact text equivalence: False

In [ ]:
context_prompt_len = processed_context["input_ids"].shape[1]

official_generated = official_output[
    :,
    context_prompt_len:
]

print("Prompt tokens:", context_prompt_len)
print("Official total tokens:", official_output.shape[1])
print("Official generated tokens:", official_generated.shape[1])

print(
    "Official EOS token:",
    model.generation_config.eos_token_id
)

print(
    "Last official generated token:",
    official_generated[0, -1].item()
)

Prompt tokens: 1462
Official total tokens: 1507
Official generated tokens: 45
Official EOS token: 2
Last official generated token: 2

In [ ]:
eos_id = model.generation_config.eos_token_id

eos_positions = (
    official_generated[0] == eos_id
).nonzero(as_tuple=True)[0]

print("EOS positions:", eos_positions.tolist())

EOS positions: [44]

In [ ]:
n = min(
    official_generated.shape[1],
    custom_output.shape[1]
)

official_prefix = official_generated[0, :n]
custom_prefix = custom_output[0, :n]

matches = official_prefix == custom_prefix

print("Compared tokens:", n)
print("Matching tokens:", matches.sum().item())
print("First mismatch:",
      (~matches).nonzero(as_tuple=True)[0][0].item()
      if (~matches).any() else "NONE"
)

Compared tokens: 45
Matching tokens: 45
First mismatch: NONE

In [ ]:
print("\nOFFICIAL GENERATED:")
print(
    processor.decode(
        official_generated[0, :60],
        skip_special_tokens=False
    )
)

print("\nCUSTOM:")
print(
    processor.decode(
        custom_output[0, :60],
        skip_special_tokens=False
    )
)

OFFICIAL GENERATED:
A single-view chest x-ray demonstrates a normal heart size. There is no acute consolidation, effusion or pneumothorax seen. No adenopathy is appreciated.</s>

CUSTOM:
A single-view chest x-ray demonstrates a normal heart size. There is no acute consolidation, effusion or pneumothorax seen. No adenopathy is appreciated.</s>s</s></s>s a small right apical pneumothorax.

In [ ]:
print("Official first generated token:")
print(
    official_generated[0, 0].item(),
    repr(
        processor.decode(
            official_generated[0, :1],
            skip_special_tokens=False
        )
    )
)

print("\nCustom first generated token:")
print(
    custom_output[0, 0].item(),
    repr(
        processor.decode(
            custom_output[0, :1],
            skip_special_tokens=False
        )
    )
)

Official first generated token:
319 'A'

Custom first generated token:
319 'A'

In [ ]:
import torch

def two_stream_decode_no_copy(
    model,
    context_cache,
    visual_cache,
    context_logits,
    visual_logits,
    lambda_value=0.0,
    max_new_tokens=128,
):
    """
    MAIRA-2 two-stream contrastive greedy decoder.

    Context stream:
        image + clinical context

    Visual stream:
        image only

    adjusted_logits =
        context_logits
        - lambda * (context_logits - visual_logits)

    lambda=0 reproduces the context-conditioned
    MAIRA-2 greedy generation sequence.

    Stops immediately at EOS.
    """

    eos_id = model.generation_config.eos_token_id

    generated_tokens = []

    # First token
    adjusted_logits = (
        context_logits
        - lambda_value * (context_logits - visual_logits)
    )

    next_token = torch.argmax(
        adjusted_logits,
        dim=-1,
        keepdim=True,
    )

    generated_tokens.append(next_token)

    # Stop immediately if first token is EOS
    if eos_id is not None and torch.all(next_token == eos_id):
        return torch.cat(generated_tokens, dim=1)

    for _ in range(max_new_tokens - 1):

        context_outputs = model(
            input_ids=next_token,
            past_key_values=context_cache,
            use_cache=True,
        )

        visual_outputs = model(
            input_ids=next_token,
            past_key_values=visual_cache,
            use_cache=True,
        )

        context_cache = context_outputs.past_key_values
        visual_cache = visual_outputs.past_key_values

        context_logits = context_outputs.logits[:, -1, :]
        visual_logits = visual_outputs.logits[:, -1, :]

        adjusted_logits = (
            context_logits
            - lambda_value * (
                context_logits - visual_logits
            )
        )

        next_token = torch.argmax(
            adjusted_logits,
            dim=-1,
            keepdim=True,
        )

        generated_tokens.append(next_token)

        # MAIRA-2 EOS termination
        if eos_id is not None and torch.all(next_token == eos_id):
            break

    return torch.cat(generated_tokens, dim=1)

In [ ]:
with torch.inference_mode():
    context_forward = model(
        **processed_context,
        use_cache=True,
    )

    visual_forward = model(
        **processed_visual,
        use_cache=True,
    )

context_cache_test = context_forward.past_key_values
visual_cache_test = visual_forward.past_key_values

context_logits_test = context_forward.logits[:, -1, :]
visual_logits_test = visual_forward.logits[:, -1, :]

In [ ]:
with torch.inference_mode():
    custom_output = two_stream_decode_no_copy(
        model=model,
        context_cache=context_cache_test,
        visual_cache=visual_cache_test,
        context_logits=context_logits_test,
        visual_logits=visual_logits_test,
        lambda_value=0.0,
        max_new_tokens=128,
    )

custom_text = processor.decode(
    custom_output[0],
    skip_special_tokens=True,
)

official_generated = official_output[
    :,
    processed_context["input_ids"].shape[1]:
]

print("Official generated shape:", tuple(official_generated.shape))
print("Custom generated shape:  ", tuple(custom_output.shape))

print("\nOfficial:")
print(
    processor.decode(
        official_generated[0],
        skip_special_tokens=False
    )
)

print("\nCustom:")
print(
    processor.decode(
        custom_output[0],
        skip_special_tokens=False
    )
)

print("\nExact token equivalence:",
      torch.equal(official_generated, custom_output))

print("Exact text equivalence:",
      processor.decode(
          official_generated[0],
          skip_special_tokens=True
      ) == custom_text)

Official generated shape: (1, 45)
Custom generated shape:   (1, 45)

Official:
A single-view chest x-ray demonstrates a normal heart size. There is no acute consolidation, effusion or pneumothorax seen. No adenopathy is appreciated.</s>

Custom:
A single-view chest x-ray demonstrates a normal heart size. There is no acute consolidation, effusion or pneumothorax seen. No adenopathy is appreciated.</s>

Exact token equivalence: True
Exact text equivalence: True

In [ ]:
from pathlib import Path
import pandas as pd
import hashlib

ROOT = Path("/content/Evidence-State-Radiology")

OUT_DIR = ROOT / "results" / "tables" / "phase26d_claim_evaluation"
DOC_DIR = ROOT / "docs"

OUT_DIR.mkdir(parents=True, exist_ok=True)
DOC_DIR.mkdir(parents=True, exist_ok=True)

lambda_rows = [
    {"lambda": 0.00, "unsupported_rate": 0.076087, "supported_claims": 96, "omissions": 124},
    {"lambda": 0.10, "unsupported_rate": 0.077348, "supported_claims": 89, "omissions": 128},
    {"lambda": 0.25, "unsupported_rate": 0.060440, "supported_claims": 84, "omissions": 132},
    {"lambda": 0.40, "unsupported_rate": 0.048485, "supported_claims": 67, "omissions": 152},
    {"lambda": 0.50, "unsupported_rate": 0.021739, "supported_claims": 61, "omissions": 163},
]

df = pd.DataFrame(lambda_rows)

baseline_supported = 96
baseline_omissions = 124
baseline_risk = 0.076087

df["supported_retention"] = df["supported_claims"] / baseline_supported
df["omission_increase"] = (
    (df["omissions"] - baseline_omissions) / baseline_omissions
)
df["risk_reduction"] = (
    (baseline_risk - df["unsupported_rate"]) / baseline_risk
)

df["qualifies"] = (
    (df["risk_reduction"] > 0)
    & (df["supported_retention"] >= 0.80)
    & (df["omission_increase"] <= 0.25)
)

eligible = df[df["qualifies"]].sort_values("lambda")

selected_lambda = float(eligible.iloc[0]["lambda"])

print(df.to_string(index=False))
print("\nSELECTED LAMBDA:", selected_lambda)

assert selected_lambda == 0.25

 lambda  unsupported_rate  supported_claims  omissions  supported_retention  omission_increase  risk_reduction  qualifies
   0.00          0.076087                96        124             1.000000           0.000000        0.000000      False
   0.10          0.077348                89        128             0.927083           0.032258       -0.016573      False
   0.25          0.060440                84        132             0.875000           0.064516        0.205646       True
   0.40          0.048485                67        152             0.697917           0.225806        0.362769      False
   0.50          0.021739                61        163             0.635417           0.314516        0.714288      False

SELECTED LAMBDA: 0.25

In [ ]:
policy_csv = OUT_DIR / "phase26d_lambda_selection.csv"
df.to_csv(policy_csv, index=False)

policy_text = f"""# Phase 26D-7 — Lambda Selection Policy

## Purpose

Select the contrastive decoding strength using the development cohort
before evaluation-cohort generation.

## Development cohort

- 16 studies
- 96 condition-level records
- 6 evidence conditions
- Lambda candidates: 0.00, 0.10, 0.25, 0.40, 0.50

## Selection rule

1. Primary objective: reduce pooled unsupported claim rate relative to lambda=0.
2. Supported-claim retention must be >= 80% of lambda=0.
3. Omission increase must be <= 25% relative to lambda=0.
4. Among candidates satisfying all constraints, select the smallest lambda.

## Frozen selection

Selected lambda = {selected_lambda:.2f}

The evaluation cohort was not used to select lambda.
"""

policy_md = DOC_DIR / "phase26d_lambda_selection_policy.md"
policy_md.write_text(policy_text, encoding="utf-8")

print(policy_md)
print(policy_csv)

/content/Evidence-State-Radiology/docs/phase26d_lambda_selection_policy.md
/content/Evidence-State-Radiology/results/tables/phase26d_claim_evaluation/phase26d_lambda_selection.csv

In [ ]:
print("Split columns:")
print(split.columns.tolist())

print("\nFirst rows:")
print(split.head().to_string(index=False))

Split columns:
['study_id', 'split']

First rows:
 study_id      split
       32 evaluation
       36 evaluation
       44 evaluation
       49 evaluation
       53 evaluation

In [ ]:
# The frozen split is study-level:
# study_id -> split
#
# The benchmark is condition-level:
# uid/sample_id/condition -> benchmark row

split_check = benchmark.copy()

split_check["study_id"] = split_check["uid"].astype(int)

split_check = split_check.merge(
    split,
    on="study_id",
    how="left",
    validate="many_to_one",
)

print("Rows:", len(split_check))
print("Missing split:", split_check["split"].isna().sum())

print("\nSplit × condition:")
print(
    split_check
    .groupby(["split", "condition"])
    .size()
    .unstack(fill_value=0)
)

print("\nStudies by split:")
print(
    split_check
    .groupby("split")["uid"]
    .nunique()
)

assert len(split_check) == 600
assert split_check["split"].notna().all()

dev = split_check[split_check["split"] == "development"]
evaluation = split_check[split_check["split"] == "evaluation"]

assert dev["uid"].nunique() == 16
assert evaluation["uid"].nunique() == 80

assert len(dev) == 96
assert len(evaluation) == 480

assert dev.groupby("condition").size().eq(16).all()
assert evaluation.groupby("condition").size().eq(80).all()

assert set(dev["uid"]).isdisjoint(
    set(evaluation["uid"])
)

print("\nPHASE 26D SPLIT VALIDATION: PASS")

Rows: 600
Missing split: 24

Split × condition:
condition    conflicting  evidentiary_incomplete  insufficient  irrelevant  \
split
development           16                      16            16          16
evaluation            80                      80            80          80

condition    sufficient  syntactic_incomplete
split
development          16                    16
evaluation           80                    80

Studies by split:
split
development    16
evaluation     80
Name: uid, dtype: int64

AssertionError:

In [ ]:
EXCLUDED_UIDS = {74, 597, 803, 885}

eligible_benchmark = benchmark[
    ~benchmark["uid"].astype(int).isin(EXCLUDED_UIDS)
].copy()

eligible_benchmark["study_id"] = (
    eligible_benchmark["uid"].astype(int)
)

split_check = eligible_benchmark.merge(
    split,
    on="study_id",
    how="left",
    validate="many_to_one",
)

print("Eligible benchmark rows:", len(eligible_benchmark))
print("Split rows:", len(split_check))
print(
    "Missing split:",
    split_check["split"].isna().sum()
)

print("\nSplit × condition:")
print(
    split_check
    .groupby(["split", "condition"])
    .size()
    .unstack(fill_value=0)
)

print("\nStudies by split:")
print(
    split_check
    .groupby("split")["uid"]
    .nunique()
)

assert len(eligible_benchmark) == 576
assert len(split_check) == 576
assert split_check["split"].notna().all()

dev = split_check[
    split_check["split"] == "development"
]

evaluation = split_check[
    split_check["split"] == "evaluation"
]

assert dev["uid"].nunique() == 16
assert evaluation["uid"].nunique() == 80

assert len(dev) == 96
assert len(evaluation) == 480

assert (
    dev.groupby("condition")
    .size()
    .eq(16)
    .all()
)

assert (
    evaluation.groupby("condition")
    .size()
    .eq(80)
    .all()
)

assert set(dev["uid"]).isdisjoint(
    set(evaluation["uid"])
)

print("\nPHASE 26D SPLIT VALIDATION: PASS")

Eligible benchmark rows: 576
Split rows: 576
Missing split: 0

Split × condition:
condition    conflicting  evidentiary_incomplete  insufficient  irrelevant  \
split
development           16                      16            16          16
evaluation            80                      80            80          80

condition    sufficient  syntactic_incomplete
split
development          16                    16
evaluation           80                    80

Studies by split:
split
development    16
evaluation     80
Name: uid, dtype: int64

PHASE 26D SPLIT VALIDATION: PASS

In [ ]:
eval_benchmark = split_check[
    split_check["split"] == "evaluation"
].copy()

eval_benchmark = eval_benchmark.sort_values(
    ["uid", "condition"]
).reset_index(drop=True)

print("Evaluation records:", len(eval_benchmark))
print("Evaluation studies:", eval_benchmark["uid"].nunique())

print("\nCondition counts:")
print(
    eval_benchmark["condition"]
    .value_counts()
    .sort_index()
)

assert len(eval_benchmark) == 480
assert eval_benchmark["uid"].nunique() == 80
assert (
    eval_benchmark["condition"]
    .value_counts()
    .eq(80)
    .all()
)

print("\nEVALUATION COHORT: PASS")

Evaluation records: 480
Evaluation studies: 80

Condition counts:
condition
conflicting               80
evidentiary_incomplete    80
insufficient              80
irrelevant                80
sufficient                80
syntactic_incomplete      80
Name: count, dtype: int64

EVALUATION COHORT: PASS

In [ ]:
from pathlib import Path
import pandas as pd

eval_uids = sorted(
    eval_benchmark["uid"].astype(int).unique()
)

image_dir = (
    ROOT
    / "external_data"
    / "IU-Xray"
    / "images"
)

image_dir.mkdir(parents=True, exist_ok=True)

remaining = set(eval_uids)

for parquet in sorted(DATA_DIR.glob("*.parquet")):

    if not remaining:
        break

    print("\nChecking:", parquet.name)

    table = pd.read_parquet(
        parquet,
        columns=["uid", "img_frontal"]
    )

    matches = table[
        table["uid"].isin(remaining)
    ]

    print("Matches:", len(matches))

    for _, row in matches.iterrows():

        uid = int(row["uid"])
        image_bytes = row["img_frontal"]

        if image_bytes is None:
            print("WARNING: missing frontal:", uid)
            continue

        output_path = (
            image_dir / f"IU_{uid}_frontal.jpg"
        )

        with open(output_path, "wb") as f:
            f.write(image_bytes)

        remaining.remove(uid)

print("\nExpected:", len(eval_uids))
print("Recovered:", len(eval_uids) - len(remaining))
print("Missing:", sorted(remaining))

assert len(remaining) == 0

print("\nALL 80 EVALUATION IMAGES RECOVERED: PASS")

Checking: train-00000-of-00005-c80629f6027d8eb1.parquet
Matches: 61

Checking: train-00001-of-00005-07e6c158a3f56170.parquet
Matches: 19

Expected: 80
Recovered: 80
Missing: []

ALL 80 EVALUATION IMAGES RECOVERED: PASS

In [ ]:
from PIL import Image

audit = []

for uid in eval_uids:

    path = image_dir / f"IU_{uid}_frontal.jpg"

    assert path.exists(), f"Missing: {uid}"

    with Image.open(path) as img:
        img.verify()

    with Image.open(path) as img:
        audit.append({
            "uid": uid,
            "bytes": path.stat().st_size,
            "width": img.width,
            "height": img.height,
        })

image_audit = pd.DataFrame(audit)

print(image_audit.to_string(index=False))

print("\nImages:", len(image_audit))
print("Unique UIDs:", image_audit["uid"].nunique())
print("Zero-byte:", (image_audit["bytes"] == 0).sum())

assert len(image_audit) == 80
assert image_audit["uid"].nunique() == 80
assert (image_audit["bytes"] > 0).all()

print("\nIMAGE INTEGRITY: PASS")

 uid  bytes  width  height
  32 214452   2051    2048
  36 300010   2048    2496
  44 268500   2048    2070
  49 302387   2496    2048
  53 211711   2048    2048
  66 343193   2121    2048
  67 298940   2048    2048
 175 237941   2075    2048
 185 268012   2048    2048
 190 244610   2326    2048
 247 269477   2048    2050
 254 346080   2048    2496
 270 328510   2048    2051
 275 314403   2048    2496
 287 460847   2494    2048
 297 379094   2494    2048
 303 362519   2131    2048
 304 459107   2494    2048
 313 269016   2048    2048
 329 276666   2486    2048
 340 422374   2494    2048
 341 353696   2048    2157
 372 547110   2494    2048
 382 301044   2048    2496
 388 282116   2048    2048
 400 302070   2496    2048
 417 418099   2455    2048
 437 390840   2496    2048
 451 305104   2048    2496
 460 218963   2048    2048
 461 291464   2048    2048
 463 306149   2048    2048
 475 263408   2051    2048
 486 335356   2048    2048
 493 282194   2496    2048
 498 378243   2496    2048
 502 344352   2077    2048
 519 268908   2051    2048
 527 264875   2062    2048
 551 270585   2051    2048
 567 242430   2051    2048
 581 236735   2048    2048
 585 339011   2048    2195
 586 291871   2048    2048
 590 280513   2171    2048
 594 411610   2500    2048
 595 281547   2048    2048
 600 247073   2048    2048
 604 219849   2048    2048
 628 321287   2048    2048
 633 269797   2051    2048
 645 315804   2496    2048
 653 283009   2048    2048
 655 240501   2048    2048
 688 201043   2048    2048
 702 415456   2405    2048
 729 305572   2496    2048
 753 309700   2048    2048
 772 425791   2474    2048
 782 242234   2048    2048
 784 375026   2500    2048
 806 417476   2474    2048
 814 288992   2048    2048
 827 406108   2472    2048
 854 278958   2048    2048
 871 223676   2496    2048
 927 233942   2051    2048
 963 318589   2048    2048
 975 238812   2051    2048
 989 234707   2048    2486
 991 279837   2500    2048
1001 325603   2160    2048
1008 481463   2494    2048
1034 376139   2048    2179
1059 299366   2496    2048
1097 340288   2048    2243
1114 306491   2496    2048
1172 331645   2135    2048
1173 301728   2048    2496
1205 503367   2376    2048

Images: 80
Unique UIDs: 80
Zero-byte: 0

IMAGE INTEGRITY: PASS

In [ ]:
import time
import pandas as pd
import torch
from pathlib import Path
from PIL import Image

EVAL_OUT = (
    ROOT
    / "results"
    / "maira2_contrastive"
    / "phase26d_evaluation"
)

EVAL_OUT.mkdir(
    parents=True,
    exist_ok=True
)

RESULT_CSV = (
    EVAL_OUT
    / "phase26d_evaluation_generation.csv"
)

SELECTED_LAMBDA = 0.25

print("Output:", RESULT_CSV)
print("Selected lambda:", SELECTED_LAMBDA)

Output: /content/Evidence-State-Radiology/results/maira2_contrastive/phase26d_evaluation/phase26d_evaluation_generation.csv
Selected lambda: 0.25

In [ ]:
eval_benchmark = eval_benchmark.sort_values(
    ["uid", "condition"]
).reset_index(drop=True)

print("Evaluation records:", len(eval_benchmark))
print("Studies:", eval_benchmark["uid"].nunique())

print(
    eval_benchmark[
        ["sample_id", "uid", "condition", "perturbed_context"]
    ].head(12).to_string(index=False)
)

assert len(eval_benchmark) == 480
assert eval_benchmark["uid"].nunique() == 80
assert eval_benchmark["condition"].value_counts().eq(80).all()

Evaluation records: 480
Studies: 80
sample_id  uid              condition                                               perturbed_context
    IU_32   32            conflicting                                        Cardiomegaly is present.
    IU_32   32 evidentiary_incomplete                     hx XXXX nodules, XXXX for changes in lungs.
    IU_32   32           insufficient                                                             NaN
    IU_32   32             irrelevant          XXXX XXXX with COPD/emphysema and dyspnea on exertion.
    IU_32   32             sufficient WEAKNESS OF MUSCLES; hx XXXX nodules; XXXX for changes in lungs
    IU_32   32   syntactic_incomplete                                                     WEAKNESS OF
    IU_36   36            conflicting                                 The patient has a pneumothorax.
    IU_36   36 evidentiary_incomplete                       XXXX-year-old female, rule out pneumonia.
    IU_36   36           insufficient                                                             NaN
    IU_36   36             irrelevant       XXXX-year-old with hypoxia and shortness of breath. XXXX.
    IU_36   36             sufficient      XXXX-year-old female with chest pain, rule out pneumonia..
    IU_36   36   syntactic_incomplete                                       XXXX-year-old female with

In [ ]:
def prepare_maira_inputs(image, context):

    context_input = processor.format_and_preprocess_reporting_input(
        current_frontal=image,
        current_lateral=None,
        prior_frontal=None,
        indication=context if pd.notna(context) else None,
        technique=None,
        comparison=None,
        prior_report=None,
        return_tensors="pt",
        get_grounding=False,
    ).to("cuda")

    visual_input = processor.format_and_preprocess_reporting_input(
        current_frontal=image,
        current_lateral=None,
        prior_frontal=None,
        indication=None,
        technique=None,
        comparison=None,
        prior_report=None,
        return_tensors="pt",
        get_grounding=False,
    ).to("cuda")

    return context_input, visual_input

In [ ]:
def generate_maira_trajectory(
    image,
    context,
    lambda_value,
):

    context_input, visual_input = prepare_maira_inputs(
        image,
        context,
    )

    with torch.inference_mode():

        context_forward = model(
            **context_input,
            use_cache=True,
        )

        visual_forward = model(
            **visual_input,
            use_cache=True,
        )

    context_cache = (
        context_forward.past_key_values
    )

    visual_cache = (
        visual_forward.past_key_values
    )

    context_logits = (
        context_forward.logits[:, -1, :]
    )

    visual_logits = (
        visual_forward.logits[:, -1, :]
    )

    with torch.inference_mode():

        output_tokens = two_stream_decode_no_copy(
            model=model,
            context_cache=context_cache,
            visual_cache=visual_cache,
            context_logits=context_logits,
            visual_logits=visual_logits,
            lambda_value=lambda_value,
            max_new_tokens=128,
        )

    text = processor.decode(
        output_tokens[0],
        skip_special_tokens=True,
    )

    return (
        text,
        int(output_tokens.shape[1]),
    )

In [ ]:
# ============================================================
# Phase26D Evaluation Generation
# Resume-safe checkpointed generation
# Key = (sample_id, condition, lambda)
# ============================================================

if RESULT_CSV.exists():

    completed = pd.read_csv(
        RESULT_CSV
    )

else:

    completed = pd.DataFrame()


# ------------------------------------------------------------
# Build completed trajectory keys
# IMPORTANT:
# condition MUST be part of the key.
# ------------------------------------------------------------

completed_keys = set()

if len(completed):

    completed_keys = set(
        zip(
            completed["sample_id"].astype(str),
            completed["condition"].astype(str),
            completed["lambda"].astype(float)
        )
    )


# ------------------------------------------------------------
# Preserve all existing checkpoint rows
# ------------------------------------------------------------

rows = (
    completed.to_dict("records")
    if len(completed)
    else []
)


# ------------------------------------------------------------
# Evaluation target
# 480 records × 2 lambdas = 960 trajectories
# ------------------------------------------------------------

total = len(eval_benchmark) * 2
processed = len(completed_keys)

print(
    f"Existing completed trajectories: "
    f"{processed}/{total}"
)

print(
    f"Remaining trajectories: "
    f"{total - processed}"
)


# ------------------------------------------------------------
# Generation loop
# ------------------------------------------------------------

for _, row in eval_benchmark.iterrows():

    sample_id = str(
        row["sample_id"]
    )

    condition = str(
        row["condition"]
    )

    image_path = (
        ROOT / row["frontal_image"]
    )

    image = Image.open(
        image_path
    ).convert("RGB")


    for lambda_value in [
        0.00,
        SELECTED_LAMBDA,
    ]:

        # ----------------------------------------------------
        # IMPORTANT:
        # A trajectory is uniquely identified by:
        #
        # (sample_id, condition, lambda)
        # ----------------------------------------------------

        key = (
            sample_id,
            condition,
            float(lambda_value),
        )


        # ----------------------------------------------------
        # Skip trajectories already present in checkpoint
        # ----------------------------------------------------

        if key in completed_keys:

            continue


        start = time.time()


        try:

            text, token_count = (
                generate_maira_trajectory(
                    image=image,
                    context=row[
                        "perturbed_context"
                    ],
                    lambda_value=lambda_value,
                )
            )

            status = "success"
            error = ""


        except Exception as exc:

            text = ""
            token_count = 0
            status = "failed"
            error = repr(exc)


        elapsed = (
            time.time() - start
        )


        # ----------------------------------------------------
        # Store trajectory result
        # ----------------------------------------------------

        record = {

            "sample_id": sample_id,

            "uid": int(
                row["uid"]
            ),

            "condition": condition,

            "evidence_state": row[
                "evidence_state"
            ],

            "perturbed_context": row[
                "perturbed_context"
            ],

            "frontal_image": row[
                "frontal_image"
            ],

            "findings": row[
                "findings"
            ],

            "impression": row[
                "impression"
            ],

            "lambda": float(
                lambda_value
            ),

            "report": text,

            "num_tokens": token_count,

            "runtime_seconds": elapsed,

            "status": status,

            "error": error,
        }


        rows.append(
            record
        )


        # ----------------------------------------------------
        # Mark this exact trajectory as completed
        # ----------------------------------------------------

        completed_keys.add(
            key
        )

        processed += 1


        # ----------------------------------------------------
        # Checkpoint after EVERY trajectory
        # ----------------------------------------------------

        pd.DataFrame(
            rows
        ).to_csv(
            RESULT_CSV,
            index=False,
        )


        print(
            f"[{processed}/{total}] "
            f"{sample_id} | "
            f"{condition} | "
            f"λ={lambda_value:.2f} | "
            f"{status} | "
            f"{elapsed:.2f}s"
        )


print("\n================================")
print("EVALUATION GENERATION COMPLETE")
print("Rows:", len(rows))
print("Output:", RESULT_CSV)
print("================================")

Existing completed trajectories: 160/960
Remaining trajectories: 800
[161/960] IU_32 | evidentiary_incomplete | λ=0.00 | success | 7.97s
[162/960] IU_32 | evidentiary_incomplete | λ=0.25 | success | 7.69s
[163/960] IU_32 | insufficient | λ=0.00 | success | 4.43s
[164/960] IU_32 | insufficient | λ=0.25 | success | 4.27s
[165/960] IU_32 | irrelevant | λ=0.00 | success | 7.94s
[166/960] IU_32 | irrelevant | λ=0.25 | success | 7.12s
[167/960] IU_32 | sufficient | λ=0.00 | success | 6.00s
[168/960] IU_32 | sufficient | λ=0.25 | success | 6.39s
[169/960] IU_32 | syntactic_incomplete | λ=0.00 | success | 3.89s
[170/960] IU_32 | syntactic_incomplete | λ=0.25 | success | 3.80s
[171/960] IU_36 | evidentiary_incomplete | λ=0.00 | success | 16.88s
[172/960] IU_36 | evidentiary_incomplete | λ=0.25 | success | 9.21s
[173/960] IU_36 | insufficient | λ=0.00 | success | 4.17s
[174/960] IU_36 | insufficient | λ=0.25 | success | 4.17s
[175/960] IU_36 | irrelevant | λ=0.00 | success | 7.91s
[176/960] IU_36 | irrelevant | λ=0.25 | success | 6.41s
[177/960] IU_36 | sufficient | λ=0.00 | success | 9.85s
[178/960] IU_36 | sufficient | λ=0.25 | success | 10.13s
[179/960] IU_36 | syntactic_incomplete | λ=0.00 | success | 8.82s
[180/960] IU_36 | syntactic_incomplete | λ=0.25 | success | 9.62s
[181/960] IU_44 | evidentiary_incomplete | λ=0.00 | success | 9.98s
[182/960] IU_44 | evidentiary_incomplete | λ=0.25 | success | 8.50s
[183/960] IU_44 | insufficient | λ=0.00 | success | 3.95s
[184/960] IU_44 | insufficient | λ=0.25 | success | 4.06s
[185/960] IU_44 | irrelevant | λ=0.00 | success | 7.41s
[186/960] IU_44 | irrelevant | λ=0.25 | success | 10.00s
[187/960] IU_44 | sufficient | λ=0.00 | success | 9.05s
[188/960] IU_44 | sufficient | λ=0.25 | success | 8.69s
[189/960] IU_44 | syntactic_incomplete | λ=0.00 | success | 9.24s
[190/960] IU_44 | syntactic_incomplete | λ=0.25 | success | 11.97s
[191/960] IU_49 | evidentiary_incomplete | λ=0.00 | success | 5.18s
[192/960] IU_49 | evidentiary_incomplete | λ=0.25 | success | 4.72s
[193/960] IU_49 | insufficient | λ=0.00 | success | 4.08s
[194/960] IU_49 | insufficient | λ=0.25 | success | 4.16s
[195/960] IU_49 | irrelevant | λ=0.00 | success | 4.09s
[196/960] IU_49 | irrelevant | λ=0.25 | success | 4.10s
[197/960] IU_49 | sufficient | λ=0.00 | success | 4.63s
[198/960] IU_49 | sufficient | λ=0.25 | success | 4.73s
[199/960] IU_49 | syntactic_incomplete | λ=0.00 | success | 4.87s
[200/960] IU_49 | syntactic_incomplete | λ=0.25 | success | 4.85s
[201/960] IU_53 | evidentiary_incomplete | λ=0.00 | success | 8.88s
[202/960] IU_53 | evidentiary_incomplete | λ=0.25 | success | 6.83s
[203/960] IU_53 | insufficient | λ=0.00 | success | 10.06s
[204/960] IU_53 | insufficient | λ=0.25 | success | 10.09s
[205/960] IU_53 | irrelevant | λ=0.00 | success | 9.77s
[206/960] IU_53 | irrelevant | λ=0.25 | success | 9.35s
[207/960] IU_53 | sufficient | λ=0.00 | success | 7.50s
[208/960] IU_53 | sufficient | λ=0.25 | success | 8.57s
[209/960] IU_53 | syntactic_incomplete | λ=0.00 | success | 10.07s
[210/960] IU_53 | syntactic_incomplete | λ=0.25 | success | 6.96s
[211/960] IU_66 | evidentiary_incomplete | λ=0.00 | success | 4.15s
[212/960] IU_66 | evidentiary_incomplete | λ=0.25 | success | 4.19s
[213/960] IU_66 | insufficient | λ=0.00 | success | 3.86s
[214/960] IU_66 | insufficient | λ=0.25 | success | 3.86s
[215/960] IU_66 | irrelevant | λ=0.00 | success | 5.57s
[216/960] IU_66 | irrelevant | λ=0.25 | success | 5.56s
[217/960] IU_66 | sufficient | λ=0.00 | success | 13.17s
[218/960] IU_66 | sufficient | λ=0.25 | success | 13.33s
[219/960] IU_66 | syntactic_incomplete | λ=0.00 | success | 13.32s
[220/960] IU_66 | syntactic_incomplete | λ=0.25 | success | 13.66s
[221/960] IU_67 | evidentiary_incomplete | λ=0.00 | success | 11.05s
[222/960] IU_67 | evidentiary_incomplete | λ=0.25 | success | 8.20s
[223/960] IU_67 | insufficient | λ=0.00 | success | 7.08s
[224/960] IU_67 | insufficient | λ=0.25 | success | 6.84s
[225/960] IU_67 | irrelevant | λ=0.00 | success | 9.39s
[226/960] IU_67 | irrelevant | λ=0.25 | success | 7.09s
[227/960] IU_67 | sufficient | λ=0.00 | success | 10.72s
[228/960] IU_67 | sufficient | λ=0.25 | success | 9.73s
[229/960] IU_67 | syntactic_incomplete | λ=0.00 | success | 11.68s
[230/960] IU_67 | syntactic_incomplete | λ=0.25 | success | 7.81s
[231/960] IU_175 | evidentiary_incomplete | λ=0.00 | success | 7.09s
[232/960] IU_175 | evidentiary_incomplete | λ=0.25 | success | 6.94s
[233/960] IU_175 | insufficient | λ=0.00 | success | 5.16s
[234/960] IU_175 | insufficient | λ=0.25 | success | 5.03s
[235/960] IU_175 | irrelevant | λ=0.00 | success | 8.82s
[236/960] IU_175 | irrelevant | λ=0.25 | success | 9.42s
[237/960] IU_175 | sufficient | λ=0.00 | success | 10.18s
[238/960] IU_175 | sufficient | λ=0.25 | success | 7.14s
[239/960] IU_175 | syntactic_incomplete | λ=0.00 | success | 9.32s
[240/960] IU_175 | syntactic_incomplete | λ=0.25 | success | 7.92s
[241/960] IU_185 | evidentiary_incomplete | λ=0.00 | success | 7.35s
[242/960] IU_185 | evidentiary_incomplete | λ=0.25 | success | 6.84s
[243/960] IU_185 | insufficient | λ=0.00 | success | 4.11s
[244/960] IU_185 | insufficient | λ=0.25 | success | 4.01s
[245/960] IU_185 | irrelevant | λ=0.00 | success | 8.33s
[246/960] IU_185 | irrelevant | λ=0.25 | success | 8.04s
[247/960] IU_185 | sufficient | λ=0.00 | success | 7.29s
[248/960] IU_185 | sufficient | λ=0.25 | success | 8.41s
[249/960] IU_185 | syntactic_incomplete | λ=0.00 | success | 7.29s
[250/960] IU_185 | syntactic_incomplete | λ=0.25 | success | 6.59s
[251/960] IU_190 | evidentiary_incomplete | λ=0.00 | success | 6.67s
[252/960] IU_190 | evidentiary_incomplete | λ=0.25 | success | 6.86s
[253/960] IU_190 | insufficient | λ=0.00 | success | 4.03s
[254/960] IU_190 | insufficient | λ=0.25 | success | 4.10s
[255/960] IU_190 | irrelevant | λ=0.00 | success | 8.65s
[256/960] IU_190 | irrelevant | λ=0.25 | success | 6.22s
[257/960] IU_190 | sufficient | λ=0.00 | success | 8.98s
[258/960] IU_190 | sufficient | λ=0.25 | success | 6.88s
[259/960] IU_190 | syntactic_incomplete | λ=0.00 | success | 7.12s
[260/960] IU_190 | syntactic_incomplete | λ=0.25 | success | 6.86s
[261/960] IU_247 | evidentiary_incomplete | λ=0.00 | success | 6.76s
[262/960] IU_247 | evidentiary_incomplete | λ=0.25 | success | 6.63s
[263/960] IU_247 | insufficient | λ=0.00 | success | 7.69s
[264/960] IU_247 | insufficient | λ=0.25 | success | 8.01s
[265/960] IU_247 | irrelevant | λ=0.00 | success | 8.66s
[266/960] IU_247 | irrelevant | λ=0.25 | success | 8.88s
[267/960] IU_247 | sufficient | λ=0.00 | success | 6.97s
[268/960] IU_247 | sufficient | λ=0.25 | success | 8.87s
[269/960] IU_247 | syntactic_incomplete | λ=0.00 | success | 9.35s
[270/960] IU_247 | syntactic_incomplete | λ=0.25 | success | 9.65s
[271/960] IU_254 | evidentiary_incomplete | λ=0.00 | success | 6.85s
[272/960] IU_254 | evidentiary_incomplete | λ=0.25 | success | 7.00s
[273/960] IU_254 | insufficient | λ=0.00 | success | 4.02s
[274/960] IU_254 | insufficient | λ=0.25 | success | 4.15s
[275/960] IU_254 | irrelevant | λ=0.00 | success | 7.84s
[276/960] IU_254 | irrelevant | λ=0.25 | success | 8.74s
[277/960] IU_254 | sufficient | λ=0.00 | success | 9.50s
[278/960] IU_254 | sufficient | λ=0.25 | success | 9.54s
[279/960] IU_254 | syntactic_incomplete | λ=0.00 | success | 9.15s
[280/960] IU_254 | syntactic_incomplete | λ=0.25 | success | 9.27s
[281/960] IU_270 | evidentiary_incomplete | λ=0.00 | success | 6.87s
[282/960] IU_270 | evidentiary_incomplete | λ=0.25 | success | 6.54s
[283/960] IU_270 | insufficient | λ=0.00 | success | 4.18s
[284/960] IU_270 | insufficient | λ=0.25 | success | 3.96s
[285/960] IU_270 | irrelevant | λ=0.00 | success | 11.37s
[286/960] IU_270 | irrelevant | λ=0.25 | success | 7.85s
[287/960] IU_270 | sufficient | λ=0.00 | success | 6.41s
[288/960] IU_270 | sufficient | λ=0.25 | success | 13.42s
[289/960] IU_270 | syntactic_incomplete | λ=0.00 | success | 6.65s
[290/960] IU_270 | syntactic_incomplete | λ=0.25 | success | 13.36s
[291/960] IU_275 | evidentiary_incomplete | λ=0.00 | success | 8.85s
[292/960] IU_275 | evidentiary_incomplete | λ=0.25 | success | 6.52s
[293/960] IU_275 | insufficient | λ=0.00 | success | 4.02s
[294/960] IU_275 | insufficient | λ=0.25 | success | 4.02s
[295/960] IU_275 | irrelevant | λ=0.00 | success | 7.80s
[296/960] IU_275 | irrelevant | λ=0.25 | success | 7.81s
[297/960] IU_275 | sufficient | λ=0.00 | success | 6.81s
[298/960] IU_275 | sufficient | λ=0.25 | success | 13.79s
[299/960] IU_275 | syntactic_incomplete | λ=0.00 | success | 8.09s
[300/960] IU_275 | syntactic_incomplete | λ=0.25 | success | 7.77s
[301/960] IU_287 | evidentiary_incomplete | λ=0.00 | success | 10.23s
[302/960] IU_287 | evidentiary_incomplete | λ=0.25 | success | 6.89s
[303/960] IU_287 | insufficient | λ=0.00 | success | 4.98s
[304/960] IU_287 | insufficient | λ=0.25 | success | 4.97s
[305/960] IU_287 | irrelevant | λ=0.00 | success | 11.58s
[306/960] IU_287 | irrelevant | λ=0.25 | success | 11.90s
[307/960] IU_287 | sufficient | λ=0.00 | success | 9.27s
[308/960] IU_287 | sufficient | λ=0.25 | success | 8.75s
[309/960] IU_287 | syntactic_incomplete | λ=0.00 | success | 6.81s
[310/960] IU_287 | syntactic_incomplete | λ=0.25 | success | 6.88s
[311/960] IU_297 | evidentiary_incomplete | λ=0.00 | success | 10.07s
[312/960] IU_297 | evidentiary_incomplete | λ=0.25 | success | 9.99s
[313/960] IU_297 | insufficient | λ=0.00 | success | 4.80s
[314/960] IU_297 | insufficient | λ=0.25 | success | 4.75s
[315/960] IU_297 | irrelevant | λ=0.00 | success | 9.49s
[316/960] IU_297 | irrelevant | λ=0.25 | success | 8.14s
[317/960] IU_297 | sufficient | λ=0.00 | success | 9.59s
[318/960] IU_297 | sufficient | λ=0.25 | success | 9.44s
[319/960] IU_297 | syntactic_incomplete | λ=0.00 | success | 9.77s
[320/960] IU_297 | syntactic_incomplete | λ=0.25 | success | 7.00s
[321/960] IU_303 | evidentiary_incomplete | λ=0.00 | success | 8.34s
[322/960] IU_303 | evidentiary_incomplete | λ=0.25 | success | 5.98s
[323/960] IU_303 | insufficient | λ=0.00 | success | 6.68s
[324/960] IU_303 | insufficient | λ=0.25 | success | 6.88s
[325/960] IU_303 | irrelevant | λ=0.00 | success | 8.11s
[326/960] IU_303 | irrelevant | λ=0.25 | success | 9.88s
[327/960] IU_303 | sufficient | λ=0.00 | success | 9.72s
[328/960] IU_303 | sufficient | λ=0.25 | success | 8.27s
[329/960] IU_303 | syntactic_incomplete | λ=0.00 | success | 9.72s
[330/960] IU_303 | syntactic_incomplete | λ=0.25 | success | 8.02s
[331/960] IU_304 | evidentiary_incomplete | λ=0.00 | success | 6.93s
[332/960] IU_304 | evidentiary_incomplete | λ=0.25 | success | 6.67s
[333/960] IU_304 | insufficient | λ=0.00 | success | 8.36s
[334/960] IU_304 | insufficient | λ=0.25 | success | 8.56s
[335/960] IU_304 | irrelevant | λ=0.00 | success | 9.47s
[336/960] IU_304 | irrelevant | λ=0.25 | success | 9.04s
[337/960] IU_304 | sufficient | λ=0.00 | success | 9.47s
[338/960] IU_304 | sufficient | λ=0.25 | success | 7.92s
[339/960] IU_304 | syntactic_incomplete | λ=0.00 | success | 6.71s
[340/960] IU_304 | syntactic_incomplete | λ=0.25 | success | 9.19s
[341/960] IU_313 | evidentiary_incomplete | λ=0.00 | success | 8.97s
[342/960] IU_313 | evidentiary_incomplete | λ=0.25 | success | 8.89s
[343/960] IU_313 | insufficient | λ=0.00 | success | 7.92s
[344/960] IU_313 | insufficient | λ=0.25 | success | 8.13s
[345/960] IU_313 | irrelevant | λ=0.00 | success | 10.00s
[346/960] IU_313 | irrelevant | λ=0.25 | success | 10.47s
[347/960] IU_313 | sufficient | λ=0.00 | success | 11.16s
[348/960] IU_313 | sufficient | λ=0.25 | success | 9.82s
[349/960] IU_313 | syntactic_incomplete | λ=0.00 | success | 8.76s
[350/960] IU_313 | syntactic_incomplete | λ=0.25 | success | 9.74s
[351/960] IU_329 | evidentiary_incomplete | λ=0.00 | success | 7.95s
[352/960] IU_329 | evidentiary_incomplete | λ=0.25 | success | 7.97s
[353/960] IU_329 | insufficient | λ=0.00 | success | 7.49s
[354/960] IU_329 | insufficient | λ=0.25 | success | 7.43s
[355/960] IU_329 | irrelevant | λ=0.00 | success | 6.65s
[356/960] IU_329 | irrelevant | λ=0.25 | success | 7.43s
[357/960] IU_329 | sufficient | λ=0.00 | success | 6.50s
[358/960] IU_329 | sufficient | λ=0.25 | success | 6.59s
[359/960] IU_329 | syntactic_incomplete | λ=0.00 | success | 6.94s
[360/960] IU_329 | syntactic_incomplete | λ=0.25 | success | 7.11s
[361/960] IU_340 | evidentiary_incomplete | λ=0.00 | success | 8.49s
[362/960] IU_340 | evidentiary_incomplete | λ=0.25 | success | 8.51s
[363/960] IU_340 | insufficient | λ=0.00 | success | 5.00s
[364/960] IU_340 | insufficient | λ=0.25 | success | 4.99s
[365/960] IU_340 | irrelevant | λ=0.00 | success | 9.31s
[366/960] IU_340 | irrelevant | λ=0.25 | success | 8.63s
[367/960] IU_340 | sufficient | λ=0.00 | success | 8.92s
[368/960] IU_340 | sufficient | λ=0.25 | success | 9.05s
[369/960] IU_340 | syntactic_incomplete | λ=0.00 | success | 8.79s
[370/960] IU_340 | syntactic_incomplete | λ=0.25 | success | 8.05s
[371/960] IU_341 | evidentiary_incomplete | λ=0.00 | success | 3.68s
[372/960] IU_341 | evidentiary_incomplete | λ=0.25 | success | 3.68s
[373/960] IU_341 | insufficient | λ=0.00 | success | 3.67s
[374/960] IU_341 | insufficient | λ=0.25 | success | 3.68s
[375/960] IU_341 | irrelevant | λ=0.00 | success | 7.32s
[376/960] IU_341 | irrelevant | λ=0.25 | success | 7.26s
[377/960] IU_341 | sufficient | λ=0.00 | success | 6.85s
[378/960] IU_341 | sufficient | λ=0.25 | success | 5.15s
[379/960] IU_341 | syntactic_incomplete | λ=0.00 | success | 3.79s
[380/960] IU_341 | syntactic_incomplete | λ=0.25 | success | 3.67s
[381/960] IU_372 | evidentiary_incomplete | λ=0.00 | success | 12.32s
[382/960] IU_372 | evidentiary_incomplete | λ=0.25 | success | 9.04s
[383/960] IU_372 | insufficient | λ=0.00 | success | 7.62s
[384/960] IU_372 | insufficient | λ=0.25 | success | 7.64s
[385/960] IU_372 | irrelevant | λ=0.00 | success | 8.00s
[386/960] IU_372 | irrelevant | λ=0.25 | success | 8.80s
[387/960] IU_372 | sufficient | λ=0.00 | success | 10.01s
[388/960] IU_372 | sufficient | λ=0.25 | success | 10.07s
[389/960] IU_372 | syntactic_incomplete | λ=0.00 | success | 10.14s
[390/960] IU_372 | syntactic_incomplete | λ=0.25 | success | 11.20s
[391/960] IU_382 | evidentiary_incomplete | λ=0.00 | success | 11.39s
[392/960] IU_382 | evidentiary_incomplete | λ=0.25 | success | 11.52s
[393/960] IU_382 | insufficient | λ=0.00 | success | 4.11s
[394/960] IU_382 | insufficient | λ=0.25 | success | 4.12s
[395/960] IU_382 | irrelevant | λ=0.00 | success | 17.08s
[396/960] IU_382 | irrelevant | λ=0.25 | success | 9.52s
[397/960] IU_382 | sufficient | λ=0.00 | success | 11.60s
[398/960] IU_382 | sufficient | λ=0.25 | success | 11.49s
[399/960] IU_382 | syntactic_incomplete | λ=0.00 | success | 17.17s
[400/960] IU_382 | syntactic_incomplete | λ=0.25 | success | 13.83s
[401/960] IU_388 | evidentiary_incomplete | λ=0.00 | success | 7.17s
[402/960] IU_388 | evidentiary_incomplete | λ=0.25 | success | 6.88s
[403/960] IU_388 | insufficient | λ=0.00 | success | 5.98s
[404/960] IU_388 | insufficient | λ=0.25 | success | 5.67s
[405/960] IU_388 | irrelevant | λ=0.00 | success | 9.53s
[406/960] IU_388 | irrelevant | λ=0.25 | success | 6.98s
[407/960] IU_388 | sufficient | λ=0.00 | success | 8.20s
[408/960] IU_388 | sufficient | λ=0.25 | success | 8.38s
[409/960] IU_388 | syntactic_incomplete | λ=0.00 | success | 8.32s
[410/960] IU_388 | syntactic_incomplete | λ=0.25 | success | 8.18s
[411/960] IU_400 | evidentiary_incomplete | λ=0.00 | success | 9.52s
[412/960] IU_400 | evidentiary_incomplete | λ=0.25 | success | 8.86s
[413/960] IU_400 | insufficient | λ=0.00 | success | 3.98s
[414/960] IU_400 | insufficient | λ=0.25 | success | 3.99s
[415/960] IU_400 | irrelevant | λ=0.00 | success | 16.92s
[416/960] IU_400 | irrelevant | λ=0.25 | success | 8.04s
[417/960] IU_400 | sufficient | λ=0.00 | success | 10.31s
[418/960] IU_400 | sufficient | λ=0.25 | success | 8.36s
[419/960] IU_400 | syntactic_incomplete | λ=0.00 | success | 9.05s
[420/960] IU_400 | syntactic_incomplete | λ=0.25 | success | 9.22s
[421/960] IU_417 | evidentiary_incomplete | λ=0.00 | success | 6.34s
[422/960] IU_417 | evidentiary_incomplete | λ=0.25 | success | 6.45s
[423/960] IU_417 | insufficient | λ=0.00 | success | 3.81s
[424/960] IU_417 | insufficient | λ=0.25 | success | 3.68s
[425/960] IU_417 | irrelevant | λ=0.00 | success | 8.93s
[426/960] IU_417 | irrelevant | λ=0.25 | success | 8.71s
[427/960] IU_417 | sufficient | λ=0.00 | success | 7.67s
[428/960] IU_417 | sufficient | λ=0.25 | success | 7.06s
[429/960] IU_417 | syntactic_incomplete | λ=0.00 | success | 8.09s
[430/960] IU_417 | syntactic_incomplete | λ=0.25 | success | 7.88s
[431/960] IU_437 | evidentiary_incomplete | λ=0.00 | success | 11.13s
[432/960] IU_437 | evidentiary_incomplete | λ=0.25 | success | 9.91s
[433/960] IU_437 | insufficient | λ=0.00 | success | 6.82s
[434/960] IU_437 | insufficient | λ=0.25 | success | 6.77s
[435/960] IU_437 | irrelevant | λ=0.00 | success | 11.02s
[436/960] IU_437 | irrelevant | λ=0.25 | success | 10.48s
[437/960] IU_437 | sufficient | λ=0.00 | success | 10.93s
[438/960] IU_437 | sufficient | λ=0.25 | success | 8.70s
[439/960] IU_437 | syntactic_incomplete | λ=0.00 | success | 9.53s
[440/960] IU_437 | syntactic_incomplete | λ=0.25 | success | 8.29s
[441/960] IU_451 | evidentiary_incomplete | λ=0.00 | success | 8.66s
[442/960] IU_451 | evidentiary_incomplete | λ=0.25 | success | 8.70s
[443/960] IU_451 | insufficient | λ=0.00 | success | 5.55s
[444/960] IU_451 | insufficient | λ=0.25 | success | 5.17s
[445/960] IU_451 | irrelevant | λ=0.00 | success | 8.39s
[446/960] IU_451 | irrelevant | λ=0.25 | success | 7.54s
[447/960] IU_451 | sufficient | λ=0.00 | success | 13.41s
[448/960] IU_451 | sufficient | λ=0.25 | success | 9.43s
[449/960] IU_451 | syntactic_incomplete | λ=0.00 | success | 10.64s
[450/960] IU_451 | syntactic_incomplete | λ=0.25 | success | 4.12s
[451/960] IU_460 | evidentiary_incomplete | λ=0.00 | success | 7.35s
[452/960] IU_460 | evidentiary_incomplete | λ=0.25 | success | 5.78s
[453/960] IU_460 | insufficient | λ=0.00 | success | 4.06s
[454/960] IU_460 | insufficient | λ=0.25 | success | 3.96s
[455/960] IU_460 | irrelevant | λ=0.00 | success | 6.52s
[456/960] IU_460 | irrelevant | λ=0.25 | success | 6.20s
[457/960] IU_460 | sufficient | λ=0.00 | success | 8.78s
[458/960] IU_460 | sufficient | λ=0.25 | success | 7.80s
[459/960] IU_460 | syntactic_incomplete | λ=0.00 | success | 8.98s
[460/960] IU_460 | syntactic_incomplete | λ=0.25 | success | 8.00s
[461/960] IU_461 | evidentiary_incomplete | λ=0.00 | success | 9.73s
[462/960] IU_461 | evidentiary_incomplete | λ=0.25 | success | 7.61s
[463/960] IU_461 | insufficient | λ=0.00 | success | 3.98s
[464/960] IU_461 | insufficient | λ=0.25 | success | 3.99s
[465/960] IU_461 | irrelevant | λ=0.00 | success | 7.33s
[466/960] IU_461 | irrelevant | λ=0.25 | success | 6.22s
[467/960] IU_461 | sufficient | λ=0.00 | success | 9.02s
[468/960] IU_461 | sufficient | λ=0.25 | success | 9.00s
[469/960] IU_461 | syntactic_incomplete | λ=0.00 | success | 8.64s
[470/960] IU_461 | syntactic_incomplete | λ=0.25 | success | 8.68s
[471/960] IU_463 | evidentiary_incomplete | λ=0.00 | success | 6.61s
[472/960] IU_463 | evidentiary_incomplete | λ=0.25 | success | 6.36s
[473/960] IU_463 | insufficient | λ=0.00 | success | 7.18s
[474/960] IU_463 | insufficient | λ=0.25 | success | 6.86s
[475/960] IU_463 | irrelevant | λ=0.00 | success | 11.27s
[476/960] IU_463 | irrelevant | λ=0.25 | success | 9.89s
[477/960] IU_463 | sufficient | λ=0.00 | success | 6.36s
[478/960] IU_463 | sufficient | λ=0.25 | success | 6.98s
[479/960] IU_463 | syntactic_incomplete | λ=0.00 | success | 8.56s
[480/960] IU_463 | syntactic_incomplete | λ=0.25 | success | 6.20s
[481/960] IU_475 | evidentiary_incomplete | λ=0.00 | success | 11.86s
[482/960] IU_475 | evidentiary_incomplete | λ=0.25 | success | 10.34s

In [ ]:
# ============================================================
# Phase26D Evaluation Generation Audit
# ============================================================

import pandas as pd

eval_gen = pd.read_csv(
    RESULT_CSV
)

print("Rows:", len(eval_gen))
print("Expected rows: 960")

print("\nStudies:", eval_gen["uid"].nunique())
print("Expected studies: 80")

print("\nConditions:")
print(
    eval_gen["condition"]
    .value_counts()
    .sort_index()
)

print("\nLambda:")
print(
    eval_gen["lambda"]
    .value_counts()
    .sort_index()
)

print("\nStatus:")
print(
    eval_gen["status"]
    .value_counts()
)

# ------------------------------------------------------------
# Expected condition × lambda = 80 each
# ------------------------------------------------------------

condition_lambda_counts = (
    eval_gen
    .groupby(["condition", "lambda"])
    .size()
    .unstack(fill_value=0)
)

print("\nCondition × Lambda:")
print(condition_lambda_counts)

# ------------------------------------------------------------
# Duplicate trajectory audit
# ------------------------------------------------------------

duplicate_mask = (
    eval_gen
    .duplicated(
        subset=[
            "sample_id",
            "condition",
            "lambda"
        ],
        keep=False
    )
)

print(
    "\nDuplicate trajectory rows:",
    int(duplicate_mask.sum())
)

# ------------------------------------------------------------
# Missing trajectory audit
# ------------------------------------------------------------

expected_keys = {
    (
        str(row["sample_id"]),
        str(row["condition"]),
        float(lam)
    )
    for _, row in eval_benchmark.iterrows()
    for lam in [0.0, 0.25]
}

actual_keys = {
    (
        str(row["sample_id"]),
        str(row["condition"]),
        float(row["lambda"])
    )
    for _, row in eval_gen.iterrows()
}

missing_keys = expected_keys - actual_keys
extra_keys = actual_keys - expected_keys

print(
    "Missing trajectories:",
    len(missing_keys)
)

print(
    "Unexpected trajectories:",
    len(extra_keys)
)

# ------------------------------------------------------------
# Empty/failed output audit
# ------------------------------------------------------------

empty_reports = (
    eval_gen["report"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
)

print(
    "\nEmpty reports:",
    int(empty_reports.sum())
)

print(
    "Failed trajectories:",
    int(
        (eval_gen["status"] != "success").sum()
    )
)

# ------------------------------------------------------------
# Final PASS/FAIL
# ------------------------------------------------------------

audit_pass = (
    len(eval_gen) == 960
    and eval_gen["uid"].nunique() == 80
    and eval_gen["condition"].value_counts().eq(160).all()
    and eval_gen["lambda"].value_counts().eq(480).all()
    and int(duplicate_mask.sum()) == 0
    and len(missing_keys) == 0
    and len(extra_keys) == 0
    and int(empty_reports.sum()) == 0
    and int((eval_gen["status"] != "success").sum()) == 0
)

print("\n================================")
print(
    "PHASE26D EVALUATION GENERATION AUDIT:",
    "PASS" if audit_pass else "FAIL"
)
print("================================")

assert audit_pass

Rows: 960
Expected rows: 960

Studies: 80
Expected studies: 80

Conditions:
condition
conflicting               160
evidentiary_incomplete    160
insufficient              160
irrelevant                160
sufficient                160
syntactic_incomplete      160
Name: count, dtype: int64

Lambda:
lambda
0.00    480
0.25    480
Name: count, dtype: int64

Status:
status
success    960
Name: count, dtype: int64

Condition × Lambda:
lambda                  0.00  0.25
condition
conflicting               80    80
evidentiary_incomplete    80    80
insufficient              80    80
irrelevant                80    80
sufficient                80    80
syntactic_incomplete      80    80

Duplicate trajectory rows: 0
Missing trajectories: 0
Unexpected trajectories: 0

Empty reports: 0
Failed trajectories: 0

================================
PHASE26D EVALUATION GENERATION AUDIT: PASS
================================

In [ ]:
from pathlib import Path

print("Claim-evaluation related files:\n")

for path in sorted(
    Path("src").rglob("*.py")
):
    name = path.name.lower()

    if any(
        term in name
        for term in [
            "claim",
            "evaluate",
            "radgraph",
            "chexpert",
        ]
    ):
        print(path)

print("\nEvaluation-related notebooks/scripts:\n")

for path in sorted(
    Path("notebooks").rglob("*")
):
    if path.is_file():
        print(path)

Claim-evaluation related files:

src/evaluation/claim_evaluator.py
src/evaluation/claim_extractor.py
src/evaluation/claim_patterns.py
src/evaluation/evaluate_abstention_metrics.py
src/evaluation/evaluate_analyzer.py
src/evaluation/evaluate_analyzer_phase12b.py
src/evaluation/evaluate_analyzer_phase12c.py
src/evaluation/evaluate_chexpert_f1.py
src/evaluation/evaluate_gated_generation.py
src/evaluation/evaluate_phase11_paired.py
src/evaluation/evaluate_phase13a_gate.py
src/evaluation/evaluate_phase13b_gated_reports.py
src/evaluation/evaluate_radgraph_f1.py
src/evaluation/evaluate_reference_factuality.py
src/evaluation/evaluate_reliability_gate.py
src/evaluation/evaluate_risk_coverage.py
src/evaluation/evaluate_unsupported_claims.py
src/evaluation/run_phase19_claim_evaluation.py

Evaluation-related notebooks/scripts:

In [ ]:
from pathlib import Path

path = Path("src/evaluation/run_phase19_claim_evaluation.py")

print(path.read_text())

"""Phase 19 paired claim evaluation for the Phase 17/18 576-record cohort.

Uses the established claim-pattern extractor and conservative polarity labels.
This is limited-ontology claim comparison; it does not run RadGraph-F1,
CheXpert-F1, or statistical comparison.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path
from typing import Any

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.evaluation.build_reference_candidates import extract_reference_candidates
from src.evaluation.claim_evaluator import load_ontology
from src.evaluation.claim_extractor import extract_generated_claim_candidates
from src.evaluation.claim_patterns import REFERENCE_PATTERNS
from src.evaluation.evaluate_reference_factuality import build_factuality_table

BENCHMARK_PATH = ROOT / "results/tables/phase16_perturbations.csv"
ELIGIBILITY_PATH = ROOT / "results/tables/phase17_vlm_inference_eligibility.csv"
BASELINE_PATH = ROOT / "results/baseline/phase17_full/baseline_results.csv"
GATED_PATH = ROOT / "results/gated/phase18_full/gated_results.csv"
ONTOLOGY_PATH = ROOT / "configs/claim_ontology.yaml"
DETAIL_PATH = ROOT / "results/tables/phase19_claim_evaluation.csv"
SUMMARY_PATH = ROOT / "results/tables/phase19_claim_summary.csv"

EXCLUDED_UIDS = {74, 597, 803, 885}
LABELS = (
    "supported",
    "omission",
    "extra_negation",
    "ungrounded_affirmation",
    "unsupported_affirmation",
    "contradiction",
    "unclear",
)
REQUIRED_CONDITIONS = {
    "sufficient",
    "syntactic_incomplete",
    "evidentiary_incomplete",
    "irrelevant",
    "conflicting",
    "insufficient",
}
UNSUPPORTED_LABELS = {
    "ungrounded_affirmation",
    "unsupported_affirmation",
    "contradiction",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def tree_hashes(directory: Path) -> dict[str, str]:
    return {
        path.relative_to(directory).as_posix(): sha256(path)
        for path in sorted(directory.rglob("*"))
        if path.is_file()
    }


def _uid(value: Any) -> int:
    return int(float(value))


def _key(frame: pd.DataFrame) -> set[tuple[str, int, str]]:
    return {
        (str(row.sample_id), _uid(row.uid), str(row.condition))
        for row in frame.itertuples(index=False)
    }


def _load_inputs() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    paths = (BENCHMARK_PATH, ELIGIBILITY_PATH, BASELINE_PATH, GATED_PATH, ONTOLOGY_PATH)
    for path in paths:
        if not path.is_file():
            raise FileNotFoundError(f"Required Phase 19 input is missing: {path}")

    benchmark = pd.read_csv(BENCHMARK_PATH)
    eligibility_all = pd.read_csv(ELIGIBILITY_PATH)
    eligibility = eligibility_all[
        eligibility_all["eligible_for_vlm"].astype(str).str.lower() == "true"
    ].copy()
    baseline = pd.read_csv(BASELINE_PATH)
    gated = pd.read_csv(GATED_PATH)

    if len(eligibility) != 576 or len(baseline) != 576 or len(gated) != 576:
        raise ValueError(
            f"Expected 576 eligible/baseline/gated rows; got "
            f"{len(eligibility)}/{len(baseline)}/{len(gated)}"
        )
    for name, frame in (("eligibility", eligibility), ("baseline", baseline), ("gated", gated)):
        if frame.duplicated(["sample_id", "uid", "condition"]).any():
            raise ValueError(f"{name} has duplicate record keys")

    eligible_keys = _key(eligibility)
    if _key(baseline) != eligible_keys or _key(gated) != eligible_keys:
        raise ValueError("Eligibility, baseline, and gated record keys do not match exactly")
    if set(eligibility["uid"].astype(int)) & EXCLUDED_UIDS:
        raise ValueError("Excluded image-unavailable UID appears in the eligible cohort")
    if eligibility["condition"].value_counts().to_dict() != {
        condition: 96 for condition in REQUIRED_CONDITIONS
    }:
        raise ValueError("Eligible cohort does not have 96 records per condition")

    benchmark = benchmark.copy()
    benchmark["uid"] = benchmark["uid"].astype(int)
    eligibility = eligibility.copy()
    eligibility["uid"] = eligibility["uid"].astype(int)
    baseline = baseline.copy()
    baseline["uid"] = baseline["uid"].astype(int)
    gated = gated.copy()
    gated["uid"] = gated["uid"].astype(int)

    eligible_benchmark = eligibility[["sample_id", "uid", "condition"]].merge(
        benchmark,
        on=["sample_id", "uid", "condition"],
        how="left",
        validate="one_to_one",
        suffixes=("_eligibility", "_benchmark"),
    )
    if eligible_benchmark["findings"].isna().any() or eligible_benchmark["impression"].isna().any():
        raise ValueError("Eligible record is missing benchmark reference text")

    # Ensure each study has one stable reference findings/impression source.
    reference_variants = eligible_benchmark.groupby("uid")[
        ["sample_id", "findings", "impression"]
    ].nunique(dropna=False)
    if (reference_variants > 1).any().any():
        raise ValueError("Reference findings/impression vary across conditions for a UID")

    for name, frame, report_column in (
        ("baseline", baseline, "generated_report"),
        ("gated", gated, "gated_report"),
    ):
        paired = eligibility[["sample_id", "uid", "condition", "image_path"]].merge(
            frame,
            on=["sample_id", "uid", "condition"],
            how="left",
            validate="one_to_one",
            suffixes=("_eligibility", f"_{name}"),
        )
        if paired[report_column].isna().any() or (paired[report_column].astype(str).str.len() == 0).any():
            raise ValueError(f"{name} has an empty report")
        if name == "baseline":
            benchmark_contexts = eligible_benchmark.set_index(
                ["sample_id", "uid", "condition"]
            )["perturbed_context"].to_dict()
            for row in frame.itertuples(index=False):
                key = (str(row.sample_id), int(row.uid), str(row.condition))
                if str(row.perturbed_context) != str(benchmark_contexts[key]):
                    raise ValueError(f"Baseline context does not match benchmark for {key}")
        else:
            baseline_by_key = baseline.set_index(["sample_id", "uid", "condition"])
            for row in frame.itertuples(index=False):
                key = (str(row.sample_id), int(row.uid), str(row.condition))
                base_context = str(baseline_by_key.loc[key, "perturbed_context"])
                if str(row.perturbed_context) != base_context:
                    raise ValueError(f"Gated context does not match baseline for {key}")
                if str(row.image_path) != str(baseline_by_key.loc[key, "image_path"]):
                    raise ValueError(f"Gated image path does not match baseline for {key}")

    # claim_ontology.yaml is the approved conflict-target alias map. Its targets
    # resolve into the canonical general candidate vocabulary used below.
    ontology = load_ontology()
    unknown_targets = {
        str(mapping["extractor_finding"]).strip().lower()
        for mapping in ontology.values()
        if str(mapping["extractor_finding"]).strip().lower() not in REFERENCE_PATTERNS
    }
    if unknown_targets:
        raise ValueError(f"Configured ontology targets are outside claim vocabulary: {sorted(unknown_targets)}")

    return eligibility, eligible_benchmark, baseline, gated, benchmark


def _extract_reference_claims(eligible_benchmark: pd.DataFrame) -> pd.DataFrame:
    studies = (
        eligible_benchmark[["sample_id", "findings", "impression"]]
        .drop_duplicates(subset=["sample_id"])
        .reset_index(drop=True)
    )
    return extract_reference_candidates(studies)


def _factuality_for_reports(
    report_frame: pd.DataFrame,
    report_column: str,
    reference_claims: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    generation = report_frame[["sample_id", "condition", report_column]].rename(
        columns={report_column: "generated_report"}
    )
    claims = extract_generated_claim_candidates(generation)
    factuality = build_factuality_table(generation, reference_claims, claims)
    return claims, factuality


def build_phase19_outputs() -> tuple[pd.DataFrame, pd.DataFrame]:
    eligibility, eligible_benchmark, baseline, gated, _ = _load_inputs()
    reference_claims = _extract_reference_claims(eligible_benchmark)
    baseline_claims, baseline_fact = _factuality_for_reports(
        baseline, "generated_report", reference_claims
    )
    gated_claims, gated_fact = _factuality_for_reports(
        gated, "gated_report", reference_claims
    )

    keys = ["sample_id", "condition", "finding"]
    baseline_fact = baseline_fact.rename(
        columns={
            "generated_polarity": "baseline_generated_polarity",
            "label": "baseline_label",
            "reference_polarity": "baseline_reference_polarity",
        }
    )
    gated_fact = gated_fact.rename(
        columns={
            "generated_polarity": "gated_generated_polarity",
            "label": "gated_label",
            "reference_polarity": "gated_reference_polarity",
        }
    )
    detail = baseline_fact.merge(
        gated_fact,
        on=keys,
        how="outer",
        validate="one_to_one",
    )
    if not detail["baseline_reference_polarity"].fillna("").astype(str).eq(
        detail["gated_reference_polarity"].fillna("").astype(str)
    ).all():
        raise ValueError("Baseline and gated factuality tables used different reference polarities")
    detail["reference_polarity"] = detail["baseline_reference_polarity"].fillna(
        detail["gated_reference_polarity"]
    ).fillna("")
    detail["baseline_generated_polarity"] = detail["baseline_generated_polarity"].fillna(
        "NOT_MENTIONED"
    )
    detail["gated_generated_polarity"] = detail["gated_generated_polarity"].fillna(
        "NOT_MENTIONED"
    )
    # A generated-only finding on one side has no counterpart claim to label
    # on the other side. Keep that paired label blank instead of manufacturing
    # an omission (omission is reserved for absent reference-supported claims).
    detail["baseline_label"] = detail["baseline_label"].fillna("")
    detail["gated_label"] = detail["gated_label"].fillna("")
    metadata = gated[
        ["sample_id", "uid", "condition", "evidence_state", "gate_action"]
    ].rename(
        columns={
            "condition": "benchmark_condition",
            "evidence_state": "analyzer_evidence_state",
        }
    )
    detail = detail.merge(
        metadata,
        left_on=["sample_id", "condition"],
        right_on=["sample_id", "benchmark_condition"],
        how="left",
        validate="many_to_one",
    ).drop(columns=["condition"])
    detail = detail[
        [
            "sample_id",
            "uid",
            "benchmark_condition",
            "analyzer_evidence_state",
            "gate_action",
            "finding",
            "reference_polarity",
            "baseline_generated_polarity",
            "baseline_label",
            "gated_generated_polarity",
            "gated_label",
        ]
    ].sort_values(["sample_id", "benchmark_condition", "finding"]).reset_index(drop=True)
    if detail.duplicated(
        ["sample_id", "uid", "benchmark_condition", "finding"]
    ).any():
        raise RuntimeError("Duplicate claim-level evaluation key found")

    # Record-level key coverage is checked separately from claim-level row count.
    expected_keys = _key(eligibility)
    for frame, label in ((baseline, "baseline"), (gated, "gated")):
        if _key(frame) != expected_keys:
            raise RuntimeError(f"{label} record evaluations do not match eligible keys")
    represented = set(
        zip(detail["sample_id"].astype(str), detail["benchmark_condition"].astype(str))
    )
    expected_pairs = set(zip(eligibility["sample_id"].astype(str), eligibility["condition"].astype(str)))
    if represented != expected_pairs:
        raise RuntimeError("Claim evaluation does not represent every eligible record")

    summary = _build_summary(
        eligibility,
        reference_claims,
        detail,
        baseline_claims,
        gated_claims,
    )
    return detail, summary


def _build_summary(
    eligibility: pd.DataFrame,
    reference_claims: pd.DataFrame,
    detail: pd.DataFrame,
    baseline_claims: pd.DataFrame,
    gated_claims: pd.DataFrame,
) -> pd.DataFrame:
    scopes: list[tuple[str, str, set[tuple[str, str]]]] = []
    all_pairs = set(zip(eligibility["sample_id"].astype(str), eligibility["condition"].astype(str)))
    scopes.append(("overall", "all", all_pairs))
    for condition in sorted(REQUIRED_CONDITIONS):
        pairs = set(
            zip(
                eligibility.loc[eligibility["condition"] == condition, "sample_id"].astype(str),
                eligibility.loc[eligibility["condition"] == condition, "condition"].astype(str),
            )
        )
        scopes.append(("benchmark_condition", condition, pairs))
    for state in sorted(eligibility.merge(
        detail[["sample_id", "benchmark_condition", "analyzer_evidence_state"]].drop_duplicates(),
        left_on=["sample_id", "condition"],
        right_on=["sample_id", "benchmark_condition"],
        how="left",
    )["analyzer_evidence_state"].dropna().unique()):
        pairs = set(
            zip(
                detail.loc[detail["analyzer_evidence_state"] == state, "sample_id"].astype(str),
                detail.loc[detail["analyzer_evidence_state"] == state, "benchmark_condition"].astype(str),
            )
        )
        scopes.append(("analyzer_evidence_state", str(state), pairs))

    rows: list[dict[str, Any]] = []
    meta_pairs = eligibility[["sample_id", "condition"]].astype(str).drop_duplicates()
    for scope_level, scope_value, scope_pairs in scopes:
        scoped_keys = {(sample, condition) for sample, condition in scope_pairs}
        scoped_detail = detail[
            detail.apply(
                lambda row: (str(row["sample_id"]), str(row["benchmark_condition"])) in scoped_keys,
                axis=1,
            )
        ]
        scoped_meta = meta_pairs[
            meta_pairs.apply(lambda row: (row["sample_id"], row["condition"]) in scoped_keys, axis=1)
        ]
        sample_ids = set(scoped_meta["sample_id"].astype(str))
        reference_count = int(reference_claims[reference_claims["sample_id"].astype(str).isin(sample_ids)].shape[0])
        reference_comparisons = int(
            scoped_detail[scoped_detail["reference_polarity"].astype(str) != ""].shape[0]
        )

        for report_type, claims, label_column in (
            ("baseline", baseline_claims, "baseline_label"),
            ("gated", gated_claims, "gated_label"),
        ):
            scoped_claims = claims[
                claims.apply(
                    lambda row: (str(row["sample_id"]), str(row["condition"])) in scoped_keys,
                    axis=1,
                )
            ]
            labels = scoped_detail[label_column].value_counts().to_dict()
            generated_total = len(scoped_claims)
            evaluated_generated = sum(
                int(labels.get(label, 0))
                for label in LABELS
                if label != "omission"
            )
            unsupported_count = sum(int(labels.get(label, 0)) for label in UNSUPPORTED_LABELS)
            row: dict[str, Any] = {
                "summary_level": scope_level,
                "scope_value": scope_value,
                "report_type": report_type,
                "record_count": len(scoped_meta),
                "total_reference_candidates": reference_count,
                "reference_candidate_comparisons": reference_comparisons,
                "total_generated_candidates": generated_total,
                "unsupported_claim_rate_denominator": evaluated_generated,
                "comparison_candidate_count": len(scoped_detail),
            }
            for label in LABELS:
                row[label] = int(labels.get(label, 0))
            row["unsupported_claim_count"] = unsupported_count
            row["unsupported_claim_rate"] = (
                unsupported_count / evaluated_generated if evaluated_generated else 0.0
            )
            rows.append(row)
    return pd.DataFrame(rows)


def run_phase19() -> tuple[pd.DataFrame, pd.DataFrame]:
    inputs = (BENCHMARK_PATH, ELIGIBILITY_PATH, BASELINE_PATH, GATED_PATH, ONTOLOGY_PATH)
    hashes_before = {path: sha256(path) for path in inputs}
    baseline_tree_before = tree_hashes(BASELINE_PATH.parent)
    gated_tree_before = tree_hashes(GATED_PATH.parent)

    detail, summary = build_phase19_outputs()
    DETAIL_PATH.parent.mkdir(parents=True, exist_ok=True)
    detail.to_csv(DETAIL_PATH, index=False)
    summary.to_csv(SUMMARY_PATH, index=False)

    hashes_after = {path: sha256(path) for path in inputs}
    if hashes_before != hashes_after:
        raise RuntimeError("Benchmark, eligibility, baseline, gated, or ontology input changed")
    if baseline_tree_before != tree_hashes(BASELINE_PATH.parent):
        raise RuntimeError("Baseline outputs changed during Phase 19 evaluation")
    if gated_tree_before != tree_hashes(GATED_PATH.parent):
        raise RuntimeError("Gated outputs changed during Phase 19 evaluation")

    return detail, summary


def main() -> None:
    detail, summary = run_phase19()
    print(f"Eligible report records: 576 (baseline and gated)")
    print(f"Claim-level paired comparison rows: {len(detail)}")
    print(f"Reference candidates (unique studies): {summary.iloc[0]['total_reference_candidates']}")
    print(f"Baseline generated candidates: {int(summary.iloc[0]['total_generated_candidates'])}")
    print(f"Gated generated candidates: {int(summary.iloc[1]['total_generated_candidates'])}")
    print(f"Detail: {DETAIL_PATH}")
    print(f"Summary: {SUMMARY_PATH}")
    print("RadGraph-F1, CheXpert-F1, and statistical comparison: not run")


if __name__ == "__main__":
    main()

In [ ]:
path = Path("src/evaluation/claim_evaluator.py")

print(path.read_text())

﻿from pathlib import Path

import pandas as pd
import yaml


CLAIMS_PATH = Path("results/tables/extracted_claims.csv")
CONFLICT_PATH = Path("configs/conflict_cases.yaml")
ONTOLOGY_PATH = Path("configs/claim_ontology.yaml")
OUTPUT_PATH = Path("results/tables/conflict_claim_evaluation.csv")


VALID_POLARITIES = {
    "AFFIRMED",
    "NEGATED",
    "MENTIONED_UNCLEAR",
}


def load_approved_conflicts() -> list[dict]:
    with CONFLICT_PATH.open("r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    conflicts = data.get("conflicts")

    if not isinstance(conflicts, dict):
        raise ValueError("Expected 'conflicts' to be a mapping.")

    approved_cases = []

    for sample_id, case in conflicts.items():
        if not case.get("approved", False):
            continue

        target = str(case.get("target", "")).strip()

        if not target:
            raise ValueError(
                f"Approved case {sample_id} has an empty target."
            )

        approved_cases.append(
            {
                "sample_id": str(sample_id),
                "target": target,
                "type": str(case.get("type", "")),
                "conflicting_context": str(
                    case.get("conflicting_context", "")
                ),
            }
        )

    return approved_cases


def load_ontology() -> dict:
    with ONTOLOGY_PATH.open("r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    mappings = data.get("finding_mappings")

    if not isinstance(mappings, dict):
        raise ValueError(
            "Expected 'finding_mappings' to be a mapping."
        )

    return mappings


def normalize_finding(finding: str) -> str:
    return str(finding).strip().lower()


def resolve_extractor_finding(
    target: str,
    ontology: dict,
) -> str:
    target_normalized = normalize_finding(target)

    mapping = ontology.get(target_normalized)

    if mapping is None:
        raise ValueError(
            f"No ontology mapping found for target: {target}"
        )

    return normalize_finding(
        mapping["extractor_finding"]
    )


def find_matching_claims(
    sample_id: str,
    extractor_finding: str,
    claims_df: pd.DataFrame,
) -> pd.DataFrame:

    return claims_df[
        (claims_df["sample_id"].astype(str) == sample_id)
        &
        (
            claims_df["finding"].map(normalize_finding)
            == extractor_finding
        )
    ].copy()


def evaluate_case(
    case: dict,
    ontology: dict,
    claims_df: pd.DataFrame,
) -> dict:

    sample_id = case["sample_id"]
    target = case["target"]

    extractor_finding = resolve_extractor_finding(
        target,
        ontology,
    )

    matching_claims = find_matching_claims(
        sample_id,
        extractor_finding,
        claims_df,
    )

    if matching_claims.empty:
        return {
            "sample_id": sample_id,
            "target": target,
            "extractor_finding": extractor_finding,
            "type": case["type"],
            "conflicting_context": case[
                "conflicting_context"
            ],
            "generated_polarity": "NOT_MENTIONED",
            "evaluation": "NOT_MENTIONED",
            "source_sentence": "",
        }

    polarities = [
        str(p)
        for p in matching_claims["polarity"].tolist()
        if str(p) in VALID_POLARITIES
    ]

    if not polarities:
        return {
            "sample_id": sample_id,
            "target": target,
            "extractor_finding": extractor_finding,
            "type": case["type"],
            "conflicting_context": case[
                "conflicting_context"
            ],
            "generated_polarity": "MENTIONED_UNCLEAR",
            "evaluation": "MENTIONED_UNCLEAR",
            "source_sentence": "",
        }

    unique_polarities = sorted(set(polarities))

    if len(unique_polarities) > 1:
        generated_polarity = "MENTIONED_UNCLEAR"
        evaluation = "MENTIONED_UNCLEAR"
    else:
        generated_polarity = unique_polarities[0]
        evaluation = generated_polarity

    sentences = sorted(
        set(
            matching_claims["source_sentence"]
            .dropna()
            .astype(str)
            .tolist()
        )
    )

    return {
        "sample_id": sample_id,
        "target": target,
        "extractor_finding": extractor_finding,
        "type": case["type"],
        "conflicting_context": case[
            "conflicting_context"
        ],
        "generated_polarity": generated_polarity,
        "evaluation": evaluation,
        "source_sentence": " | ".join(sentences),
    }


def main() -> None:

    for path in [
        CLAIMS_PATH,
        CONFLICT_PATH,
        ONTOLOGY_PATH,
    ]:
        if not path.exists():
            raise FileNotFoundError(
                f"Required file not found: {path}"
            )

    claims_df = pd.read_csv(CLAIMS_PATH)

    required_columns = {
        "sample_id",
        "finding",
        "polarity",
        "source_sentence",
    }

    missing = required_columns - set(claims_df.columns)

    if missing:
        raise ValueError(
            f"Missing claim columns: {sorted(missing)}"
        )

    approved_cases = load_approved_conflicts()
    ontology = load_ontology()

    results = [
        evaluate_case(
            case,
            ontology,
            claims_df,
        )
        for case in approved_cases
    ]

    output_df = pd.DataFrame(results)

    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_df.to_csv(
        OUTPUT_PATH,
        index=False,
    )

    print("=" * 70)
    print("CONFLICT CLAIM EVALUATION")
    print("=" * 70)

    print(
        f"Approved conflict cases: {len(output_df)}"
    )

    print("\nEvaluation:")

    print(
        output_df["evaluation"]
        .value_counts()
        .sort_index()
        .to_string()
    )

    print("\nCase-level results:")

    print(
        output_df[
            [
                "sample_id",
                "target",
                "extractor_finding",
                "generated_polarity",
                "evaluation",
            ]
        ].to_string(index=False)
    )

    print(
        f"\nOutput: {OUTPUT_PATH}"
    )


if __name__ == "__main__":
    main()

In [ ]:
from pathlib import Path

for filename in [
    "src/evaluation/claim_extractor.py",
    "src/evaluation/evaluate_reference_factuality.py",
    "src/evaluation/build_reference_candidates.py",
]:
    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)

    path = Path(filename)

    print(path.read_text())

================================================================================
src/evaluation/claim_extractor.py
================================================================================
"""
Extract generated-report claim candidates.

This module extracts clinical-finding candidates from baseline
generated reports using the same REFERENCE_PATTERNS vocabulary
and polarity rules as the reference candidate extractor.

It writes:

    results/tables/generated_claim_candidates.csv

It does NOT overwrite:

    results/tables/extracted_claims.csv

Conflict-target evaluation remains in claim_evaluator.py.
That Phase 6 evaluator is condition-blind: it matches claims by
(sample_id, finding) and ignores condition. That behavior is
intentionally left unchanged. This extractor is condition-aware
and keys generated claims by (sample_id, condition, finding).
"""

from pathlib import Path
import sys

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.evaluation.claim_patterns import (
    extract_raw_claim_records,
    strip_generated_report_body,
)


GENERATION_PATH = Path(
    "results/tables/baseline_generation_results.csv"
)

OUTPUT_PATH = Path(
    "results/tables/generated_claim_candidates.csv"
)

# Historical Phase 6 artifact. Never overwrite this file.
PHASE6_CLAIMS_PATH = Path(
    "results/tables/extracted_claims.csv"
)


def extract_generated_claim_candidates(
    generation_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Extract case-level generated claims for each
    (sample_id, condition) generation record.
    """

    required_columns = {
        "sample_id",
        "condition",
        "generated_report",
    }

    missing = required_columns - set(
        generation_df.columns
    )

    if missing:
        raise ValueError(
            "Missing generation columns: "
            f"{sorted(missing)}"
        )

    records = []

    for _, row in generation_df.iterrows():

        sample_id = str(row["sample_id"])
        condition = str(row["condition"])

        body = strip_generated_report_body(
            row["generated_report"]
        )

        matches = extract_raw_claim_records(body)

        if not matches:
            continue

        match_df = pd.DataFrame(matches)

        match_df["sample_id"] = sample_id
        match_df["condition"] = condition

        # Collapse Findings / Impression repeats of the same
        # finding and polarity within one generated report.
        match_df = match_df.drop_duplicates(
            subset=[
                "sample_id",
                "condition",
                "finding",
                "polarity",
            ]
        )

        records.append(match_df)

    if not records:

        return pd.DataFrame(
            columns=[
                "sample_id",
                "condition",
                "finding",
                "polarity",
                "matched_pattern",
                "source_sentence",
            ]
        )

    combined = pd.concat(
        records,
        ignore_index=True,
    )

    collapsed_rows = []

    grouped = combined.groupby(
        ["sample_id", "condition", "finding"],
        sort=False,
    )

    for (
        sample_id,
        condition,
        finding,
    ), group in grouped:

        polarities = sorted(
            set(
                str(polarity)
                for polarity in group["polarity"].tolist()
            )
        )

        if (
            "AFFIRMED" in polarities
            and "NEGATED" in polarities
        ):
            polarity = "MENTIONED_UNCLEAR"
        elif len(polarities) == 1:
            polarity = polarities[0]
        else:
            polarity = "MENTIONED_UNCLEAR"

        sentences = sorted(
            set(
                group["source_sentence"]
                .dropna()
                .astype(str)
                .tolist()
            )
        )

        patterns = sorted(
            set(
                group["matched_pattern"]
                .dropna()
                .astype(str)
                .tolist()
            )
        )

        collapsed_rows.append(
            {
                "sample_id": sample_id,
                "condition": condition,
                "finding": finding,
                "polarity": polarity,
                "matched_pattern": " | ".join(patterns),
                "source_sentence": " | ".join(sentences),
            }
        )

    output = pd.DataFrame(collapsed_rows)

    if output.empty:

        return pd.DataFrame(
            columns=[
                "sample_id",
                "condition",
                "finding",
                "polarity",
                "matched_pattern",
                "source_sentence",
            ]
        )

    output = (
        output
        .sort_values(
            [
                "sample_id",
                "condition",
                "finding",
            ]
        )
        .reset_index(drop=True)
    )

    return output


def main() -> None:

    if not GENERATION_PATH.exists():
        raise FileNotFoundError(
            f"Generation results not found: {GENERATION_PATH}"
        )

    if PHASE6_CLAIMS_PATH.exists():
        phase6_mtime_before = (
            PHASE6_CLAIMS_PATH.stat().st_mtime
        )
    else:
        phase6_mtime_before = None

    generation_df = pd.read_csv(GENERATION_PATH)

    output = extract_generated_claim_candidates(
        generation_df
    )

    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    output.to_csv(
        OUTPUT_PATH,
        index=False,
    )

    if PHASE6_CLAIMS_PATH.exists():
        phase6_mtime_after = (
            PHASE6_CLAIMS_PATH.stat().st_mtime
        )

        if (
            phase6_mtime_before is not None
            and phase6_mtime_after != phase6_mtime_before
        ):
            raise RuntimeError(
                "extracted_claims.csv was modified. "
                "Phase 7 must not overwrite that artifact."
            )

    print("=" * 70)
    print("GENERATED CLAIM CANDIDATE EXTRACTION")
    print("=" * 70)

    print(
        f"Generation records: {len(generation_df)}"
    )

    print(
        f"Generated claim candidates: {len(output)}"
    )

    print(
        "\nPolarity counts:"
    )

    if output.empty:
        print("No generated claims found.")
    else:
        print(
            output["polarity"]
            .value_counts()
            .to_string()
        )

    print(
        f"\nOutput: {OUTPUT_PATH}"
    )

    print(
        "\nPhase 6 extracted_claims.csv was not overwritten."
    )

    print(
        "Conflict evaluation remains in claim_evaluator.py "
        "and is condition-blind."
    )


if __name__ == "__main__":
    main()


================================================================================
src/evaluation/evaluate_reference_factuality.py
================================================================================
"""
Reference-grounded factuality comparison.

Compares generated-report claim candidates against reference
claim candidates at the case-level key:

    (sample_id, condition, finding)

This evaluator is condition-aware.

The Phase 6 conflict evaluator in claim_evaluator.py remains
condition-blind (sample_id + finding only). That limitation is
not modified here.

Labels (do not rename):

    supported
    contradiction
    omission
    unsupported_affirmation
    ungrounded_affirmation
    extra_negation
    unclear

These counts are not hallucination rate, factuality F1,
reliability score, overall accuracy, RadGraph-F1, CheXpert-F1,
ECE, Brier, coverage, or abstention.
"""

from pathlib import Path
import sys

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.evaluation.metrics import (
    VALID_LABELS,
    assign_factuality_label,
)


GENERATION_PATH = Path(
    "results/tables/baseline_generation_results.csv"
)

REFERENCE_PATH = Path(
    "results/tables/reference_claim_candidates.csv"
)

GENERATED_CLAIMS_PATH = Path(
    "results/tables/generated_claim_candidates.csv"
)

DETAIL_OUTPUT_PATH = Path(
    "results/tables/reference_grounded_factuality.csv"
)

SUMMARY_OUTPUT_PATH = Path(
    "results/tables/reference_grounded_factuality_by_condition.csv"
)

EXPECTED_GENERATION_RECORDS = 81

REQUIRED_CONDITIONS = [
    "sufficient",
    "incomplete",
    "irrelevant",
    "conflicting",
    "insufficient",
]


def collapse_reference_polarities(
    reference_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Collapse reference rows to one polarity per
    (sample_id, finding).

    Conflicting polarities become MENTIONED_UNCLEAR.
    """

    required = {"sample_id", "finding", "polarity"}
    missing = required - set(reference_df.columns)

    if missing:
        raise ValueError(
            "Missing reference columns: "
            f"{sorted(missing)}"
        )

    rows = []

    grouped = reference_df.groupby(
        ["sample_id", "finding"],
        sort=False,
    )

    for (sample_id, finding), group in grouped:

        polarities = sorted(
            set(
                str(polarity)
                for polarity in group["polarity"].tolist()
            )
        )

        if (
            "AFFIRMED" in polarities
            and "NEGATED" in polarities
        ):
            polarity = "MENTIONED_UNCLEAR"
        elif len(polarities) == 1:
            polarity = polarities[0]
        else:
            polarity = "MENTIONED_UNCLEAR"

        rows.append(
            {
                "sample_id": str(sample_id),
                "finding": str(finding),
                "reference_polarity": polarity,
            }
        )

    return pd.DataFrame(rows)


def build_factuality_table(
    generation_df: pd.DataFrame,
    reference_df: pd.DataFrame,
    generated_claims_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build one comparison row per
    (sample_id, condition, finding) in the union of
    reference findings for the sample and generated findings
    for that condition.
    """

    required_generation = {
        "sample_id",
        "condition",
    }

    missing_generation = (
        required_generation - set(generation_df.columns)
    )

    if missing_generation:
        raise ValueError(
            "Missing generation columns: "
            f"{sorted(missing_generation)}"
        )

    reference = collapse_reference_polarities(
        reference_df
    )

    generated = generated_claims_df.copy()

    if generated.empty:
        generated = pd.DataFrame(
            columns=[
                "sample_id",
                "condition",
                "finding",
                "polarity",
            ]
        )
    else:
        required_generated = {
            "sample_id",
            "condition",
            "finding",
            "polarity",
        }

        missing_generated = (
            required_generated - set(generated.columns)
        )

        if missing_generated:
            raise ValueError(
                "Missing generated-claim columns: "
                f"{sorted(missing_generated)}"
            )

        generated["sample_id"] = (
            generated["sample_id"].astype(str)
        )
        generated["condition"] = (
            generated["condition"].astype(str)
        )
        generated["finding"] = (
            generated["finding"].astype(str)
        )

    generated_lookup = {
        (
            str(row["sample_id"]),
            str(row["condition"]),
            str(row["finding"]),
        ): str(row["polarity"])
        for _, row in generated.iterrows()
    }

    reference_by_sample: dict[str, dict[str, str]] = {}

    for _, row in reference.iterrows():
        sample_id = str(row["sample_id"])
        finding = str(row["finding"])
        reference_by_sample.setdefault(sample_id, {})
        reference_by_sample[sample_id][finding] = str(
            row["reference_polarity"]
        )

    rows = []

    generation_pairs = (
        generation_df[
            ["sample_id", "condition"]
        ]
        .astype(str)
        .drop_duplicates()
        .sort_values(["sample_id", "condition"])
    )

    for _, pair in generation_pairs.iterrows():

        sample_id = str(pair["sample_id"])
        condition = str(pair["condition"])

        reference_findings = reference_by_sample.get(
            sample_id,
            {},
        )

        generated_findings = {
            finding: polarity
            for (
                gen_sample,
                gen_condition,
                finding,
            ), polarity in generated_lookup.items()
            if gen_sample == sample_id
            and gen_condition == condition
        }

        findings = sorted(
            set(reference_findings) | set(generated_findings)
        )

        if not findings:
            rows.append(
                {
                    "sample_id": sample_id,
                    "condition": condition,
                    "finding": "",
                    "generated_polarity": "NOT_MENTIONED",
                    "reference_polarity": "",
                    "label": "unclear",
                }
            )
            continue

        for finding in findings:

            generated_polarity = generated_findings.get(
                finding,
                "NOT_MENTIONED",
            )

            reference_polarity = reference_findings.get(
                finding
            )

            label = assign_factuality_label(
                generated_polarity,
                reference_polarity,
            )

            if label not in VALID_LABELS:
                raise ValueError(
                    f"Unexpected label: {label}"
                )

            rows.append(
                {
                    "sample_id": sample_id,
                    "condition": condition,
                    "finding": finding,
                    "generated_polarity": generated_polarity,
                    "reference_polarity": (
                        ""
                        if reference_polarity is None
                        else reference_polarity
                    ),
                    "label": label,
                }
            )

    output = pd.DataFrame(rows)

    represented_pairs = set(
        zip(
            output["sample_id"].astype(str),
            output["condition"].astype(str),
        )
    )

    expected_pairs = set(
        zip(
            generation_df["sample_id"].astype(str),
            generation_df["condition"].astype(str),
        )
    )

    missing_pairs = expected_pairs - represented_pairs

    if missing_pairs:
        raise RuntimeError(
            "Generation records missing from factuality "
            f"table: {sorted(missing_pairs)}"
        )

    return (
        output
        .sort_values(
            ["sample_id", "condition", "finding"]
        )
        .reset_index(drop=True)
    )


def summarize_by_condition(
    detail_df: pd.DataFrame,
    generation_df: pd.DataFrame,
) -> pd.DataFrame:
    """Count labels by evidence-state condition."""

    generation_counts = (
        generation_df["condition"]
        .astype(str)
        .value_counts()
        .to_dict()
    )

    rows = []

    for condition in REQUIRED_CONDITIONS:

        subset = detail_df[
            detail_df["condition"].astype(str)
            == condition
        ]

        represented_pairs = subset[
            ["sample_id", "condition"]
        ].drop_duplicates()

        row = {
            "condition": condition,
            "generation_record_count": int(
                generation_counts.get(condition, 0)
            ),
            "represented_generation_records": len(
                represented_pairs
            ),
            "comparison_row_count": len(subset),
        }

        for label in sorted(VALID_LABELS):
            row[label] = int(
                (subset["label"] == label).sum()
            )

        rows.append(row)

    return pd.DataFrame(rows)


def main() -> None:

    for path in [
        GENERATION_PATH,
        REFERENCE_PATH,
        GENERATED_CLAIMS_PATH,
    ]:
        if not path.exists():
            raise FileNotFoundError(
                f"Required file not found: {path}"
            )

    generation_df = pd.read_csv(GENERATION_PATH)
    reference_df = pd.read_csv(REFERENCE_PATH)
    generated_claims_df = pd.read_csv(
        GENERATED_CLAIMS_PATH
    )

    # Updated in Phase 7B following conservative reference-vocabulary expansion (73 candidate rows).
    if len(reference_df) != 73:
        raise RuntimeError(
            "Reference candidate row count changed: "
            f"expected 73, found {len(reference_df)}."
        )


    generation_pairs = (
        generation_df[["sample_id", "condition"]]
        .astype(str)
        .drop_duplicates()
    )

    if len(generation_pairs) != EXPECTED_GENERATION_RECORDS:
        raise RuntimeError(
            "Expected "
            f"{EXPECTED_GENERATION_RECORDS} generation "
            "records, found "
            f"{len(generation_pairs)}."
        )

    detail_df = build_factuality_table(
        generation_df,
        reference_df,
        generated_claims_df,
    )

    summary_df = summarize_by_condition(
        detail_df,
        generation_df,
    )

    DETAIL_OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    detail_df.to_csv(
        DETAIL_OUTPUT_PATH,
        index=False,
    )

    summary_df.to_csv(
        SUMMARY_OUTPUT_PATH,
        index=False,
    )

    print("=" * 70)
    print("REFERENCE-GROUNDED FACTUALITY COMPARISON")
    print("=" * 70)

    print(
        "These counts are polarity comparisons against "
        "reference claim candidates."
    )
    print(
        "They are not hallucination rate, factuality F1, "
        "reliability score, or overall accuracy."
    )

    print(
        f"\nGeneration records: {len(generation_df)}"
    )
    print(
        f"Reference candidate rows: {len(reference_df)}"
    )
    print(
        f"Generated claim rows: {len(generated_claims_df)}"
    )
    print(
        f"Comparison rows: {len(detail_df)}"
    )

    represented = detail_df[
        ["sample_id", "condition"]
    ].drop_duplicates()

    print(
        "Represented generation records: "
        f"{len(represented)}"
    )

    print("\nLabel counts:")
    print(
        detail_df["label"]
        .value_counts()
        .reindex(sorted(VALID_LABELS), fill_value=0)
        .to_string()
    )

    print("\nBy condition:")
    print(summary_df.to_string(index=False))

    print(
        f"\nDetail output: {DETAIL_OUTPUT_PATH}"
    )
    print(
        f"Summary output: {SUMMARY_OUTPUT_PATH}"
    )

    print(
        "\nPhase 6 limitation (unchanged): "
        "claim_evaluator.py matches by (sample_id, finding) "
        "and ignores condition."
    )


if __name__ == "__main__":
    main()


================================================================================
src/evaluation/build_reference_candidates.py
================================================================================
from pathlib import Path
import sys

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.evaluation.claim_patterns import (
    extract_raw_claim_records,
)


DATASET_PATH = Path(
    "data/processed/iu_xray/metadata/dataset.csv"
)

OUTPUT_PATH = Path(
    "results/tables/reference_claim_candidates.csv"
)


def extract_reference_candidates(
    df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Extract candidate reference findings from findings +
    impression text.
    """

    records = []

    for _, row in df.iterrows():

        sample_id = str(
            row["sample_id"]
        )


In [ ]:
# ============================================================
# Phase26D Evaluation Claim Analysis
#
# Development-selected policy:
#   baseline  = lambda 0.00
#   selected  = lambda 0.25
#
# Evaluation cohort:
#   80 studies × 6 conditions = 480 records
#   2 lambdas = 960 generated reports
#
# Uses the established:
#   - reference candidate extractor
#   - generated claim extractor
#   - reference-grounded factuality evaluator
#
# Does NOT modify the existing evaluation source files.
# ============================================================

from pathlib import Path
import pandas as pd

from src.evaluation.build_reference_candidates import (
    extract_reference_candidates,
)

from src.evaluation.claim_extractor import (
    extract_generated_claim_candidates,
)

from src.evaluation.evaluate_reference_factuality import (
    build_factuality_table,
)


# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

GENERATION_PATH = Path(
    "results/maira2_contrastive/phase26d_evaluation/"
    "phase26d_evaluation_generation.csv"
)

BENCHMARK_PATH = Path(
    "results/tables/phase16_perturbations.csv"
)

OUTPUT_DIR = Path(
    "results/tables/phase26d_claim_evaluation"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ------------------------------------------------------------
# Load generated evaluation trajectories
# ------------------------------------------------------------

generation = pd.read_csv(
    GENERATION_PATH
)

print("Generation rows:", len(generation))

assert len(generation) == 960

assert (
    generation["status"]
    .astype(str)
    .eq("success")
    .all()
)

assert (
    generation["lambda"]
    .value_counts()
    .to_dict()
    == {
        0.0: 480,
        0.25: 480,
    }
)


# ------------------------------------------------------------
# Load benchmark
# ------------------------------------------------------------

benchmark = pd.read_csv(
    BENCHMARK_PATH
)

benchmark["uid"] = (
    benchmark["uid"]
    .astype(int)
)


# ------------------------------------------------------------
# Build stable reference table
#
# Findings/impression are identical across the six
# perturbation conditions for a study.
#
# Therefore use one row per study.
# ------------------------------------------------------------

reference_source = (
    benchmark[
        [
            "sample_id",
            "uid",
            "findings",
            "impression",
        ]
    ]
    .drop_duplicates(
        subset=["sample_id", "uid"]
    )
    .reset_index(drop=True)
)

print(
    "Reference studies:",
    len(reference_source)
)

assert len(reference_source) == 100


# ------------------------------------------------------------
# Restrict reference studies to the 80-study evaluation split
# ------------------------------------------------------------

evaluation_uids = set(
    generation["uid"]
    .astype(int)
)

reference_source = (
    reference_source[
        reference_source["uid"]
        .isin(evaluation_uids)
    ]
    .copy()
)

print(
    "Evaluation reference studies:",
    len(reference_source)
)

assert len(reference_source) == 80


# ------------------------------------------------------------
# Extract reference claim candidates
# ------------------------------------------------------------

reference_claims = (
    extract_reference_candidates(
        reference_source[
            [
                "sample_id",
                "findings",
                "impression",
            ]
        ]
    )
)

print(
    "Reference claim candidates:",
    len(reference_claims)
)


# ------------------------------------------------------------
# Prepare generated reports for the established extractor
# ------------------------------------------------------------

generation_for_extractor = (
    generation[
        [
            "sample_id",
            "condition",
            "lambda",
            "report",
        ]
    ]
    .rename(
        columns={
            "report": "generated_report"
        }
    )
)


# ------------------------------------------------------------
# Extract generated claim candidates
#
# The existing extractor requires:
#   sample_id
#   condition
#   generated_report
#
# Lambda is retained separately for pairing.
# ------------------------------------------------------------

generated_claims_by_lambda = []

for lambda_value in [0.0, 0.25]:

    subset = (
        generation_for_extractor[
            generation_for_extractor["lambda"]
            == lambda_value
        ]
        .drop(columns=["lambda"])
        .copy()
    )

    claims = (
        extract_generated_claim_candidates(
            subset
        )
    )

    if not claims.empty:

        claims["lambda"] = (
            float(lambda_value)
        )

    generated_claims_by_lambda.append(
        claims
    )

generated_claims = pd.concat(
    generated_claims_by_lambda,
    ignore_index=True,
)

print(
    "Generated claim candidates:",
    len(generated_claims)
)


# ------------------------------------------------------------
# Build factuality tables separately for each lambda
# ------------------------------------------------------------

factuality_tables = []

for lambda_value in [0.0, 0.25]:

    report_subset = (
        generation[
            generation["lambda"]
            == lambda_value
        ][
            [
                "sample_id",
                "condition",
                "report",
            ]
        ]
        .rename(
            columns={
                "report": "generated_report"
            }
        )
        .copy()
    )

    claim_subset = (
        generated_claims[
            generated_claims["lambda"]
            == lambda_value
        ]
        .drop(
            columns=["lambda"]
        )
        .copy()
    )

    factuality = (
        build_factuality_table(
            report_subset,
            reference_claims,
            claim_subset,
        )
    )

    factuality["lambda"] = (
        float(lambda_value)
    )

    factuality_tables.append(
        factuality
    )


factuality = pd.concat(
    factuality_tables,
    ignore_index=True,
)


# ------------------------------------------------------------
# Add UID
# ------------------------------------------------------------

uid_lookup = (
    generation[
        [
            "sample_id",
            "uid",
        ]
    ]
    .drop_duplicates(
        subset=["sample_id"]
    )
)

factuality = factuality.merge(
    uid_lookup,
    on="sample_id",
    how="left",
    validate="many_to_one",
)


# ------------------------------------------------------------
# Sort and save detailed claim evaluation
# ------------------------------------------------------------

factuality = (
    factuality[
        [
            "sample_id",
            "uid",
            "condition",
            "lambda",
            "finding",
            "generated_polarity",
            "reference_polarity",
            "label",
        ]
    ]
    .sort_values(
        [
            "sample_id",
            "condition",
            "finding",
            "lambda",
        ]
    )
    .reset_index(drop=True)
)


DETAIL_PATH = (
    OUTPUT_DIR
    / "phase26d_evaluation_claims.csv"
)

factuality.to_csv(
    DETAIL_PATH,
    index=False,
)


# ------------------------------------------------------------
# Summary counts
# ------------------------------------------------------------

VALID_LABELS = [
    "supported",
    "omission",
    "extra_negation",
    "ungrounded_affirmation",
    "unsupported_affirmation",
    "contradiction",
    "unclear",
]

UNSUPPORTED_LABELS = {
    "ungrounded_affirmation",
    "unsupported_affirmation",
    "contradiction",
}


summary_rows = []


for lambda_value in [0.0, 0.25]:

    subset = factuality[
        factuality["lambda"]
        == lambda_value
    ]

    label_counts = (
        subset["label"]
        .value_counts()
        .to_dict()
    )

    evaluated = sum(
        int(label_counts.get(label, 0))
        for label in VALID_LABELS
        if label != "omission"
    )

    unsupported = sum(
        int(label_counts.get(label, 0))
        for label in UNSUPPORTED_LABELS
    )

    row = {
        "lambda": lambda_value,
        "comparison_rows": len(subset),
        "supported": int(
            label_counts.get(
                "supported",
                0,
            )
        ),
        "omission": int(
            label_counts.get(
                "omission",
                0,
            )
        ),
        "extra_negation": int(
            label_counts.get(
                "extra_negation",
                0,
            )
        ),
        "ungrounded_affirmation": int(
            label_counts.get(
                "ungrounded_affirmation",
                0,
            )
        ),
        "unsupported_affirmation": int(
            label_counts.get(
                "unsupported_affirmation",
                0,
            )
        ),
        "contradiction": int(
            label_counts.get(
                "contradiction",
                0,
            )
        ),
        "unclear": int(
            label_counts.get(
                "unclear",
                0,
            )
        ),
        "unsupported_claim_count": unsupported,
        "unsupported_claim_rate_denominator": evaluated,
        "unsupported_claim_rate": (
            unsupported / evaluated
            if evaluated
            else 0.0
        ),
    }

    summary_rows.append(
        row
    )


summary = pd.DataFrame(
    summary_rows
)


SUMMARY_PATH = (
    OUTPUT_DIR
    / "phase26d_evaluation_claim_summary.csv"
)

summary.to_csv(
    SUMMARY_PATH,
    index=False,
)


# ------------------------------------------------------------
# Condition × lambda summary
# ------------------------------------------------------------

condition_rows = []

for (
    condition,
    lambda_value,
), subset in factuality.groupby(
    [
        "condition",
        "lambda",
    ]
):

    label_counts = (
        subset["label"]
        .value_counts()
        .to_dict()
    )

    evaluated = sum(
        int(label_counts.get(label, 0))
        for label in VALID_LABELS
        if label != "omission"
    )

    unsupported = sum(
        int(label_counts.get(label, 0))
        for label in UNSUPPORTED_LABELS
    )

    condition_rows.append(
        {
            "condition": condition,
            "lambda": lambda_value,
            "comparison_rows": len(
                subset
            ),
            "supported": int(
                label_counts.get(
                    "supported",
                    0,
                )
            ),
            "omission": int(
                label_counts.get(
                    "omission",
                    0,
                )
            ),
            "extra_negation": int(
                label_counts.get(
                    "extra_negation",
                    0,
                )
            ),
            "ungrounded_affirmation": int(
                label_counts.get(
                    "ungrounded_affirmation",
                    0,
                )
            ),
            "unsupported_affirmation": int(
                label_counts.get(
                    "unsupported_affirmation",
                    0,
                )
            ),
            "contradiction": int(
                label_counts.get(
                    "contradiction",
                    0,
                )
            ),
            "unclear": int(
                label_counts.get(
                    "unclear",
                    0,
                )
            ),
            "unsupported_claim_count": unsupported,
            "unsupported_claim_rate_denominator": evaluated,
            "unsupported_claim_rate": (
                unsupported / evaluated
                if evaluated
                else 0.0
            ),
        }
    )


condition_summary = (
    pd.DataFrame(
        condition_rows
    )
    .sort_values(
        [
            "condition",
            "lambda",
        ]
    )
    .reset_index(drop=True)
)


CONDITION_PATH = (
    OUTPUT_DIR
    / "phase26d_evaluation_claim_summary_by_condition.csv"
)

condition_summary.to_csv(
    CONDITION_PATH,
    index=False,
)


# ------------------------------------------------------------
# Final audit
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PHASE26D CLAIM EVALUATION")
print("=" * 70)

print(
    f"Evaluation reports: {len(generation)}"
)

print(
    f"Reference studies: {len(reference_source)}"
)

print(
    f"Reference candidates: {len(reference_claims)}"
)

print(
    f"Generated claim candidates: "
    f"{len(generated_claims)}"
)

print(
    f"Factuality comparison rows: "
    f"{len(factuality)}"
)

print("\nOverall summary:")
print(
    summary.to_string(
        index=False
    )
)

print("\nCondition summary:")
print(
    condition_summary.to_string(
        index=False
    )
)

print("\nOutputs:")
print(
    DETAIL_PATH
)
print(
    SUMMARY_PATH
)
print(
    CONDITION_PATH
)

Generation rows: 960
Reference studies: 100
Evaluation reference studies: 80
Reference claim candidates: 265
Generated claim candidates: 1845

======================================================================
PHASE26D CLAIM EVALUATION
======================================================================
Evaluation reports: 960
Reference studies: 80
Reference candidates: 265
Generated claim candidates: 1845
Factuality comparison rows: 3864

Overall summary:
 lambda  comparison_rows  supported  omission  extra_negation  ungrounded_affirmation  unsupported_affirmation  contradiction  unclear  unsupported_claim_count  unsupported_claim_rate_denominator  unsupported_claim_rate
   0.00             1940        471      1005             269                      91                       35             45       24                      171                                 935                0.182888
   0.25             1924        479       993             271                      77                       38             53       13                      168                                 931                0.180451

Condition summary:
             condition  lambda  comparison_rows  supported  omission  extra_negation  ungrounded_affirmation  unsupported_affirmation  contradiction  unclear  unsupported_claim_count  unsupported_claim_rate_denominator  unsupported_claim_rate
           conflicting    0.00              308         50       171              33                      12                       28              6        8                       46                                 137                0.335766
           conflicting    0.25              311         55       161              42                       8                       33              9        3                       50                                 150                0.333333
evidentiary_incomplete    0.00              337        110       132              59                      16                        4             13        3                       33                                 205                0.160976
evidentiary_incomplete    0.25              325         94       153              48                      15                        1             13        1                       29                                 172                0.168605
          insufficient    0.00              288         21       240               6                      16                        0              0        5                       16                                  48                0.333333
          insufficient    0.25              288         21       240               6                      16                        0              0        5                       16                                  48                0.333333
            irrelevant    0.00              340         98       156              59                      18                        2              5        2                       25                                 184                0.135870
            irrelevant    0.25              345        107       147              67                      16                        1              6        1                       23                                 198                0.116162
            sufficient    0.00              339        101       148              57                      19                        1             11        2                       31                                 191                0.162304
            sufficient    0.25              333        107       141              60                      10                        1             12        2                       23                                 192                0.119792
  syntactic_incomplete    0.00              328         91       158              55                      10                        0             10        4                       20                                 170                0.117647
  syntactic_incomplete    0.25              322         95       151              48                      12                        2             13        1                       27                                 171                0.157895

Outputs:
results/tables/phase26d_claim_evaluation/phase26d_evaluation_claims.csv
results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary.csv
results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary_by_condition.csv

In [ ]:
# ============================================================
# Phase26D Paired Statistical Evaluation
# ============================================================

import numpy as np
import pandas as pd

from scipy.stats import (
    wilcoxon,
    binomtest,
)


DETAIL_PATH = (
    "results/tables/phase26d_claim_evaluation/"
    "phase26d_evaluation_claims.csv"
)

detail = pd.read_csv(DETAIL_PATH)

UNSUPPORTED_LABELS = {
    "ungrounded_affirmation",
    "unsupported_affirmation",
    "contradiction",
}

# ------------------------------------------------------------
# Unsupported claims per record
# ------------------------------------------------------------

detail["is_unsupported"] = (
    detail["label"]
    .isin(UNSUPPORTED_LABELS)
)


record_rows = []

for (
    sample_id,
    uid,
    condition,
    lambda_value,
), group in detail.groupby(
    [
        "sample_id",
        "uid",
        "condition",
        "lambda",
    ],
    sort=True,
):

    unsupported_count = int(
        group["is_unsupported"].sum()
    )

    evaluated_count = int(
        (
            group["label"]
            != "omission"
        ).sum()
    )

    unsupported_rate = (
        unsupported_count / evaluated_count
        if evaluated_count
        else 0.0
    )

    record_rows.append(
        {
            "sample_id": sample_id,
            "uid": int(uid),
            "condition": condition,
            "lambda": float(lambda_value),
            "unsupported_count": unsupported_count,
            "evaluated_count": evaluated_count,
            "unsupported_rate": unsupported_rate,
            "has_unsupported": (
                unsupported_count > 0
            ),
        }
    )


record_df = pd.DataFrame(
    record_rows
)

# ------------------------------------------------------------
# Pivot baseline and selected policy
# ------------------------------------------------------------

baseline = (
    record_df[
        record_df["lambda"] == 0.0
    ]
    .rename(
        columns={
            "unsupported_count":
                "baseline_unsupported_count",
            "evaluated_count":
                "baseline_evaluated_count",
            "unsupported_rate":
                "baseline_unsupported_rate",
            "has_unsupported":
                "baseline_has_unsupported",
        }
    )
    .drop(columns=["lambda"])
)

selected = (
    record_df[
        record_df["lambda"] == 0.25
    ]
    .rename(
        columns={
            "unsupported_count":
                "selected_unsupported_count",
            "evaluated_count":
                "selected_evaluated_count",
            "unsupported_rate":
                "selected_unsupported_rate",
            "has_unsupported":
                "selected_has_unsupported",
        }
    )
    .drop(columns=["lambda"])
)

paired = baseline.merge(
    selected,
    on=[
        "sample_id",
        "uid",
        "condition",
    ],
    how="inner",
    validate="one_to_one",
)

assert len(paired) == 480

# ------------------------------------------------------------
# Record-level unsupported indicator
# ------------------------------------------------------------

baseline_positive = int(
    paired[
        "baseline_has_unsupported"
    ].sum()
)

selected_positive = int(
    paired[
        "selected_has_unsupported"
    ].sum()
)

baseline_only = int(
    (
        paired["baseline_has_unsupported"]
        &
        ~paired["selected_has_unsupported"]
    ).sum()
)

selected_only = int(
    (
        ~paired["baseline_has_unsupported"]
        &
        paired["selected_has_unsupported"]
    ).sum()
)

both_positive = int(
    (
        paired["baseline_has_unsupported"]
        &
        paired["selected_has_unsupported"]
    ).sum()
)

neither_positive = int(
    (
        ~paired["baseline_has_unsupported"]
        &
        ~paired["selected_has_unsupported"]
    ).sum()
)

# ------------------------------------------------------------
# Exact McNemar test
#
# Conditional on discordant pairs:
# baseline-only vs selected-only
# ------------------------------------------------------------

discordant = (
    baseline_only
    + selected_only
)

if discordant > 0:

    mcnemar = binomtest(
        k=min(
            baseline_only,
            selected_only,
        ),
        n=discordant,
        p=0.5,
        alternative="two-sided",
    )

    mcnemar_p = float(
        mcnemar.pvalue
    )

else:

    mcnemar_p = 1.0


# ------------------------------------------------------------
# Wilcoxon signed-rank test
#
# Per-record unsupported claim rate
# ------------------------------------------------------------

paired["delta_rate"] = (
    paired["selected_unsupported_rate"]
    -
    paired["baseline_unsupported_rate"]
)

nonzero = paired[
    paired["delta_rate"] != 0
]

if len(nonzero) > 0:

    wilcox = wilcoxon(
        nonzero[
            "selected_unsupported_rate"
        ],
        nonzero[
            "baseline_unsupported_rate"
        ],
        alternative="two-sided",
        zero_method="wilcox",
        method="auto",
    )

    wilcoxon_stat = float(
        wilcox.statistic
    )

    wilcoxon_p = float(
        wilcox.pvalue
    )

else:

    wilcoxon_stat = 0.0
    wilcoxon_p = 1.0


# ------------------------------------------------------------
# Rank-biserial effect size
# ------------------------------------------------------------

positive_deltas = int(
    (
        nonzero["delta_rate"]
        > 0
    ).sum()
)

negative_deltas = int(
    (
        nonzero["delta_rate"]
        < 0
    ).sum()
)

if len(nonzero) > 0:

    rank_biserial = (
        negative_deltas
        -
        positive_deltas
    ) / len(nonzero)

else:

    rank_biserial = 0.0


# ------------------------------------------------------------
# Pooled claim-level rates
# ------------------------------------------------------------

pooled = (
    detail.groupby(
        "lambda"
    )
    .agg(
        unsupported_claims=(
            "is_unsupported",
            "sum",
        ),
        evaluated_claims=(
            "is_unsupported",
            "count",
        ),
    )
    .reset_index()
)

# Recompute denominator excluding omissions
pooled_rows = []

for lambda_value, group in detail.groupby(
    "lambda"
):

    unsupported = int(
        group["is_unsupported"].sum()
    )

    evaluated = int(
        (
            group["label"]
            != "omission"
        ).sum()
    )

    pooled_rows.append(
        {
            "lambda": float(lambda_value),
            "unsupported_claims": unsupported,
            "evaluated_claims": evaluated,
            "unsupported_rate": (
                unsupported / evaluated
                if evaluated
                else 0.0
            ),
        }
    )

pooled = pd.DataFrame(
    pooled_rows
)

baseline_rate = float(
    pooled.loc[
        pooled["lambda"] == 0.0,
        "unsupported_rate",
    ].iloc[0]
)

selected_rate = float(
    pooled.loc[
        pooled["lambda"] == 0.25,
        "unsupported_rate",
    ].iloc[0]
)

absolute_change = (
    selected_rate
    -
    baseline_rate
)

relative_reduction = (
    (baseline_rate - selected_rate)
    / baseline_rate
    if baseline_rate
    else 0.0
)


# ------------------------------------------------------------
# Print results
# ------------------------------------------------------------

print("=" * 70)
print("PHASE26D PAIRED STATISTICAL EVALUATION")
print("=" * 70)

print(
    f"\nPaired evaluation records: {len(paired)}"
)

print("\nRecord-level unsupported status:")
print(
    f"Baseline positive: {baseline_positive}"
)

print(
    f"λ=0.25 positive: {selected_positive}"
)

print(
    f"Baseline-only: {baseline_only}"
)

print(
    f"λ=0.25-only: {selected_only}"
)

print(
    f"Both positive: {both_positive}"
)

print(
    f"Neither positive: {neither_positive}"
)

print(
    f"Discordant pairs: {discordant}"
)

print(
    f"\nMcNemar exact p-value: "
    f"{mcnemar_p:.6g}"
)

print("\nPer-record unsupported-rate comparison:")

print(
    f"Non-zero paired differences: "
    f"{len(nonzero)}"
)

print(
    f"Wilcoxon statistic: "
    f"{wilcoxon_stat:.6g}"
)

print(
    f"Wilcoxon p-value: "
    f"{wilcoxon_p:.6g}"
)

print(
    f"Rank-biserial effect size: "
    f"{rank_biserial:.6f}"
)

print("\nPooled claim-level risk:")

print(
    pooled.to_string(
        index=False
    )
)

print(
    f"\nAbsolute rate change: "
    f"{absolute_change:.6f}"
)

print(
    f"Relative reduction: "
    f"{relative_reduction:.6%}"
)


# ------------------------------------------------------------
# Save paired record table
# ------------------------------------------------------------

PAIRED_PATH = (
    "results/tables/phase26d_claim_evaluation/"
    "phase26d_evaluation_paired_records.csv"
)

paired.to_csv(
    PAIRED_PATH,
    index=False,
)

print(
    f"\nPaired record output: {PAIRED_PATH}"
)

======================================================================
PHASE26D PAIRED STATISTICAL EVALUATION
======================================================================

Paired evaluation records: 480

Record-level unsupported status:
Baseline positive: 126
λ=0.25 positive: 129
Baseline-only: 30
λ=0.25-only: 33
Both positive: 96
Neither positive: 321
Discordant pairs: 63

McNemar exact p-value: 0.801306

Per-record unsupported-rate comparison:
Non-zero paired differences: 102
Wilcoxon statistic: 2328.5
Wilcoxon p-value: 0.318635
Rank-biserial effect size: -0.078431

Pooled claim-level risk:
 lambda  unsupported_claims  evaluated_claims  unsupported_rate
   0.00                 171               935          0.182888
   0.25                 168               931          0.180451

Absolute rate change: -0.002437
Relative reduction: 1.332278%

Paired record output: results/tables/phase26d_claim_evaluation/phase26d_evaluation_paired_records.csv

In [ ]:
from pathlib import Path

for filename in [
    "src/evaluation/evaluate_radgraph_f1.py",
    "src/evaluation/evaluate_chexpert_f1.py",
]:
    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)

    path = Path(filename)
    print(path.read_text())

================================================================================
src/evaluation/evaluate_radgraph_f1.py
================================================================================
"""
Phase 15 Evaluation: RadGraph-F1 Clinical Content / Entity-Relation Evaluation.

Evaluates entity and relation overlap between generated radiology reports
(baseline and Phase 13B gated reports) and reference reports (reference findings + impression).

Uses the official `radgraph` PyPI package (F1RadGraph / DyGIE model).

Outputs:
    results/tables/radgraph_f1_results.csv
    results/tables/radgraph_f1_summary.csv

Scientific Integrity Note:
    RadGraph-F1 measures clinical entity and relation overlap against reference text.
    It is NOT a direct measure of hallucination rate, factuality accuracy, or safety.
"""

from pathlib import Path
import sys
from typing import Dict, List, Tuple, Any

import pandas as pd
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# Monkeypatch transformers for radgraph compatibility with transformers >= 5.0
import transformers

if not hasattr(transformers.PreTrainedTokenizerBase, "encode_plus"):
    transformers.PreTrainedTokenizerBase.encode_plus = transformers.PreTrainedTokenizerBase.__call__

if not hasattr(transformers.PreTrainedTokenizerBase, "build_inputs_with_special_tokens"):
    def _build_inputs_with_special_tokens(self, token_ids_0, token_ids_1=None):
        if token_ids_1 is None:
            return [self.cls_token_id] + token_ids_0 + [self.sep_token_id]
        return [self.cls_token_id] + token_ids_0 + [self.sep_token_id] + token_ids_1 + [self.sep_token_id]
    transformers.PreTrainedTokenizerBase.build_inputs_with_special_tokens = _build_inputs_with_special_tokens

from radgraph import F1RadGraph

PERTURBATIONS_PATH = ROOT / "data/processed/iu_xray/perturbations/perturbations.csv"
BASELINE_PATH = ROOT / "results/tables/baseline_generation_results.csv"
GATED_PATH = ROOT / "results/tables/phase13b_gated_generation_results.csv"

RESULTS_OUTPUT_PATH = ROOT / "results/tables/radgraph_f1_results.csv"
SUMMARY_OUTPUT_PATH = ROOT / "results/tables/radgraph_f1_summary.csv"

REQUIRED_CONDITIONS = [
    "sufficient",
    "incomplete",
    "irrelevant",
    "conflicting",
    "insufficient",
]


def load_input_data() -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    for p in [PERTURBATIONS_PATH, BASELINE_PATH, GATED_PATH]:
        if not p.exists():
            raise FileNotFoundError(f"Required input file not found: {p}")

    pert_df = pd.read_csv(PERTURBATIONS_PATH)
    base_df = pd.read_csv(BASELINE_PATH)
    gated_df = pd.read_csv(GATED_PATH)

    if len(pert_df) != 81 or len(base_df) != 81 or len(gated_df) != 81:
        raise ValueError("Expected exactly 81 records in input files.")

    return pert_df, base_df, gated_df


def compute_radgraph_scores(
    refs: List[str],
    hyps: List[str],
    model_type: str = "radgraph",
) -> Tuple[List[float], List[float], List[float]]:
    """
    Compute RadGraph precision, recall, and F1 for a list of reference and hypothesis pairs.
    """
    f1radgraph = F1RadGraph(reward_level="all", model_type=model_type)
    _, reward_list, _, _ = f1radgraph(refs=refs, hyps=hyps)

    precisions = [float(p) for p in reward_list[0]]
    recalls = [float(r) for r in reward_list[1]]
    f1_scores = [float(f) for f in reward_list[2]]

    return precisions, recalls, f1_scores


def evaluate_radgraph() -> Tuple[pd.DataFrame, pd.DataFrame]:
    pert_df, base_df, gated_df = load_input_data()

    # Build reference reports (findings + impression)
    reference_reports = []
    sample_ids = []
    conditions = []
    baseline_reports = []
    gated_reports = []

    # Map baseline and gated by (sample_id, condition)
    base_lookup = {
        (str(r["sample_id"]), str(r["condition"])): str(r["generated_report"])
        for _, r in base_df.iterrows()
    }
    gated_lookup = {
        (str(r["sample_id"]), str(r["condition"])): str(r["gated_report"])
        for _, r in gated_df.iterrows()
    }

    for _, row in pert_df.iterrows():
        sid = str(row["sample_id"])
        cond = str(row["condition"])
        rf = str(row["reference_findings"]) if pd.notna(row["reference_findings"]) else ""
        ri = str(row["reference_impression"]) if pd.notna(row["reference_impression"]) else ""
        ref_text = f"{rf} {ri}".strip()

        sample_ids.append(sid)
        conditions.append(cond)
        reference_reports.append(ref_text)
        baseline_reports.append(base_lookup[(sid, cond)])
        gated_reports.append(gated_lookup[(sid, cond)])

    # Compute baseline RadGraph scores
    b_prec, b_rec, b_f1 = compute_radgraph_scores(reference_reports, baseline_reports)

    # Compute gated RadGraph scores
    g_prec, g_rec, g_f1 = compute_radgraph_scores(reference_reports, gated_reports)

    results_rows = []
    for i in range(len(sample_ids)):
        delta_f1 = g_f1[i] - b_f1[i]
        results_rows.append(
            {
                "sample_id": sample_ids[i],
                "condition": conditions[i],
                "baseline_radgraph_precision": round(b_prec[i], 4),
                "baseline_radgraph_recall": round(b_rec[i], 4),
                "baseline_radgraph_f1": round(b_f1[i], 4),
                "gated_radgraph_precision": round(g_prec[i], 4),
                "gated_radgraph_recall": round(g_rec[i], 4),
                "gated_radgraph_f1": round(g_f1[i], 4),
                "delta_radgraph_f1": round(delta_f1, 4),
            }
        )

    results_df = pd.DataFrame(results_rows)

    # Summary table
    summary_rows = []
    subsets = [("overall", results_df)] + [
        (c, results_df[results_df["condition"] == c]) for c in REQUIRED_CONDITIONS
    ]

    for scope, subset in subsets:
        n = len(subset)
        summary_rows.append(
            {
                "condition": scope,
                "n_records": n,
                "mean_baseline_radgraph_precision": round(float(subset["baseline_radgraph_precision"].mean()), 4),
                "mean_baseline_radgraph_recall": round(float(subset["baseline_radgraph_recall"].mean()), 4),
                "mean_baseline_radgraph_f1": round(float(subset["baseline_radgraph_f1"].mean()), 4),
                "mean_gated_radgraph_precision": round(float(subset["gated_radgraph_precision"].mean()), 4),
                "mean_gated_radgraph_recall": round(float(subset["gated_radgraph_recall"].mean()), 4),
                "mean_gated_radgraph_f1": round(float(subset["gated_radgraph_f1"].mean()), 4),
                "mean_delta_radgraph_f1": round(float(subset["delta_radgraph_f1"].mean()), 4),
            }
        )

    summary_df = pd.DataFrame(summary_rows)
    return results_df, summary_df


def main() -> None:
    print("=" * 70)
    print("RADGRAPH-F1 EVALUATION")
    print("=" * 70)

    results_df, summary_df = evaluate_radgraph()

    RESULTS_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    results_df.to_csv(RESULTS_OUTPUT_PATH, index=False)
    summary_df.to_csv(SUMMARY_OUTPUT_PATH, index=False)

    print(f"Results saved to: {RESULTS_OUTPUT_PATH}")
    print(f"Summary saved to: {SUMMARY_OUTPUT_PATH}\n")
    print(summary_df.to_string(index=False))


if __name__ == "__main__":
    main()


================================================================================
src/evaluation/evaluate_chexpert_f1.py
================================================================================
"""
Phase 15 Evaluation: CheXpert-F1 Clinical Finding Evaluation.

Evaluates clinical finding overlap across 14 Stanford CheXpert observation categories
between generated radiology reports (baseline and Phase 13B gated reports) and reference reports.

14 CheXpert Categories:
    1. Enlarged Cardiomediastinum
    2. Cardiomegaly
    3. Lung Opacity
    4. Lung Lesion
    5. Edema
    6. Consolidation
    7. Pneumonia
    8. Atelectasis
    9. Pneumothorax
    10. Pleural Effusion
    11. Pleural Other
    12. Fracture
    13. Support Devices
    14. No Finding

Label-Handling Policy (Explicitly Documented):
    - Positive (1): Explicit positive mention of condition.
    - Negative (0): Explicit negation of condition.
    - Uncertain (-1): Equivocal/uncertain mention (retained in label vectors for auditability).
    - Unmentioned (nan): Condition not mentioned in report text.
    - Metric calculation: Positive targets are compared against candidate positive predictions.
      Uncertain labels (-1) are NOT silently treated as positive or negative.

Outputs:
    results/tables/chexpert_f1_results.csv
    results/tables/chexpert_f1_summary.csv
"""

from pathlib import Path
import sys
from typing import Dict, List, Tuple, Any

import pandas as pd
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

PERTURBATIONS_PATH = ROOT / "data/processed/iu_xray/perturbations/perturbations.csv"
BASELINE_PATH = ROOT / "results/tables/baseline_generation_results.csv"
GATED_PATH = ROOT / "results/tables/phase13b_gated_generation_results.csv"

RESULTS_OUTPUT_PATH = ROOT / "results/tables/chexpert_f1_results.csv"
SUMMARY_OUTPUT_PATH = ROOT / "results/tables/chexpert_f1_summary.csv"

REQUIRED_CONDITIONS = [
    "sufficient",
    "incomplete",
    "irrelevant",
    "conflicting",
    "insufficient",
]

CHEXPERT_CATEGORIES = [
    "Enlarged Cardiomediastinum",
    "Cardiomegaly",
    "Lung Opacity",
    "Lung Lesion",
    "Edema",
    "Consolidation",
    "Pneumonia",
    "Atelectasis",
    "Pneumothorax",
    "Pleural Effusion",
    "Pleural Other",
    "Fracture",
    "Support Devices",
    "No Finding",
]

# Patterns for CheXpert labeling
CATEGORY_PATTERNS = {
    "Cardiomegaly": ["cardiomegaly", "enlarged heart", "cardiac silhouette is enlarged", "borderline enlarged cardiac silhouette", "borderline cardiomegaly"],
    "Enlarged Cardiomediastinum": ["enlarged mediastinum", "mediastinal widening", "widened mediastinum", "enlarged cardiomediastinum"],
    "Lung Opacity": ["airspace opacity", "air space opacity", "lung opacity", "pulmonary opacity", "opacities", "opacity", "airspace disease", "air space disease", "infiltrate", "infiltrates", "density", "densities"],
    "Lung Lesion": ["nodule", "nodules", "mass", "masses", "lung lesion", "granuloma", "calcified granuloma", "granulomatous disease"],
    "Edema": ["pulmonary edema", "edema", "vascular congestion", "pulmonary congestion", "chf"],
    "Consolidation": ["consolidation", "focal consolidation", "consolidations"],
    "Pneumonia": ["pneumonia", "infectious process"],
    "Atelectasis": ["atelectasis", "collapse", "basilar atelectasis"],
    "Pneumothorax": ["pneumothorax", "pneumothoraces"],
    "Pleural Effusion": ["pleural effusion", "pleural effusions", "effusion", "effusions"],
    "Pleural Other": ["pleural thickening", "pleural plaque", "pleural scarring"],
    "Fracture": ["fracture", "fractures", "rib fracture", "displaced fracture"],
    "Support Devices": ["tube", "catheter", "line", "pacemaker", "stent", "picc", "hardware", "pigtail"],
    "No Finding": ["no acute cardiopulmonary abnormality", "no acute cardiopulmonary process", "lungs are clear", "no findings", "unremarkable chest", "no acute intrathoracic process"],
}

NEGATION_CUES = ["no ", "no evidence of ", "without ", "free of ", "negative for ", "cleared "]
UNCERTAIN_CUES = ["possible", "probable", "cannot be excluded", "cannot rule out", "evaluating for", "questionable", "borderline"]


def label_condition_in_text(text: str, category: str) -> int:
    """
    Assign label for a single CheXpert category in text:
        1: Positive
        0: Negative
        -1: Uncertain
        9: Unmentioned (used internally, mapped to nan)
    """
    text_lower = text.lower()
    patterns = CATEGORY_PATTERNS.get(category, [])

    matched = False
    matched_pos = -1
    for p in patterns:
        pos = text_lower.find(p)
        if pos != -1:
            matched = True
            matched_pos = pos
            break

    if not matched:
        return 9  # Unmentioned

    # Check negation
    prefix = text_lower[max(0, matched_pos - 30):matched_pos]
    for n in NEGATION_CUES:
        if n in prefix:
            return 0  # Negative

    # Check uncertainty
    for u in UNCERTAIN_CUES:
        if u in prefix or u in text_lower[matched_pos:matched_pos + len(patterns[0]) + 20]:
            return -1  # Uncertain

    return 1  # Positive


def extract_chexpert_vector(text: str) -> Dict[str, Any]:
    """
    Extract 14-condition CheXpert label vector from text.
    """
    vector = {}
    for cat in CHEXPERT_CATEGORIES:
        lbl = label_condition_in_text(text, cat)
        vector[cat] = lbl if lbl != 9 else np.nan
    return vector


def compute_chexpert_f1(ref_vector: Dict[str, Any], cand_vector: Dict[str, Any]) -> float:
    """
    Compute micro CheXpert-F1 between reference vector and candidate vector.

    Positive targets are conditions where ref_vector == 1.
    """
    tp = 0
    fp = 0
    fn = 0

    for cat in CHEXPERT_CATEGORIES:
        r_val = ref_vector[cat]
        c_val = cand_vector[cat]

        r_pos = (r_val == 1)
        c_pos = (c_val == 1)

        if r_pos and c_pos:
            tp += 1
        elif not r_pos and c_pos:
            fp += 1
        elif r_pos and not c_pos:
            fn += 1

    if tp == 0 and fp == 0 and fn == 0:
        return 1.0  # Perfect agreement on absence of positive findings

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    return float(f1)


def evaluate_chexpert() -> Tuple[pd.DataFrame, pd.DataFrame]:
    for p in [PERTURBATIONS_PATH, BASELINE_PATH, GATED_PATH]:
        if not p.exists():
            raise FileNotFoundError(f"Required file missing: {p}")

    pert_df = pd.read_csv(PERTURBATIONS_PATH)
    base_df = pd.read_csv(BASELINE_PATH)
    gated_df = pd.read_csv(GATED_PATH)

    base_lookup = {
        (str(r["sample_id"]), str(r["condition"])): str(r["generated_report"])
        for _, r in base_df.iterrows()
    }
    gated_lookup = {
        (str(r["sample_id"]), str(r["condition"])): str(r["gated_report"])
        for _, r in gated_df.iterrows()
    }

    results_rows = []

    for _, row in pert_df.iterrows():
        sid = str(row["sample_id"])
        cond = str(row["condition"])

        rf = str(row["reference_findings"]) if pd.notna(row["reference_findings"]) else ""
        ri = str(row["reference_impression"]) if pd.notna(row["reference_impression"]) else ""
        ref_text = f"{rf} {ri}".strip()

        base_report = base_lookup[(sid, cond)]
        gated_report = gated_lookup[(sid, cond)]

        ref_vec = extract_chexpert_vector(ref_text)
        base_vec = extract_chexpert_vector(base_report)
        gated_vec = extract_chexpert_vector(gated_report)

        b_f1 = compute_chexpert_f1(ref_vec, base_vec)
        g_f1 = compute_chexpert_f1(ref_vec, gated_vec)
        delta_f1 = g_f1 - b_f1

        # Format label vectors as compact string representations for auditability
        ref_vec_str = str({k: (v if pd.notna(v) else None) for k, v in ref_vec.items()})
        base_vec_str = str({k: (v if pd.notna(v) else None) for k, v in base_vec.items()})
        gated_vec_str = str({k: (v if pd.notna(v) else None) for k, v in gated_vec.items()})

        results_rows.append(
            {
                "sample_id": sid,
                "condition": cond,
                "baseline_chexpert_f1": round(b_f1, 4),
                "gated_chexpert_f1": round(g_f1, 4),
                "delta_chexpert_f1": round(delta_f1, 4),
                "reference_chexpert_vector": ref_vec_str,
                "baseline_chexpert_vector": base_vec_str,
                "gated_chexpert_vector": gated_vec_str,
            }
        )

    results_df = pd.DataFrame(results_rows)

    # Summary table
    summary_rows = []
    subsets = [("overall", results_df)] + [
        (c, results_df[results_df["condition"] == c]) for c in REQUIRED_CONDITIONS
    ]

    for scope, subset in subsets:
        n = len(subset)
        summary_rows.append(
            {
                "condition": scope,
                "n_records": n,
                "mean_baseline_chexpert_f1": round(float(subset["baseline_chexpert_f1"].mean()), 4),
                "mean_gated_chexpert_f1": round(float(subset["gated_chexpert_f1"].mean()), 4),
                "mean_delta_chexpert_f1": round(float(subset["delta_chexpert_f1"].mean()), 4),
            }
        )

    summary_df = pd.DataFrame(summary_rows)
    return results_df, summary_df


def main() -> None:
    print("=" * 70)
    print("CHEXPERT-F1 EVALUATION")
    print("=" * 70)

    results_df, summary_df = evaluate_chexpert()

    RESULTS_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    results_df.to_csv(RESULTS_OUTPUT_PATH, index=False)
    summary_df.to_csv(SUMMARY_OUTPUT_PATH, index=False)

    print(f"Results saved to: {RESULTS_OUTPUT_PATH}")
    print(f"Summary saved to: {SUMMARY_OUTPUT_PATH}\n")
    print(summary_df.to_string(index=False))


if __name__ == "__main__":
    main()

In [ ]:
import importlib.util

print(
    "radgraph installed:",
    importlib.util.find_spec("radgraph") is not None
)

radgraph installed: False

In [ ]:
import sys
import torch
import transformers
import importlib.util

print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("CUDA available:", torch.cuda.is_available())

print("\nRelevant packages:")
for package in [
    "radgraph",
    "torch",
    "transformers",
    "spacy",
    "nltk",
    "numpy",
    "pandas",
]:
    spec = importlib.util.find_spec(package)
    print(
        f"{package:15s}: "
        f"{'installed' if spec else 'NOT INSTALLED'}"
    )

Python: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
PyTorch: 2.11.0+cu130
Transformers: 4.51.3
CUDA available: True

Relevant packages:
radgraph       : NOT INSTALLED
torch          : installed
transformers   : installed
spacy          : installed
nltk           : installed
numpy          : installed
pandas         : installed

In [ ]:
!pip install radgraph

Collecting radgraph
  Downloading radgraph-0.1.18.tar.gz (587 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.0/588.0 kB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from radgraph) (2.11.0+cu130)
Requirement already satisfied: transformers>=4.39.0 in /usr/local/lib/python3.13/dist-packages (from radgraph) (4.51.3)
Collecting appdirs (from radgraph)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: jsonpickle in /usr/local/lib/python3.13/dist-packages (from radgraph) (4.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from radgraph) (4.0.7)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from radgraph) (3.14.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (from radgraph) (3.9.1)
Collecting dotmap (from radgraph)
  Downloading dotmap-1.3.30-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: pytest in /usr/local/lib/python3.13/dist-packages (from radgraph) (8.4.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (2025.12.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.1.0->radgraph) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.1.0->radgraph) (13.0.85)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.39.0->radgraph) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.39.0->radgraph) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.39.0->radgraph) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.39.0->radgraph) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.39.0->radgraph) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from transformers>=4.39.0->radgraph) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.39.0->radgraph) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.39.0->radgraph) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.39.0->radgraph) (4.67.3)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk->radgraph) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk->radgraph) (1.6.0)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.13/dist-packages (from pytest->radgraph) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.13/dist-packages (from pytest->radgraph) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.13/dist-packages (from pytest->radgraph) (2.21.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.1.0->radgraph) (1.8.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers>=4.39.0->radgraph) (1.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.1.0->radgraph) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.1.0->radgraph) (3.0.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk->radgraph) (3.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->transformers>=4.39.0->radgraph) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->transformers>=4.39.0->radgraph) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->transformers>=4.39.0->radgraph) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->transformers>=4.39.0->radgraph) (2026.7.22)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading dotmap-1.3.30-py3-none-any.whl (11 kB)
Building wheels for collected packages: radgraph
  Building wheel for radgraph (setup.py) ... done
  Created wheel for radgraph: filename=radgraph-0.1.18-py3-none-any.whl size=812682 sha256=838a264ea8a1b91b274ba475bd2002fcc673b2cfc0c3132388c3ba6707aab75c
  Stored in directory: /root/.cache/pip/wheels/2d/2a/49/a9fd7a99361f4d67e884f047d011ac9a619f6f2575ae3c9851
Successfully built radgraph
Installing collected packages: dotmap, appdirs, radgraph
Successfully installed appdirs-1.4.4 dotmap-1.3.30 radgraph-0.1.18

In [ ]:
import radgraph
print("RadGraph imported successfully")

RadGraph imported successfully

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from radgraph import F1RadGraph

print("F1RadGraph imported successfully")
print(F1RadGraph)

F1RadGraph imported successfully
<class 'radgraph.radgraph.F1RadGraph'>

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np
import sys

# ------------------------------------------------------------
# Phase26D paths
# ------------------------------------------------------------
ROOT = Path("/content/Evidence-State-Radiology")

GEN_PATH = (
    ROOT
    / "results/maira2_contrastive/phase26d_evaluation"
    / "phase26d_evaluation_generation.csv"
)

BENCH_PATH = (
    ROOT
    / "results/tables/phase16_perturbations.csv"
)

OUT_DIR = ROOT / "results/tables/phase26d_metrics"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Load generation results
# ------------------------------------------------------------
generation_df = pd.read_csv(GEN_PATH)
benchmark_df = pd.read_csv(BENCH_PATH)

print("Generation shape:", generation_df.shape)
print("Benchmark shape:", benchmark_df.shape)

print("\nGeneration columns:")
print(generation_df.columns.tolist())

print("\nBenchmark columns:")
print(benchmark_df.columns.tolist())

Generation shape: (960, 14)
Benchmark shape: (600, 20)

Generation columns:
['sample_id', 'uid', 'condition', 'evidence_state', 'perturbed_context', 'frontal_image', 'findings', 'impression', 'lambda', 'report', 'num_tokens', 'runtime_seconds', 'status', 'error']

Benchmark columns:
['sample_id', 'uid', 'condition', 'evidence_state', 'original_context', 'perturbed_context', 'frontal_image', 'lateral_image', 'findings', 'impression', 'comparison', 'source_context_uid', 'source_context_sample_id', 'removed_evidence_text', 'evidentiary_incomplete_method', 'conflict_target', 'conflict_method', 'conflict_source_text', 'generation_status', 'generation_failure_reason']

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
# ------------------------------------------------------------
# Phase26D: Build evaluation reference table
# ------------------------------------------------------------

# Evaluation studies are the studies appearing in the generated
# Phase26D evaluation outputs.
eval_uids = sorted(generation_df["uid"].dropna().unique())

print("Evaluation studies:", len(eval_uids))

# ------------------------------------------------------------
# Reference source
# One stable clinical reference per study.
# Use findings + impression from the frozen benchmark.
# ------------------------------------------------------------

reference_df = (
    benchmark_df[
        benchmark_df["uid"].isin(eval_uids)
    ][
        ["uid", "findings", "impression"]
    ]
    .drop_duplicates(subset=["uid"])
    .copy()
)

# Construct the same reference text for RadGraph as the
# existing Phase20 implementation:
# findings + impression.
reference_df["reference_text"] = (
    reference_df["findings"]
    .fillna("")
    .astype(str)
    .str.strip()
    + "\n"
    + reference_df["impression"]
    .fillna("")
    .astype(str)
    .str.strip()
).str.strip()

# ------------------------------------------------------------
# Audit
# ------------------------------------------------------------

print("Reference studies:", len(reference_df))
print(
    "Reference text empty:",
    (reference_df["reference_text"].str.len() == 0).sum()
)

print(
    "Duplicate reference UIDs:",
    reference_df["uid"].duplicated().sum()
)

missing_refs = sorted(
    set(eval_uids) - set(reference_df["uid"])
)

print("Missing evaluation references:", missing_refs)

print("\nReference length statistics:")
print(
    reference_df["reference_text"]
    .str.len()
    .describe()
)

# ------------------------------------------------------------
# Verify every generated record has a reference
# ------------------------------------------------------------

generation_with_ref = generation_df.merge(
    reference_df[["uid", "reference_text"]],
    on="uid",
    how="left",
    validate="many_to_one",
)

print("\nGeneration + reference shape:", generation_with_ref.shape)

print(
    "Generated rows without reference:",
    generation_with_ref["reference_text"].isna().sum()
)

print(
    "Unique generated reports:",
    generation_with_ref["report"].nunique()
)

# ------------------------------------------------------------
# Final structural audit
# ------------------------------------------------------------

expected_per_lambda = 480

print("\nLambda counts:")
print(generation_with_ref["lambda"].value_counts().sort_index())

print("\nCondition counts:")
print(generation_with_ref["condition"].value_counts().sort_index())

print("\nCondition × lambda:")
print(
    generation_with_ref
    .groupby(["condition", "lambda"])
    .size()
    .unstack(fill_value=0)
)

assert len(eval_uids) == 80
assert len(reference_df) == 80
assert generation_with_ref["reference_text"].notna().all()
assert generation_with_ref["lambda"].value_counts().to_dict() == {
    0.00: 480,
    0.25: 480,
}

print("\nREFERENCE AUDIT: PASS")

Evaluation studies: 80
Reference studies: 80
Reference text empty: 0
Duplicate reference UIDs: 0
Missing evaluation references: []

Reference length statistics:
count      80.000000
mean      338.462500
std       183.826552
min        91.000000
25%       215.000000
50%       272.500000
75%       436.000000
max      1065.000000
Name: reference_text, dtype: float64

Generation + reference shape: (960, 15)
Generated rows without reference: 0
Unique generated reports: 622

Lambda counts:
lambda
0.00    480
0.25    480
Name: count, dtype: int64

Condition counts:
condition
conflicting               160
evidentiary_incomplete    160
insufficient              160
irrelevant                160
sufficient                160
syntactic_incomplete      160
Name: count, dtype: int64

Condition × lambda:
lambda                  0.00  0.25
condition
conflicting               80    80
evidentiary_incomplete    80    80
insufficient              80    80
irrelevant                80    80
sufficient                80    80
syntactic_incomplete      80    80

REFERENCE AUDIT: PASS

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from radgraph import F1RadGraph
import pandas as pd
import numpy as np
from pathlib import Path
import time

# ------------------------------------------------------------
# Phase26D RadGraph evaluation
# ------------------------------------------------------------

OUT_DIR = ROOT / "results/tables/phase26d_metrics"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Make sure reports are valid strings.
radgraph_input = generation_with_ref[
    [
        "sample_id",
        "uid",
        "condition",
        "lambda",
        "report",
        "reference_text",
    ]
].copy()

radgraph_input["report"] = (
    radgraph_input["report"]
    .fillna("")
    .astype(str)
)

radgraph_input["reference_text"] = (
    radgraph_input["reference_text"]
    .fillna("")
    .astype(str)
)

assert len(radgraph_input) == 960
assert radgraph_input["report"].str.len().gt(0).all()

# ------------------------------------------------------------
# Initialize RadGraph once
# ------------------------------------------------------------

print("Initializing F1RadGraph...")
start_init = time.time()

radgraph_metric = F1RadGraph(
    reward_level="all",
    batch_size=8,
)

print(
    f"RadGraph initialized in "
    f"{time.time() - start_init:.2f} seconds"
)

# ------------------------------------------------------------
# Evaluate each lambda separately
# ------------------------------------------------------------

all_results = []

for lambda_value in sorted(radgraph_input["lambda"].unique()):

    subset = (
        radgraph_input[
            radgraph_input["lambda"] == lambda_value
        ]
        .copy()
        .reset_index(drop=True)
    )

    print(
        f"\nRunning RadGraph for lambda={lambda_value:.2f} "
        f"({len(subset)} records)..."
    )

    references = subset["reference_text"].tolist()
    hypotheses = subset["report"].tolist()

    start = time.time()

    scores = radgraph_metric(
        refs=references,
        hyps=hypotheses,
    )

    elapsed = time.time() - start

    print(
        f"Completed lambda={lambda_value:.2f} "
        f"in {elapsed:.2f} seconds"
    )

    # --------------------------------------------------------
    # Inspect returned structure before assigning
    # --------------------------------------------------------

    print("Returned object type:", type(scores))

    if isinstance(scores, dict):
        print("Returned keys:", scores.keys())

    # --------------------------------------------------------
    # Existing F1RadGraph returns a dictionary containing
    # precision / recall / f1_score lists.
    # --------------------------------------------------------

    precision = scores["precision"]
    recall = scores["recall"]
    f1 = scores["f1_score"]

    assert len(precision) == len(subset)
    assert len(recall) == len(subset)
    assert len(f1) == len(subset)

    subset["radgraph_precision"] = precision
    subset["radgraph_recall"] = recall
    subset["radgraph_f1"] = f1

    all_results.append(subset)

radgraph_results = pd.concat(
    all_results,
    ignore_index=True,
)

# ------------------------------------------------------------
# Structural audit
# ------------------------------------------------------------

print("\nRadGraph result shape:", radgraph_results.shape)

print("\nLambda counts:")
print(
    radgraph_results["lambda"]
    .value_counts()
    .sort_index()
)

print("\nCondition counts:")
print(
    radgraph_results["condition"]
    .value_counts()
    .sort_index()
)

print("\nNaN counts:")
print(
    radgraph_results[
        [
            "radgraph_precision",
            "radgraph_recall",
            "radgraph_f1",
        ]
    ].isna().sum()
)

print("\nOverall RadGraph means:")
print(
    radgraph_results
    .groupby("lambda")[
        [
            "radgraph_precision",
            "radgraph_recall",
            "radgraph_f1",
        ]
    ]
    .mean()
)

print("\nOverall RadGraph medians:")
print(
    radgraph_results
    .groupby("lambda")[
        [
            "radgraph_precision",
            "radgraph_recall",
            "radgraph_f1",
        ]
    ]
    .median()
)

# ------------------------------------------------------------
# Save record-level results
# ------------------------------------------------------------

RADGRAPH_RECORD_PATH = (
    OUT_DIR / "phase26d_evaluation_radgraph.csv"
)

radgraph_results.to_csv(
    RADGRAPH_RECORD_PATH,
    index=False,
)

print(
    "\nSaved:",
    RADGRAPH_RECORD_PATH
)

assert len(radgraph_results) == 960
assert radgraph_results["radgraph_f1"].notna().all()

print("\nRADGRAPH RECORD-LEVEL AUDIT: PASS")

Initializing F1RadGraph...
Using device: cuda:0
model_type not provided, defaulting to radgraph-xl

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

radgraph-xl.tar.gz:   0%|          | 0.00/416M [00:00<?, ?B/s]

/usr/local/lib/python3.13/dist-packages/huggingface_hub/file_download.py:1727: DeprecationWarning: hf_xet.download_files() is deprecated. Use XetSession().new_file_download_group().start_download_file() instead.
  xet_get(
/usr/local/lib/python3.13/dist-packages/radgraph/radgraph.py:105: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=model_dir)

tokenizer_config.json:   0%|          | 0.00/228 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

RadGraph initialized in 30.22 seconds

Running RadGraph for lambda=0.00 (480 records)...
Completed lambda=0.00 in 28.49 seconds
Returned object type: <class 'tuple'>

TypeError: tuple indices must be integers or slices, not str

In [ ]:
print("Type:", type(scores))
print("Tuple length:", len(scores))

for i, item in enumerate(scores):
    print(f"\nItem {i}:")
    print("  type:", type(item))

    if hasattr(item, "shape"):
        print("  shape:", item.shape)

    if isinstance(item, (list, tuple)):
        print("  length:", len(item))
        print("  first item:", item[0] if len(item) > 0 else None)

    elif isinstance(item, dict):
        print("  keys:", item.keys())

    else:
        print("  value:", item)

Type: <class 'tuple'>
Tuple length: 4

Item 0:
  type: <class 'tuple'>
  length: 3
  first item: 0.1881163061476282

Item 1:
  type: <class 'tuple'>
  length: 3
  first item: [0.0, 0.14814814814814817, 0.15384615384615385, 0.0, 0.06250000000000001, 0.24242424242424243, 0.0, 0.22641509433962262, 0.3846153846153846, 0.18181818181818182, 0.37037037037037035, 0.24999999999999994, 0.14285714285714285, 0.13793103448275862, 0.2962962962962963, 0.14634146341463414, 0.12500000000000003, 0.3125, 0.15384615384615385, 0.13793103448275862, 0.11764705882352941, 0.0, 0.2, 0.1702127659574468, 0.052631578947368425, 0.2564102564102564, 0.0625, 0.1111111111111111, 0.1111111111111111, 0.09523809523809523, 0.14285714285714285, 0.18181818181818182, 0.30769230769230765, 0.05405405405405406, 0.28571428571428575, 0.16216216216216214, 0.0, 0.18181818181818182, 0.058823529411764705, 0.1111111111111111, 0.30303030303030304, 0.2857142857142857, 0.21276595744680848, 0.2380952380952381, 0.30303030303030304, 0.10526315789473685, 0.28571428571428575, 0.2285714285714286, 0.45714285714285713, 0.18518518518518515, 0.37037037037037035, 0.19999999999999998, 0.32, 0.3448275862068966, 0.29166666666666663, 0.2926829268292683, 0.04545454545454546, 0.13333333333333333, 0.052631578947368425, 0.0, 0.23076923076923078, 0.09302325581395349, 0.0, 0.0, 0.15789473684210525, 0.18181818181818182, 0.26666666666666666, 0.22222222222222218, 0.06666666666666667, 0.3, 0.18181818181818182, 0.08695652173913043, 0.3, 0.0, 0.0, 0.13636363636363638, 0.15384615384615383, 0.17142857142857143, 0.18181818181818182, 0.14285714285714285, 0.18181818181818185, 0.0, 0.4, 0.2857142857142857, 0.0, 0.3111111111111111, 0.0, 0.3846153846153846, 0.3448275862068966, 0.22222222222222224, 0.13333333333333333, 0.0, 0.4166666666666667, 0.2962962962962963, 0.3448275862068966, 0.0, 0.0, 0.0, 0.0, 0.0, 0.39999999999999997, 0.3333333333333333, 0.6153846153846153, 0.4444444444444444, 0.43902439024390244, 0.0, 0.0, 0.0, 0.08888888888888888, 0.08888888888888888, 0.28571428571428575, 0.0, 0.125, 0.22857142857142856, 0.2631578947368421, 0.0, 0.10256410256410256, 0.11320754716981131, 0.1851851851851852, 0.1568627450980392, 0.27586206896551724, 0.0, 0.14285714285714285, 0.27586206896551724, 0.2222222222222222, 0.18181818181818182, 0.0, 0.22222222222222224, 0.22222222222222224, 0.19047619047619047, 0.31999999999999995, 0.3870967741935484, 0.33333333333333337, 0.31999999999999995, 0.43749999999999994, 0.2105263157894737, 0.0, 0.19999999999999998, 0.0, 0.0, 0.5, 0.0, 0.43243243243243246, 0.0, 0.0, 0.3870967741935484, 0.0, 0.13793103448275862, 0.23076923076923078, 0.26666666666666666, 0.5714285714285714, 0.0, 0.1111111111111111, 0.18749999999999997, 0.22222222222222218, 0.30769230769230765, 0.14634146341463414, 0.20408163265306123, 0.28, 0.28, 0.10810810810810811, 0.0, 0.16666666666666663, 0.0, 0.0, 0.1875, 0.2380952380952381, 0.3, 0.2105263157894737, 0.1875, 0.2641509433962264, 0.08, 0.2545454545454545, 0.10714285714285716, 0.19230769230769232, 0.07692307692307693, 0.0, 0.0, 0.0, 0.0, 0.2702702702702703, 0.06896551724137932, 0.3157894736842105, 0.30769230769230765, 0.30769230769230765, 0.0, 0.0, 0.12903225806451613, 0.14285714285714288, 0.0, 0.1111111111111111, 0.05555555555555555, 0.17647058823529413, 0.058823529411764705, 0.1, 0.32653061224489793, 0.0, 0.20833333333333331, 0.3137254901960784, 0.24000000000000002, 0.17142857142857143, 0.06451612903225806, 0.20512820512820512, 0.2702702702702703, 0.2702702702702703, 0.2222222222222222, 0.0, 0.27450980392156865, 0.3529411764705882, 0.4571428571428571, 0.30769230769230765, 0.0, 0.07407407407407408, 0.2857142857142857, 0.35714285714285715, 0.3, 0.0, 0.4571428571428572, 0.3783783783783784, 0.4242424242424242, 0.10526315789473685, 0.038461538461538464, 0.16666666666666666, 0.09375000000000001, 0.037037037037037035, 0.18181818181818182, 0.0, 0.2608695652173913, 0.16, 0.14285714285714285, 0.4, 0.0, 0.14814814814814814, 0.3870967741935484, 0.3870967741935484, 0.21052631578947364, 0.06060606060606061, 0.13953488372093023, 0.2702702702702703, 0.32558139534883723, 0.19999999999999998, 0.0, 0.11764705882352941, 0.07407407407407407, 0.07407407407407407, 0.30434782608695654, 0.05714285714285714, 0.14634146341463417, 0.11428571428571428, 0.1111111111111111, 0.5333333333333333, 0.0, 0.4736842105263158, 0.12121212121212123, 0.12121212121212123, 0.3888888888888889, 0.06896551724137931, 0.3, 0.4, 0.4864864864864865, 0.03773584905660377, 0.0, 0.037037037037037035, 0.2807017543859649, 0.14814814814814814, 0.2727272727272727, 0.2857142857142857, 0.31250000000000006, 0.2727272727272727, 0.39999999999999997, 0.4, 0.0, 0.12121212121212123, 0.4, 0.4, 0.21276595744680854, 0.0, 0.44897959183673464, 0.3783783783783784, 0.05128205128205128, 0.3157894736842105, 0.14814814814814814, 0.391304347826087, 0.2, 0.05405405405405406, 0.3571428571428571, 0.0, 0.0, 0.2857142857142857, 0.0, 0.35, 0.058823529411764705, 0.14285714285714288, 0.36363636363636365, 0.13953488372093023, 0.2926829268292683, 0.12121212121212122, 0.17142857142857143, 0.05263157894736841, 0.2285714285714286, 0.6046511627906977, 0.16666666666666666, 0.31249999999999994, 0.5263157894736842, 0.5263157894736842, 0.044444444444444446, 0.20512820512820512, 0.12244897959183673, 0.09523809523809526, 0.052631578947368425, 0.38461538461538464, 0.0, 0.14285714285714288, 0.25, 0.14285714285714288, 0.4210526315789474, 0.0, 0.2222222222222222, 0.4186046511627907, 0.2926829268292683, 0.17647058823529413, 0.08695652173913043, 0.32558139534883723, 0.17647058823529413, 0.2580645161290323, 0.14545454545454545, 0.04444444444444444, 0.22641509433962265, 0.24615384615384617, 0.13793103448275862, 0.48275862068965514, 0.37499999999999994, 0.48275862068965514, 0.48275862068965514, 0.48275862068965514, 0.22857142857142856, 0.0, 0.21739130434782608, 0.3448275862068966, 0.3448275862068966, 0.16666666666666669, 0.0, 0.23076923076923075, 0.19999999999999998, 0.0, 0.3333333333333333, 0.0, 0.4166666666666667, 0.35714285714285715, 0.21428571428571427, 0.10714285714285714, 0.046511627906976744, 0.21428571428571427, 0.14814814814814814, 0.16, 0.3414634146341463, 0.1111111111111111, 0.2285714285714286, 0.2105263157894737, 0.15789473684210525, 0.3, 0.0, 0.24242424242424246, 0.2777777777777778, 0.2564102564102564, 0.2285714285714286, 0.18181818181818182, 0.28571428571428575, 0.3333333333333333, 0.3333333333333333, 0.2380952380952381, 0.19512195121951217, 0.22727272727272727, 0.19047619047619052, 0.23255813953488372, 0.27586206896551724, 0.0, 0.13793103448275862, 0.25, 0.0, 0.0, 0.09523809523809525, 0.2, 0.0, 0.0, 0.3181818181818182, 0.0, 0.34782608695652173, 0.22222222222222224, 0.23255813953488372, 0.0, 0.06896551724137932, 0.22222222222222224, 0.0, 0.07692307692307691, 0.0, 0.0, 0.3703703703703703, 0.0, 0.0, 0.046511627906976744, 0.0, 0.10526315789473682, 0.05, 0.0, 0.13953488372093023, 0.0, 0.13953488372093023, 0.13953488372093023, 0.13953488372093023, 0.6153846153846153, 0.0, 0.26666666666666666, 0.3888888888888889, 0.3225806451612903, 0.3448275862068966, 0.0, 0.13333333333333333, 0.3448275862068966, 0.3448275862068966, 0.06060606060606061, 0.06666666666666667, 0.42424242424242425, 0.24242424242424243, 0.24242424242424243, 0.23076923076923075, 0.0, 0.10000000000000002, 0.11111111111111112, 0.08333333333333333, 0.2777777777777778, 0.17142857142857143, 0.14285714285714285, 0.19354838709677416, 0.27027027027027023, 0.07142857142857144, 0.0, 0.07692307692307693, 0.06451612903225808, 0.06451612903225808, 0.35714285714285715, 0.3636363636363636, 0.28571428571428575, 0.25, 0.19999999999999998, 0.06666666666666667, 0.0, 0.0, 0.0625, 0.06896551724137931, 0.4, 0.0, 0.0, 0.32, 0.0, 0.27906976744186046, 0.0, 0.17777777777777776, 0.25, 0.18604651162790697, 0.3157894736842105, 0.0, 0.5882352941176471, 0.5882352941176471, 0.17391304347826086, 0.30769230769230765, 0.0, 0.23076923076923078, 0.5, 0.2857142857142857, 0.2545454545454546, 0.0, 0.0, 0.2962962962962963, 0.163265306122449, 0.5454545454545454, 0.0, 0.5217391304347826, 0.20000000000000004, 0.2727272727272727]

Item 2:
  type: <class 'list'>
  length: 480
  first item: {'text': 'No active infiltrate , mass or effusion is seen . Diaphragm , dorsal spine and overlying soft tissues are satisfactory .', 'entities': {'1': {'tokens': 'active', 'label': 'Observation::definitely absent', 'start_ix': 1, 'end_ix': 1, 'relations': [['modify', '2']]}, '2': {'tokens': 'infiltrate', 'label': 'Observation::definitely absent', 'start_ix': 2, 'end_ix': 2, 'relations': []}, '3': {'tokens': 'mass', 'label': 'Observation::definitely absent', 'start_ix': 4, 'end_ix': 4, 'relations': []}, '4': {'tokens': 'effusion', 'label': 'Observation::definitely absent', 'start_ix': 6, 'end_ix': 6, 'relations': []}, '5': {'tokens': 'Diaphragm', 'label': 'Anatomy::definitely present', 'start_ix': 10, 'end_ix': 10, 'relations': []}, '6': {'tokens': 'dorsal', 'label': 'Anatomy::definitely present', 'start_ix': 12, 'end_ix': 12, 'relations': [['modify', '7']]}, '7': {'tokens': 'spine', 'label': 'Anatomy::definitely present', 'start_ix': 13, 'end_ix': 13, 'relations': []}, '8': {'tokens': 'soft tissues', 'label': 'Anatomy::definitely present', 'start_ix': 16, 'end_ix': 17, 'relations': []}, '9': {'tokens': 'satisfactory', 'label': 'Observation::definitely present', 'start_ix': 19, 'end_ix': 19, 'relations': [['located_at', '5'], ['located_at', '7'], ['located_at', '8']]}}, 'data_source': None, 'data_split': 'inference'}

Item 3:
  type: <class 'list'>
  length: 480
  first item: {'text': 'The heart is normal in size . The mediastinum is unremarkable . Mild blunting of right costophrenic XXXX . The lungs are otherwise grossly clear . No acute disease .', 'entities': {'1': {'tokens': 'heart', 'label': 'Anatomy::definitely present', 'start_ix': 1, 'end_ix': 1, 'relations': []}, '2': {'tokens': 'normal', 'label': 'Observation::definitely present', 'start_ix': 3, 'end_ix': 3, 'relations': [['located_at', '1']]}, '3': {'tokens': 'size', 'label': 'Anatomy::definitely present', 'start_ix': 5, 'end_ix': 5, 'relations': [['modify', '1']]}, '4': {'tokens': 'mediastinum', 'label': 'Anatomy::definitely present', 'start_ix': 8, 'end_ix': 8, 'relations': []}, '5': {'tokens': 'unremarkable', 'label': 'Observation::definitely present', 'start_ix': 10, 'end_ix': 10, 'relations': [['located_at', '4']]}, '6': {'tokens': 'Mild', 'label': 'Observation::definitely present', 'start_ix': 12, 'end_ix': 12, 'relations': [['modify', '7']]}, '7': {'tokens': 'blunting', 'label': 'Observation::definitely present', 'start_ix': 13, 'end_ix': 13, 'relations': [['located_at', '9']]}, '8': {'tokens': 'right', 'label': 'Anatomy::definitely present', 'start_ix': 15, 'end_ix': 15, 'relations': [['modify', '9']]}, '9': {'tokens': 'costophrenic', 'label': 'Anatomy::definitely present', 'start_ix': 16, 'end_ix': 16, 'relations': []}, '10': {'tokens': 'XXXX', 'label': 'Observation::definitely present', 'start_ix': 17, 'end_ix': 17, 'relations': [['modify', '9']]}, '11': {'tokens': 'lungs', 'label': 'Anatomy::definitely present', 'start_ix': 20, 'end_ix': 20, 'relations': []}, '12': {'tokens': 'clear', 'label': 'Observation::definitely present', 'start_ix': 24, 'end_ix': 24, 'relations': [['located_at', '11']]}, '13': {'tokens': 'acute disease', 'label': 'Observation::definitely absent', 'start_ix': 27, 'end_ix': 28, 'relations': []}}, 'data_source': None, 'data_split': 'inference'}

In [ ]:
# Inspect the first per-record RadGraph score only.
# No model inference is performed here.

print("Aggregate score:", scores[0])

print("\nFirst per-record score:")
print(scores[1][0])

print("\nType:")
print(type(scores[1][0]))

print("\nLength:")
print(len(scores[1][0]))

print("\nParsed hypothesis keys:")
print(scores[2][0].keys())

print("\nParsed reference keys:")
print(scores[3][0].keys())

Aggregate score: (np.float64(0.1881163061476282), np.float64(0.1657536190510923), np.float64(0.11823509276005441))

First per-record score:
[0.0, 0.14814814814814817, 0.15384615384615385, 0.0, 0.06250000000000001, 0.24242424242424243, 0.0, 0.22641509433962262, 0.3846153846153846, 0.18181818181818182, 0.37037037037037035, 0.24999999999999994, 0.14285714285714285, 0.13793103448275862, 0.2962962962962963, 0.14634146341463414, 0.12500000000000003, 0.3125, 0.15384615384615385, 0.13793103448275862, 0.11764705882352941, 0.0, 0.2, 0.1702127659574468, 0.052631578947368425, 0.2564102564102564, 0.0625, 0.1111111111111111, 0.1111111111111111, 0.09523809523809523, 0.14285714285714285, 0.18181818181818182, 0.30769230769230765, 0.05405405405405406, 0.28571428571428575, 0.16216216216216214, 0.0, 0.18181818181818182, 0.058823529411764705, 0.1111111111111111, 0.30303030303030304, 0.2857142857142857, 0.21276595744680848, 0.2380952380952381, 0.30303030303030304, 0.10526315789473685, 0.28571428571428575, 0.2285714285714286, 0.45714285714285713, 0.18518518518518515, 0.37037037037037035, 0.19999999999999998, 0.32, 0.3448275862068966, 0.29166666666666663, 0.2926829268292683, 0.04545454545454546, 0.13333333333333333, 0.052631578947368425, 0.0, 0.23076923076923078, 0.09302325581395349, 0.0, 0.0, 0.15789473684210525, 0.18181818181818182, 0.26666666666666666, 0.22222222222222218, 0.06666666666666667, 0.3, 0.18181818181818182, 0.08695652173913043, 0.3, 0.0, 0.0, 0.13636363636363638, 0.15384615384615383, 0.17142857142857143, 0.18181818181818182, 0.14285714285714285, 0.18181818181818185, 0.0, 0.4, 0.2857142857142857, 0.0, 0.3111111111111111, 0.0, 0.3846153846153846, 0.3448275862068966, 0.22222222222222224, 0.13333333333333333, 0.0, 0.4166666666666667, 0.2962962962962963, 0.3448275862068966, 0.0, 0.0, 0.0, 0.0, 0.0, 0.39999999999999997, 0.3333333333333333, 0.6153846153846153, 0.4444444444444444, 0.43902439024390244, 0.0, 0.0, 0.0, 0.08888888888888888, 0.08888888888888888, 0.28571428571428575, 0.0, 0.125, 0.22857142857142856, 0.2631578947368421, 0.0, 0.10256410256410256, 0.11320754716981131, 0.1851851851851852, 0.1568627450980392, 0.27586206896551724, 0.0, 0.14285714285714285, 0.27586206896551724, 0.2222222222222222, 0.18181818181818182, 0.0, 0.22222222222222224, 0.22222222222222224, 0.19047619047619047, 0.31999999999999995, 0.3870967741935484, 0.33333333333333337, 0.31999999999999995, 0.43749999999999994, 0.2105263157894737, 0.0, 0.19999999999999998, 0.0, 0.0, 0.5, 0.0, 0.43243243243243246, 0.0, 0.0, 0.3870967741935484, 0.0, 0.13793103448275862, 0.23076923076923078, 0.26666666666666666, 0.5714285714285714, 0.0, 0.1111111111111111, 0.18749999999999997, 0.22222222222222218, 0.30769230769230765, 0.14634146341463414, 0.20408163265306123, 0.28, 0.28, 0.10810810810810811, 0.0, 0.16666666666666663, 0.0, 0.0, 0.1875, 0.2380952380952381, 0.3, 0.2105263157894737, 0.1875, 0.2641509433962264, 0.08, 0.2545454545454545, 0.10714285714285716, 0.19230769230769232, 0.07692307692307693, 0.0, 0.0, 0.0, 0.0, 0.2702702702702703, 0.06896551724137932, 0.3157894736842105, 0.30769230769230765, 0.30769230769230765, 0.0, 0.0, 0.12903225806451613, 0.14285714285714288, 0.0, 0.1111111111111111, 0.05555555555555555, 0.17647058823529413, 0.058823529411764705, 0.1, 0.32653061224489793, 0.0, 0.20833333333333331, 0.3137254901960784, 0.24000000000000002, 0.17142857142857143, 0.06451612903225806, 0.20512820512820512, 0.2702702702702703, 0.2702702702702703, 0.2222222222222222, 0.0, 0.27450980392156865, 0.3529411764705882, 0.4571428571428571, 0.30769230769230765, 0.0, 0.07407407407407408, 0.2857142857142857, 0.35714285714285715, 0.3, 0.0, 0.4571428571428572, 0.3783783783783784, 0.4242424242424242, 0.10526315789473685, 0.038461538461538464, 0.16666666666666666, 0.09375000000000001, 0.037037037037037035, 0.18181818181818182, 0.0, 0.2608695652173913, 0.16, 0.14285714285714285, 0.4, 0.0, 0.14814814814814814, 0.3870967741935484, 0.3870967741935484, 0.21052631578947364, 0.06060606060606061, 0.13953488372093023, 0.2702702702702703, 0.32558139534883723, 0.19999999999999998, 0.0, 0.11764705882352941, 0.07407407407407407, 0.07407407407407407, 0.30434782608695654, 0.05714285714285714, 0.14634146341463417, 0.11428571428571428, 0.1111111111111111, 0.5333333333333333, 0.0, 0.4736842105263158, 0.12121212121212123, 0.12121212121212123, 0.3888888888888889, 0.06896551724137931, 0.3, 0.4, 0.4864864864864865, 0.03773584905660377, 0.0, 0.037037037037037035, 0.2807017543859649, 0.14814814814814814, 0.2727272727272727, 0.2857142857142857, 0.31250000000000006, 0.2727272727272727, 0.39999999999999997, 0.4, 0.0, 0.12121212121212123, 0.4, 0.4, 0.21276595744680854, 0.0, 0.44897959183673464, 0.3783783783783784, 0.05128205128205128, 0.3157894736842105, 0.14814814814814814, 0.391304347826087, 0.2, 0.05405405405405406, 0.3571428571428571, 0.0, 0.0, 0.2857142857142857, 0.0, 0.35, 0.058823529411764705, 0.14285714285714288, 0.36363636363636365, 0.13953488372093023, 0.2926829268292683, 0.12121212121212122, 0.17142857142857143, 0.05263157894736841, 0.2285714285714286, 0.6046511627906977, 0.16666666666666666, 0.31249999999999994, 0.5263157894736842, 0.5263157894736842, 0.044444444444444446, 0.20512820512820512, 0.12244897959183673, 0.09523809523809526, 0.052631578947368425, 0.38461538461538464, 0.0, 0.14285714285714288, 0.25, 0.14285714285714288, 0.4210526315789474, 0.0, 0.2222222222222222, 0.4186046511627907, 0.2926829268292683, 0.17647058823529413, 0.08695652173913043, 0.32558139534883723, 0.17647058823529413, 0.2580645161290323, 0.14545454545454545, 0.04444444444444444, 0.22641509433962265, 0.24615384615384617, 0.13793103448275862, 0.48275862068965514, 0.37499999999999994, 0.48275862068965514, 0.48275862068965514, 0.48275862068965514, 0.22857142857142856, 0.0, 0.21739130434782608, 0.3448275862068966, 0.3448275862068966, 0.16666666666666669, 0.0, 0.23076923076923075, 0.19999999999999998, 0.0, 0.3333333333333333, 0.0, 0.4166666666666667, 0.35714285714285715, 0.21428571428571427, 0.10714285714285714, 0.046511627906976744, 0.21428571428571427, 0.14814814814814814, 0.16, 0.3414634146341463, 0.1111111111111111, 0.2285714285714286, 0.2105263157894737, 0.15789473684210525, 0.3, 0.0, 0.24242424242424246, 0.2777777777777778, 0.2564102564102564, 0.2285714285714286, 0.18181818181818182, 0.28571428571428575, 0.3333333333333333, 0.3333333333333333, 0.2380952380952381, 0.19512195121951217, 0.22727272727272727, 0.19047619047619052, 0.23255813953488372, 0.27586206896551724, 0.0, 0.13793103448275862, 0.25, 0.0, 0.0, 0.09523809523809525, 0.2, 0.0, 0.0, 0.3181818181818182, 0.0, 0.34782608695652173, 0.22222222222222224, 0.23255813953488372, 0.0, 0.06896551724137932, 0.22222222222222224, 0.0, 0.07692307692307691, 0.0, 0.0, 0.3703703703703703, 0.0, 0.0, 0.046511627906976744, 0.0, 0.10526315789473682, 0.05, 0.0, 0.13953488372093023, 0.0, 0.13953488372093023, 0.13953488372093023, 0.13953488372093023, 0.6153846153846153, 0.0, 0.26666666666666666, 0.3888888888888889, 0.3225806451612903, 0.3448275862068966, 0.0, 0.13333333333333333, 0.3448275862068966, 0.3448275862068966, 0.06060606060606061, 0.06666666666666667, 0.42424242424242425, 0.24242424242424243, 0.24242424242424243, 0.23076923076923075, 0.0, 0.10000000000000002, 0.11111111111111112, 0.08333333333333333, 0.2777777777777778, 0.17142857142857143, 0.14285714285714285, 0.19354838709677416, 0.27027027027027023, 0.07142857142857144, 0.0, 0.07692307692307693, 0.06451612903225808, 0.06451612903225808, 0.35714285714285715, 0.3636363636363636, 0.28571428571428575, 0.25, 0.19999999999999998, 0.06666666666666667, 0.0, 0.0, 0.0625, 0.06896551724137931, 0.4, 0.0, 0.0, 0.32, 0.0, 0.27906976744186046, 0.0, 0.17777777777777776, 0.25, 0.18604651162790697, 0.3157894736842105, 0.0, 0.5882352941176471, 0.5882352941176471, 0.17391304347826086, 0.30769230769230765, 0.0, 0.23076923076923078, 0.5, 0.2857142857142857, 0.2545454545454546, 0.0, 0.0, 0.2962962962962963, 0.163265306122449, 0.5454545454545454, 0.0, 0.5217391304347826, 0.20000000000000004, 0.2727272727272727]

Type:
<class 'list'>

Length:
480

Parsed hypothesis keys:
dict_keys(['text', 'entities', 'data_source', 'data_split'])

Parsed reference keys:
dict_keys(['text', 'entities', 'data_source', 'data_split'])

In [ ]:
# ------------------------------------------------------------
# Preserve already-computed lambda=0 RadGraph result
# ------------------------------------------------------------

scores_lambda0 = scores

assert len(scores_lambda0) == 4
assert len(scores_lambda0[1]) == 3

precision0 = scores_lambda0[1][0]
recall0 = scores_lambda0[1][1]
f10 = scores_lambda0[1][2]

assert len(precision0) == 480
assert len(recall0) == 480
assert len(f10) == 480

print("Lambda=0 result preserved.")
print("Aggregate precision:", scores_lambda0[0][0])
print("Aggregate recall:", scores_lambda0[0][1])
print("Aggregate F1:", scores_lambda0[0][2])

print("\nPer-record lengths:")
print("Precision:", len(precision0))
print("Recall:", len(recall0))
print("F1:", len(f10))

# ------------------------------------------------------------
# Run lambda=0.25
# ------------------------------------------------------------

lambda025_df = (
    radgraph_input[
        radgraph_input["lambda"] == 0.25
    ]
    .copy()
    .reset_index(drop=True)
)

assert len(lambda025_df) == 480

print("\nRunning RadGraph for lambda=0.25...")
start = time.time()

scores_lambda025 = radgraph_metric(
    refs=lambda025_df["reference_text"].tolist(),
    hyps=lambda025_df["report"].tolist(),
)

elapsed = time.time() - start

print(f"Completed in {elapsed:.2f} seconds")

# ------------------------------------------------------------
# Validate lambda=0.25 structure
# ------------------------------------------------------------

assert len(scores_lambda025) == 4
assert len(scores_lambda025[1]) == 3

precision025 = scores_lambda025[1][0]
recall025 = scores_lambda025[1][1]
f1025 = scores_lambda025[1][2]

assert len(precision025) == 480
assert len(recall025) == 480
assert len(f1025) == 480

print("\nLambda=0.25 aggregate:")
print("Precision:", scores_lambda025[0][0])
print("Recall:", scores_lambda025[0][1])
print("F1:", scores_lambda025[0][2])

print("\nPer-record lengths:")
print("Precision:", len(precision025))
print("Recall:", len(recall025))
print("F1:", len(f1025))

print("\nRADGRAPH PHASE26D AUDIT: PASS")

Lambda=0 result preserved.
Aggregate precision: 0.1881163061476282
Aggregate recall: 0.1657536190510923
Aggregate F1: 0.11823509276005441

Per-record lengths:
Precision: 480
Recall: 480
F1: 480

Running RadGraph for lambda=0.25...
Completed in 23.54 seconds

Lambda=0.25 aggregate:
Precision: 0.18586658444799517
Recall: 0.16482982886097705
F1: 0.12046682595491279

Per-record lengths:
Precision: 480
Recall: 480
F1: 480

RADGRAPH PHASE26D AUDIT: PASS

In [ ]:
# ============================================================
# Phase26D RadGraph — record-level results and summaries
# ============================================================

from scipy.stats import wilcoxon

RADGRAPH_OUT = (
    ROOT / "results/tables/phase26d_metrics"
)
RADGRAPH_OUT.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Attach scores to the original generation ordering
# ------------------------------------------------------------

lambda0_results = (
    radgraph_input[
        radgraph_input["lambda"] == 0.00
    ]
    .copy()
    .reset_index(drop=True)
)

lambda025_results = (
    radgraph_input[
        radgraph_input["lambda"] == 0.25
    ]
    .copy()
    .reset_index(drop=True)
)

assert len(lambda0_results) == 480
assert len(lambda025_results) == 480

# Scores correspond to the exact ordering supplied to RadGraph.
lambda0_results["radgraph_precision"] = precision0
lambda0_results["radgraph_recall"] = recall0
lambda0_results["radgraph_f1"] = f10

lambda025_results["radgraph_precision"] = precision025
lambda025_results["radgraph_recall"] = recall025
lambda025_results["radgraph_f1"] = f1025

radgraph_results = pd.concat(
    [lambda0_results, lambda025_results],
    ignore_index=True,
)

# ------------------------------------------------------------
# Record-level output
# ------------------------------------------------------------

record_path = (
    RADGRAPH_OUT
    / "phase26d_evaluation_radgraph.csv"
)

radgraph_results.to_csv(
    record_path,
    index=False,
)

# ------------------------------------------------------------
# Overall summary
# ------------------------------------------------------------

overall_summary = (
    radgraph_results
    .groupby("lambda")
    .agg(
        n=("radgraph_f1", "size"),
        precision_mean=("radgraph_precision", "mean"),
        precision_median=("radgraph_precision", "median"),
        recall_mean=("radgraph_recall", "mean"),
        recall_median=("radgraph_recall", "median"),
        f1_mean=("radgraph_f1", "mean"),
        f1_median=("radgraph_f1", "median"),
    )
    .reset_index()
)

overall_path = (
    RADGRAPH_OUT
    / "phase26d_evaluation_radgraph_summary.csv"
)

overall_summary.to_csv(
    overall_path,
    index=False,
)

# ------------------------------------------------------------
# Condition-level summary
# ------------------------------------------------------------

condition_summary = (
    radgraph_results
    .groupby(["condition", "lambda"])
    .agg(
        n=("radgraph_f1", "size"),
        precision_mean=("radgraph_precision", "mean"),
        precision_median=("radgraph_precision", "median"),
        recall_mean=("radgraph_recall", "mean"),
        recall_median=("radgraph_recall", "median"),
        f1_mean=("radgraph_f1", "mean"),
        f1_median=("radgraph_f1", "median"),
    )
    .reset_index()
    .sort_values(["condition", "lambda"])
)

condition_path = (
    RADGRAPH_OUT
    / "phase26d_evaluation_radgraph_by_condition.csv"
)

condition_summary.to_csv(
    condition_path,
    index=False,
)

# ------------------------------------------------------------
# Paired record-level analysis
# ------------------------------------------------------------

paired = (
    lambda0_results[
        [
            "sample_id",
            "uid",
            "condition",
            "radgraph_precision",
            "radgraph_recall",
            "radgraph_f1",
        ]
    ]
    .rename(
        columns={
            "radgraph_precision": "precision_lambda0",
            "radgraph_recall": "recall_lambda0",
            "radgraph_f1": "f1_lambda0",
        }
    )
    .merge(
        lambda025_results[
            [
                "sample_id",
                "uid",
                "condition",
                "radgraph_precision",
                "radgraph_recall",
                "radgraph_f1",
            ]
        ].rename(
            columns={
                "radgraph_precision": "precision_lambda025",
                "radgraph_recall": "recall_lambda025",
                "radgraph_f1": "f1_lambda025",
            }
        ),
        on=["sample_id", "uid", "condition"],
        how="inner",
        validate="one_to_one",
    )
)

assert len(paired) == 480

paired["precision_delta"] = (
    paired["precision_lambda025"]
    - paired["precision_lambda0"]
)

paired["recall_delta"] = (
    paired["recall_lambda025"]
    - paired["recall_lambda0"]
)

paired["f1_delta"] = (
    paired["f1_lambda025"]
    - paired["f1_lambda0"]
)

# ------------------------------------------------------------
# Wilcoxon signed-rank test on paired F1
# ------------------------------------------------------------

nonzero_f1 = paired.loc[
    paired["f1_delta"] != 0,
    "f1_delta"
]

wilcoxon_result = wilcoxon(
    paired["f1_lambda025"],
    paired["f1_lambda0"],
    alternative="two-sided",
    zero_method="wilcox",
)

stat = float(wilcoxon_result.statistic)
p_value = float(wilcoxon_result.pvalue)

# Rank-biserial correlation
n_nonzero = len(nonzero_f1)

if n_nonzero > 0:
    positive_rank_sum = (
        nonzero_f1[nonzero_f1 > 0]
        .rank(method="average")
        .sum()
    )
    negative_rank_sum = (
        (-nonzero_f1[nonzero_f1 < 0])
        .rank(method="average")
        .sum()
    )

    rank_biserial = (
        positive_rank_sum - negative_rank_sum
    ) / (
        positive_rank_sum + negative_rank_sum
    )
else:
    rank_biserial = np.nan

paired_path = (
    RADGRAPH_OUT
    / "phase26d_evaluation_radgraph_paired.csv"
)

paired.to_csv(
    paired_path,
    index=False,
)

stats_df = pd.DataFrame(
    [
        {
            "metric": "radgraph_f1",
            "n_pairs": len(paired),
            "n_nonzero_differences": n_nonzero,
            "lambda0_mean": paired["f1_lambda0"].mean(),
            "lambda025_mean": paired["f1_lambda025"].mean(),
            "mean_delta_lambda025_minus_lambda0":
                paired["f1_delta"].mean(),
            "median_delta":
                paired["f1_delta"].median(),
            "wilcoxon_statistic": stat,
            "wilcoxon_p_value": p_value,
            "rank_biserial": rank_biserial,
        }
    ]
)

stats_path = (
    RADGRAPH_OUT
    / "phase26d_evaluation_radgraph_paired_stats.csv"
)

stats_df.to_csv(
    stats_path,
    index=False,
)

# ------------------------------------------------------------
# Final audit
# ------------------------------------------------------------

assert len(radgraph_results) == 960
assert radgraph_results["radgraph_f1"].notna().all()
assert len(overall_summary) == 2
assert len(condition_summary) == 12
assert len(paired) == 480

print("RECORD RESULTS:", record_path)
print("OVERALL SUMMARY:", overall_path)
print("CONDITION SUMMARY:", condition_path)
print("PAIRED RESULTS:", paired_path)
print("PAIRED STATS:", stats_path)

print("\nOVERALL:")
display(overall_summary)

print("\nCONDITION:")
display(condition_summary)

print("\nPAIRED RADGRAPH-F1:")
display(stats_df)

print("\nRADGRAPH PHASE26D FINAL AUDIT: PASS")

RECORD RESULTS: /content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_radgraph.csv
OVERALL SUMMARY: /content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_radgraph_summary.csv
CONDITION SUMMARY: /content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_radgraph_by_condition.csv
PAIRED RESULTS: /content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired.csv
PAIRED STATS: /content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired_stats.csv

OVERALL:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,lambda,n,precision_mean,precision_median,recall_mean,recall_median,f1_mean,f1_median
0,0.00,480,0.188116,0.181818,0.165754,0.153846,0.118235,0.100847
1,0.25,480,0.185867,0.177778,0.164830,0.163333,0.120467,0.102130

CONDITION:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,condition,lambda,n,precision_mean,precision_median,recall_mean,recall_median,f1_mean,f1_median
0,conflicting,0.00,80,0.170817,0.160028,0.154465,0.149074,0.097833,0.076923
1,conflicting,0.25,80,0.161447,0.155870,0.143300,0.144599,0.097971,0.084220
2,evidentiary_incomplete,0.00,80,0.251074,0.271499,0.218779,0.219219,0.158154,0.142857
3,evidentiary_incomplete,0.25,80,0.225557,0.250000,0.199290,0.193277,0.156858,0.155870
4,insufficient,0.00,80,0.056178,0.000000,0.045467,0.000000,0.030178,0.000000
5,insufficient,0.25,80,0.056178,0.000000,0.045467,0.000000,0.030178,0.000000
6,irrelevant,0.00,80,0.226850,0.211310,0.205611,0.175192,0.156038,0.130496
7,irrelevant,0.25,80,0.212722,0.203448,0.191661,0.184659,0.142981,0.151923
8,sufficient,0.00,80,0.230059,0.244289,0.200675,0.200000,0.147927,0.142857
9,sufficient,0.25,80,0.243202,0.243163,0.216575,0.209430,0.160245,0.148171
10,syntactic_incomplete,0.00,80,0.193720,0.188988,0.169525,0.156923,0.119281,0.109127
11,syntactic_incomplete,0.25,80,0.216095,0.228758,0.192686,0.205128,0.134569,0.129167

PAIRED RADGRAPH-F1:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,metric,n_pairs,n_nonzero_differences,lambda0_mean,lambda025_mean,mean_delta_lambda025_minus_lambda0,median_delta,wilcoxon_statistic,wilcoxon_p_value,rank_biserial
0,radgraph_f1,480,277,0.118235,0.120467,0.002232,0.0,17968.5,0.336329,0.150224

RADGRAPH PHASE26D FINAL AUDIT: PASS

In [ ]:
import sys
from pathlib import Path

ROOT = Path("/content/Evidence-State-Radiology")

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.evaluation.evaluate_chexpert_f1 import (
    CHEXPERT_CATEGORIES,
    extract_chexpert_vector,
    compute_chexpert_f1,
)

print("CheXpert implementation imported successfully.")
print("Number of categories:", len(CHEXPERT_CATEGORIES))
print("\nCategories:")
for i, category in enumerate(CHEXPERT_CATEGORIES, start=1):
    print(f"{i:2d}. {category}")

CheXpert implementation imported successfully.
Number of categories: 14

Categories:
 1. Enlarged Cardiomediastinum
 2. Cardiomegaly
 3. Lung Opacity
 4. Lung Lesion
 5. Edema
 6. Consolidation
 7. Pneumonia
 8. Atelectasis
 9. Pneumothorax
10. Pleural Effusion
11. Pleural Other
12. Fracture
13. Support Devices
14. No Finding

In [ ]:
import inspect

print("extract_chexpert_vector signature:")
print(inspect.signature(extract_chexpert_vector))

print("\ncompute_chexpert_f1 signature:")
print(inspect.signature(compute_chexpert_f1))

print("\ncompute_chexpert_f1 source:")
print(inspect.getsource(compute_chexpert_f1))

extract_chexpert_vector signature:
(text: str) -> Dict[str, Any]

compute_chexpert_f1 signature:
(ref_vector: Dict[str, Any], cand_vector: Dict[str, Any]) -> float

compute_chexpert_f1 source:
def compute_chexpert_f1(ref_vector: Dict[str, Any], cand_vector: Dict[str, Any]) -> float:
    """
    Compute micro CheXpert-F1 between reference vector and candidate vector.

    Positive targets are conditions where ref_vector == 1.
    """
    tp = 0
    fp = 0
    fn = 0

    for cat in CHEXPERT_CATEGORIES:
        r_val = ref_vector[cat]
        c_val = cand_vector[cat]

        r_pos = (r_val == 1)
        c_pos = (c_val == 1)

        if r_pos and c_pos:
            tp += 1
        elif not r_pos and c_pos:
            fp += 1
        elif r_pos and not c_pos:
            fn += 1

    if tp == 0 and fp == 0 and fn == 0:
        return 1.0  # Perfect agreement on absence of positive findings

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    return float(f1)

In [ ]:
# ============================================================
# Phase26D — Custom 14-category CheXpert-F1 evaluation
# Corrected for the "lambda" reserved-keyword issue
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np
from scipy.stats import wilcoxon

CHEXPERT_OUT = (
    ROOT / "results/tables/phase26d_metrics"
)
CHEXPERT_OUT.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Prepare input
# ------------------------------------------------------------

chexpert_input = generation_with_ref[
    [
        "sample_id",
        "uid",
        "condition",
        "lambda",
        "report",
        "reference_text",
    ]
].copy()

chexpert_input["report"] = (
    chexpert_input["report"]
    .fillna("")
    .astype(str)
)

chexpert_input["reference_text"] = (
    chexpert_input["reference_text"]
    .fillna("")
    .astype(str)
)

assert len(chexpert_input) == 960
assert chexpert_input["report"].str.len().gt(0).all()
assert chexpert_input["reference_text"].str.len().gt(0).all()

print("Input records:", len(chexpert_input))

# ------------------------------------------------------------
# Extract reference vectors once per study
# ------------------------------------------------------------

reference_unique = (
    chexpert_input[
        ["uid", "reference_text"]
    ]
    .drop_duplicates(subset=["uid"])
    .reset_index(drop=True)
)

assert len(reference_unique) == 80

reference_vectors = {}

for _, ref_row in reference_unique.iterrows():
    reference_vectors[ref_row["uid"]] = (
        extract_chexpert_vector(
            ref_row["reference_text"]
        )
    )

# Audit reference vectors
assert len(reference_vectors) == 80

for uid, vector in reference_vectors.items():
    assert set(vector.keys()) == set(CHEXPERT_CATEGORIES)

print("Reference vector audit: PASS")

# ------------------------------------------------------------
# Extract candidate vectors + calculate F1
#
# Use iterrows() here so "lambda" remains an ordinary
# dictionary-style column access and cannot conflict with
# Python's reserved keyword.
# ------------------------------------------------------------

results = []

for _, row in chexpert_input.iterrows():

    ref_vector = reference_vectors[row["uid"]]

    cand_vector = extract_chexpert_vector(
        row["report"]
    )

    score = compute_chexpert_f1(
        ref_vector,
        cand_vector,
    )

    results.append(
        {
            "sample_id": row["sample_id"],
            "uid": row["uid"],
            "condition": row["condition"],
            "lambda": row["lambda"],
            "chexpert_f1": score,
        }
    )

chexpert_results = pd.DataFrame(results)

# ------------------------------------------------------------
# Structural audit
# ------------------------------------------------------------

assert len(chexpert_results) == 960
assert chexpert_results["chexpert_f1"].notna().all()

lambda_counts = (
    chexpert_results["lambda"]
    .value_counts()
    .sort_index()
    .to_dict()
)

print("\nLambda counts:")
print(lambda_counts)

assert lambda_counts == {
    0.00: 480,
    0.25: 480,
}

condition_counts = (
    chexpert_results["condition"]
    .value_counts()
)

print("\nCondition counts:")
print(condition_counts)

assert condition_counts.eq(160).all()

assert chexpert_results["chexpert_f1"].between(
    0.0,
    1.0
).all()

print("\nCHEXPERT RECORD AUDIT: PASS")

# ------------------------------------------------------------
# Save record-level results
# ------------------------------------------------------------

record_path = (
    CHEXPERT_OUT
    / "phase26d_evaluation_chexpert.csv"
)

chexpert_results.to_csv(
    record_path,
    index=False,
)

# ------------------------------------------------------------
# Overall summary
# ------------------------------------------------------------

overall_summary = (
    chexpert_results
    .groupby("lambda")
    .agg(
        n=("chexpert_f1", "size"),
        f1_mean=("chexpert_f1", "mean"),
        f1_median=("chexpert_f1", "median"),
    )
    .reset_index()
)

overall_path = (
    CHEXPERT_OUT
    / "phase26d_evaluation_chexpert_summary.csv"
)

overall_summary.to_csv(
    overall_path,
    index=False,
)

# ------------------------------------------------------------
# Condition-level summary
# ------------------------------------------------------------

condition_summary = (
    chexpert_results
    .groupby(["condition", "lambda"])
    .agg(
        n=("chexpert_f1", "size"),
        f1_mean=("chexpert_f1", "mean"),
        f1_median=("chexpert_f1", "median"),
    )
    .reset_index()
    .sort_values(["condition", "lambda"])
)

condition_path = (
    CHEXPERT_OUT
    / "phase26d_evaluation_chexpert_by_condition.csv"
)

condition_summary.to_csv(
    condition_path,
    index=False,
)

# ------------------------------------------------------------
# Paired lambda=0 vs lambda=.25
# ------------------------------------------------------------

lambda0 = (
    chexpert_results[
        chexpert_results["lambda"] == 0.00
    ][
        [
            "sample_id",
            "uid",
            "condition",
            "chexpert_f1",
        ]
    ]
    .rename(
        columns={
            "chexpert_f1": "f1_lambda0"
        }
    )
)

lambda025 = (
    chexpert_results[
        chexpert_results["lambda"] == 0.25
    ][
        [
            "sample_id",
            "uid",
            "condition",
            "chexpert_f1",
        ]
    ]
    .rename(
        columns={
            "chexpert_f1": "f1_lambda025"
        }
    )
)

paired = lambda0.merge(
    lambda025,
    on=[
        "sample_id",
        "uid",
        "condition",
    ],
    how="inner",
    validate="one_to_one",
)

assert len(paired) == 480

paired["f1_delta"] = (
    paired["f1_lambda025"]
    - paired["f1_lambda0"]
)

# ------------------------------------------------------------
# Wilcoxon signed-rank test
# ------------------------------------------------------------

wilcoxon_result = wilcoxon(
    paired["f1_lambda025"],
    paired["f1_lambda0"],
    alternative="two-sided",
    zero_method="wilcox",
)

stat = float(wilcoxon_result.statistic)
p_value = float(wilcoxon_result.pvalue)

nonzero = paired.loc[
    paired["f1_delta"] != 0,
    "f1_delta"
]

n_nonzero = len(nonzero)

# ------------------------------------------------------------
# Rank-biserial correlation
# ------------------------------------------------------------

if n_nonzero > 0:

    positive_rank_sum = (
        nonzero[nonzero > 0]
        .rank(method="average")
        .sum()
    )

    negative_rank_sum = (
        (-nonzero[nonzero < 0])
        .rank(method="average")
        .sum()
    )

    rank_biserial = (
        positive_rank_sum - negative_rank_sum
    ) / (
        positive_rank_sum + negative_rank_sum
    )

else:
    rank_biserial = np.nan

# ------------------------------------------------------------
# Save paired results
# ------------------------------------------------------------

paired_path = (
    CHEXPERT_OUT
    / "phase26d_evaluation_chexpert_paired.csv"
)

paired.to_csv(
    paired_path,
    index=False,
)

stats_df = pd.DataFrame(
    [
        {
            "metric": "chexpert_f1",
            "n_pairs": len(paired),
            "n_nonzero_differences": n_nonzero,
            "lambda0_mean": paired["f1_lambda0"].mean(),
            "lambda025_mean": paired["f1_lambda025"].mean(),
            "mean_delta_lambda025_minus_lambda0":
                paired["f1_delta"].mean(),
            "median_delta":
                paired["f1_delta"].median(),
            "wilcoxon_statistic": stat,
            "wilcoxon_p_value": p_value,
            "rank_biserial": rank_biserial,
        }
    ]
)

stats_path = (
    CHEXPERT_OUT
    / "phase26d_evaluation_chexpert_paired_stats.csv"
)

stats_df.to_csv(
    stats_path,
    index=False,
)

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("\nRECORD RESULTS:")
print(record_path)

print("\nOVERALL SUMMARY:")
display(overall_summary)

print("\nCONDITION SUMMARY:")
display(condition_summary)

print("\nPAIRED CHEXPERT-F1:")
display(stats_df)

print("\nSaved:")
print(overall_path)
print(condition_path)
print(paired_path)
print(stats_path)

print("\nCHEXPERT PHASE26D FINAL AUDIT: PASS")

Input records: 960
Reference vector audit: PASS

Lambda counts:
{0.0: 480, 0.25: 480}

Condition counts:
condition
conflicting               160
evidentiary_incomplete    160
insufficient              160
irrelevant                160
sufficient                160
syntactic_incomplete      160
Name: count, dtype: int64

CHEXPERT RECORD AUDIT: PASS

RECORD RESULTS:
/content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_chexpert.csv

OVERALL SUMMARY:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

   lambda    n   f1_mean  f1_median
0    0.00  480  0.247887        0.0
1    0.25  480  0.243165        0.0

CONDITION SUMMARY:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

                 condition  lambda   n   f1_mean  f1_median
0              conflicting    0.00  80  0.207083        0.0
1              conflicting    0.25  80  0.195000        0.0
2   evidentiary_incomplete    0.00  80  0.308036        0.0
3   evidentiary_incomplete    0.25  80  0.255238        0.0
4             insufficient    0.00  80  0.273452        0.0
5             insufficient    0.25  80  0.273452        0.0
6               irrelevant    0.00  80  0.201786        0.0
7               irrelevant    0.25  80  0.224881        0.0
8               sufficient    0.00  80  0.258393        0.0
9               sufficient    0.25  80  0.257262        0.0
10    syntactic_incomplete    0.00  80  0.238571        0.0
11    syntactic_incomplete    0.25  80  0.253155        0.0

PAIRED CHEXPERT-F1:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,metric,n_pairs,n_nonzero_differences,lambda0_mean,lambda025_mean,mean_delta_lambda025_minus_lambda0,median_delta,wilcoxon_statistic,wilcoxon_p_value,rank_biserial
0,chexpert_f1,480,128,0.247887,0.243165,-0.004722,0.0,3973.0,0.711959,-0.092828

Saved:
/content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_chexpert_summary.csv
/content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_chexpert_by_condition.csv
/content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired.csv
/content/Evidence-State-Radiology/results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired_stats.csv

CHEXPERT PHASE26D FINAL AUDIT: PASS

In [ ]:
# ============================================================
# Phase26D — Master Evaluation Synthesis
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

MASTER_DIR = (
    ROOT / "results/tables/phase26d_master"
)
MASTER_DIR.mkdir(parents=True, exist_ok=True)

CLAIM_DIR = (
    ROOT / "results/tables/phase26d_claim_evaluation"
)

METRIC_DIR = (
    ROOT / "results/tables/phase26d_metrics"
)

# ------------------------------------------------------------
# 1. Load claim-level evaluation
# ------------------------------------------------------------

claim_summary = pd.read_csv(
    CLAIM_DIR / "phase26d_evaluation_claim_summary.csv"
)

print("Claim summary:")
display(claim_summary)

# ------------------------------------------------------------
# 2. Load RadGraph summary
# ------------------------------------------------------------

radgraph_summary = pd.read_csv(
    METRIC_DIR
    / "phase26d_evaluation_radgraph_summary.csv"
)

radgraph_paired = pd.read_csv(
    METRIC_DIR
    / "phase26d_evaluation_radgraph_paired_stats.csv"
)

print("\nRadGraph summary:")
display(radgraph_summary)

print("\nRadGraph paired statistics:")
display(radgraph_paired)

# ------------------------------------------------------------
# 3. Load CheXpert summary
# ------------------------------------------------------------

chexpert_summary = pd.read_csv(
    METRIC_DIR
    / "phase26d_evaluation_chexpert_summary.csv"
)

chexpert_paired = pd.read_csv(
    METRIC_DIR
    / "phase26d_evaluation_chexpert_paired_stats.csv"
)

print("\nCheXpert summary:")
display(chexpert_summary)

print("\nCheXpert paired statistics:")
display(chexpert_paired)

# ------------------------------------------------------------
# 4. Extract lambda rows
# ------------------------------------------------------------

claim0 = claim_summary[
    claim_summary["lambda"] == 0.00
].iloc[0]

claim025 = claim_summary[
    claim_summary["lambda"] == 0.25
].iloc[0]

rg0 = radgraph_summary[
    radgraph_summary["lambda"] == 0.00
].iloc[0]

rg025 = radgraph_summary[
    radgraph_summary["lambda"] == 0.25
].iloc[0]

cx0 = chexpert_summary[
    chexpert_summary["lambda"] == 0.00
].iloc[0]

cx025 = chexpert_summary[
    chexpert_summary["lambda"] == 0.25
].iloc[0]

# ------------------------------------------------------------
# 5. Construct master comparison table
# ------------------------------------------------------------

master = pd.DataFrame(
    [
        {
            "metric": "Unsupported claim rate",
            "lambda_0": claim0["unsupported_claim_rate"],
            "lambda_025": claim025["unsupported_claim_rate"],
            "absolute_delta":
                claim025["unsupported_claim_rate"]
                - claim0["unsupported_claim_rate"],
            "relative_change":
                (
                    claim025["unsupported_claim_rate"]
                    - claim0["unsupported_claim_rate"]
                )
                / claim0["unsupported_claim_rate"],
            "paired_test": "Wilcoxon",
            "p_value": 0.318635,
            "interpretation":
                "Slight reduction; not statistically significant",
        },
        {
            "metric": "RadGraph precision",
            "lambda_0": rg0["precision_mean"],
            "lambda_025": rg025["precision_mean"],
            "absolute_delta":
                rg025["precision_mean"]
                - rg0["precision_mean"],
            "relative_change":
                (
                    rg025["precision_mean"]
                    - rg0["precision_mean"]
                )
                / rg0["precision_mean"],
            "paired_test": "Not separately tested",
            "p_value": np.nan,
            "interpretation":
                "Small decrease",
        },
        {
            "metric": "RadGraph recall",
            "lambda_0": rg0["recall_mean"],
            "lambda_025": rg025["recall_mean"],
            "absolute_delta":
                rg025["recall_mean"]
                - rg0["recall_mean"],
            "relative_change":
                (
                    rg025["recall_mean"]
                    - rg0["recall_mean"]
                )
                / rg0["recall_mean"],
            "paired_test": "Not separately tested",
            "p_value": np.nan,
            "interpretation":
                "Small decrease",
        },
        {
            "metric": "RadGraph F1",
            "lambda_0": rg0["f1_mean"],
            "lambda_025": rg025["f1_mean"],
            "absolute_delta":
                rg025["f1_mean"]
                - rg0["f1_mean"],
            "relative_change":
                (
                    rg025["f1_mean"]
                    - rg0["f1_mean"]
                )
                / rg0["f1_mean"],
            "paired_test": "Wilcoxon signed-rank",
            "p_value":
                radgraph_paired.iloc[0]["wilcoxon_p_value"],
            "interpretation":
                "Small increase; not statistically significant",
        },
        {
            "metric": "Custom CheXpert-style F1",
            "lambda_0": cx0["f1_mean"],
            "lambda_025": cx025["f1_mean"],
            "absolute_delta":
                cx025["f1_mean"]
                - cx0["f1_mean"],
            "relative_change":
                (
                    cx025["f1_mean"]
                    - cx0["f1_mean"]
                )
                / cx0["f1_mean"],
            "paired_test": "Wilcoxon signed-rank",
            "p_value":
                chexpert_paired.iloc[0]["wilcoxon_p_value"],
            "interpretation":
                "Small decrease; not statistically significant",
        },
    ]
)

# ------------------------------------------------------------
# 6. Save master table
# ------------------------------------------------------------

master_path = (
    MASTER_DIR
    / "phase26d_master_evaluation.csv"
)

master.to_csv(
    master_path,
    index=False,
)

# ------------------------------------------------------------
# 7. Create concise paper-ready table
# ------------------------------------------------------------

paper_table = master[
    [
        "metric",
        "lambda_0",
        "lambda_025",
        "absolute_delta",
        "p_value",
        "interpretation",
    ]
].copy()

paper_path = (
    MASTER_DIR
    / "phase26d_paper_results_table.csv"
)

paper_table.to_csv(
    paper_path,
    index=False,
)

# ------------------------------------------------------------
# 8. Create condition-level combined table
# ------------------------------------------------------------

claim_condition = pd.read_csv(
    CLAIM_DIR
    / "phase26d_evaluation_claim_summary_by_condition.csv"
)

rg_condition = pd.read_csv(
    METRIC_DIR
    / "phase26d_evaluation_radgraph_by_condition.csv"
)

cx_condition = pd.read_csv(
    METRIC_DIR
    / "phase26d_evaluation_chexpert_by_condition.csv"
)

# Keep only lambda 0 and .25 and merge all metrics.
condition_master = (
    claim_condition[
        [
            "condition",
            "lambda",
            "unsupported_claim_count",
            "unsupported_claim_rate",
        ]
    ]
    .merge(
        rg_condition[
            [
                "condition",
                "lambda",
                "f1_mean",
                "f1_median",
            ]
        ].rename(
            columns={
                "f1_mean": "radgraph_f1_mean",
                "f1_median": "radgraph_f1_median",
            }
        ),
        on=["condition", "lambda"],
        how="inner",
    )
    .merge(
        cx_condition[
            [
                "condition",
                "lambda",
                "f1_mean",
                "f1_median",
            ]
        ].rename(
            columns={
                "f1_mean": "chexpert_f1_mean",
                "f1_median": "chexpert_f1_median",
            }
        ),
        on=["condition", "lambda"],
        how="inner",
    )
    .sort_values(["condition", "lambda"])
    .reset_index(drop=True)
)

condition_path = (
    MASTER_DIR
    / "phase26d_master_by_condition.csv"
)

condition_master.to_csv(
    condition_path,
    index=False,
)

# ------------------------------------------------------------
# 9. Final structural checks
# ------------------------------------------------------------

assert len(master) == 5
assert len(paper_table) == 5
assert len(condition_master) == 12

assert set(condition_master["lambda"]) == {
    0.00,
    0.25,
}

print("\nMASTER TABLE:")
display(master)

print("\nPAPER-READY TABLE:")
display(paper_table)

print("\nCONDITION MASTER:")
display(condition_master)

print("\nSaved:")
print(master_path)
print(paper_path)
print(condition_path)

print("\nPHASE26D MASTER SYNTHESIS AUDIT: PASS")

Claim summary:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,lambda,comparison_rows,supported,omission,extra_negation,ungrounded_affirmation,unsupported_affirmation,contradiction,unclear,unsupported_claim_count,unsupported_claim_rate_denominator,unsupported_claim_rate
0,0.00,1940,471,1005,269,91,35,45,24,171,935,0.182888
1,0.25,1924,479,993,271,77,38,53,13,168,931,0.180451

RadGraph summary:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,lambda,n,precision_mean,precision_median,recall_mean,recall_median,f1_mean,f1_median
0,0.00,480,0.188116,0.181818,0.165754,0.153846,0.118235,0.100847
1,0.25,480,0.185867,0.177778,0.164830,0.163333,0.120467,0.102130

RadGraph paired statistics:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,metric,n_pairs,n_nonzero_differences,lambda0_mean,lambda025_mean,mean_delta_lambda025_minus_lambda0,median_delta,wilcoxon_statistic,wilcoxon_p_value,rank_biserial
0,radgraph_f1,480,277,0.118235,0.120467,0.002232,0.0,17968.5,0.336329,0.150224

CheXpert summary:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

   lambda    n   f1_mean  f1_median
0    0.00  480  0.247887        0.0
1    0.25  480  0.243165        0.0

CheXpert paired statistics:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,metric,n_pairs,n_nonzero_differences,lambda0_mean,lambda025_mean,mean_delta_lambda025_minus_lambda0,median_delta,wilcoxon_statistic,wilcoxon_p_value,rank_biserial
0,chexpert_f1,480,128,0.247887,0.243165,-0.004722,0.0,3973.0,0.711959,-0.092828

MASTER TABLE:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,metric,lambda_0,lambda_025,absolute_delta,relative_change,paired_test,p_value,interpretation
0,Unsupported claim rate,0.182888,0.180451,-0.002437,-0.013323,Wilcoxon,0.318635,Slight reduction; not statistically significant
1,RadGraph precision,0.188116,0.185867,-0.002250,-0.011959,Not separately tested,NaN,Small decrease
2,RadGraph recall,0.165754,0.164830,-0.000924,-0.005573,Not separately tested,NaN,Small decrease
3,RadGraph F1,0.118235,0.120467,0.002232,0.018875,Wilcoxon signed-rank,0.336329,Small increase; not statistically significant
4,Custom CheXpert-style F1,0.247887,0.243165,-0.004722,-0.019050,Wilcoxon signed-rank,0.711959,Small decrease; not statistically significant

PAPER-READY TABLE:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,metric,lambda_0,lambda_025,absolute_delta,p_value,interpretation
0,Unsupported claim rate,0.182888,0.180451,-0.002437,0.318635,Slight reduction; not statistically significant
1,RadGraph precision,0.188116,0.185867,-0.002250,NaN,Small decrease
2,RadGraph recall,0.165754,0.164830,-0.000924,NaN,Small decrease
3,RadGraph F1,0.118235,0.120467,0.002232,0.336329,Small increase; not statistically significant
4,Custom CheXpert-style F1,0.247887,0.243165,-0.004722,0.711959,Small decrease; not statistically significant

CONDITION MASTER:

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,condition,lambda,unsupported_claim_count,unsupported_claim_rate,radgraph_f1_mean,radgraph_f1_median,chexpert_f1_mean,chexpert_f1_median
0,conflicting,0.00,46,0.335766,0.097833,0.076923,0.207083,0.0
1,conflicting,0.25,50,0.333333,0.097971,0.084220,0.195000,0.0
2,evidentiary_incomplete,0.00,33,0.160976,0.158154,0.142857,0.308036,0.0
3,evidentiary_incomplete,0.25,29,0.168605,0.156858,0.155870,0.255238,0.0
4,insufficient,0.00,16,0.333333,0.030178,0.000000,0.273452,0.0
5,insufficient,0.25,16,0.333333,0.030178,0.000000,0.273452,0.0
6,irrelevant,0.00,25,0.135870,0.156038,0.130496,0.201786,0.0
7,irrelevant,0.25,23,0.116162,0.142981,0.151923,0.224881,0.0
8,sufficient,0.00,31,0.162304,0.147927,0.142857,0.258393,0.0
9,sufficient,0.25,23,0.119792,0.160245,0.148171,0.257262,0.0
10,syntactic_incomplete,0.00,20,0.117647,0.119281,0.109127,0.238571,0.0
11,syntactic_incomplete,0.25,27,0.157895,0.134569,0.129167,0.253155,0.0

Saved:
/content/Evidence-State-Radiology/results/tables/phase26d_master/phase26d_master_evaluation.csv
/content/Evidence-State-Radiology/results/tables/phase26d_master/phase26d_paper_results_table.csv
/content/Evidence-State-Radiology/results/tables/phase26d_master/phase26d_master_by_condition.csv

PHASE26D MASTER SYNTHESIS AUDIT: PASS

In [ ]:
%cd /content/Evidence-State-Radiology
!git status --short
!git branch --show-current
!git log -1 --oneline

/content/Evidence-State-Radiology
?? docs/phase26d_lambda_selection_policy.md
?? results/maira2_contrastive/
?? results/tables/phase26d/
?? results/tables/phase26d_claim_evaluation/
?? results/tables/phase26d_master/
?? results/tables/phase26d_metrics/
phase25b-maira2-feasibility
5907f33 (HEAD -> phase25b-maira2-feasibility, origin/phase25b-maira2-feasibility) feat: add phases 17-25 reliability evaluation and MAIRA-2 feasibility

In [ ]:
!git status --short

?? docs/phase26d_lambda_selection_policy.md
?? results/maira2_contrastive/
?? results/tables/phase26d/
?? results/tables/phase26d_claim_evaluation/
?? results/tables/phase26d_master/
?? results/tables/phase26d_metrics/

In [ ]:
%cd /content/Evidence-State-Radiology

!echo "===== PHASE 26D FILES ====="
!find docs/phase26d_lambda_selection_policy.md \
       results/maira2_contrastive \
       results/tables/phase26d \
       results/tables/phase26d_claim_evaluation \
       results/tables/phase26d_master \
       results/tables/phase26d_metrics \
       -type f -printf "%p\t%k KB\n" | sort

!echo ""
!echo "===== LARGE FILES (>50 MB) ====="
!find docs/phase26d_lambda_selection_policy.md \
       results/maira2_contrastive \
       results/tables/phase26d \
       results/tables/phase26d_claim_evaluation \
       results/tables/phase26d_master \
       results/tables/phase26d_metrics \
       -type f -size +50M -printf "%p\t%k KB\n" | sort

/content/Evidence-State-Radiology
===== PHASE 26D FILES =====
docs/phase26d_lambda_selection_policy.md	4 KB
results/maira2_contrastive/phase26d_evaluation/phase26d_evaluation_generation.csv	624 KB
results/tables/phase26d_claim_evaluation/phase26d_evaluation_claims.csv	284 KB
results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary_by_condition.csv	4 KB
results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary.csv	4 KB
results/tables/phase26d_claim_evaluation/phase26d_evaluation_paired_records.csv	32 KB
results/tables/phase26d_claim_evaluation/phase26d_lambda_selection.csv	4 KB
results/tables/phase26d_master/phase26d_master_by_condition.csv	4 KB
results/tables/phase26d_master/phase26d_master_evaluation.csv	4 KB
results/tables/phase26d_master/phase26d_paper_results_table.csv	4 KB
results/tables/phase26d_metrics/phase26d_evaluation_chexpert_by_condition.csv	4 KB
results/tables/phase26d_metrics/phase26d_evaluation_chexpert.csv	36 KB
results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired.csv	24 KB
results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired_stats.csv	4 KB
results/tables/phase26d_metrics/phase26d_evaluation_chexpert_summary.csv	4 KB
results/tables/phase26d_metrics/phase26d_evaluation_radgraph_by_condition.csv	4 KB
results/tables/phase26d_metrics/phase26d_evaluation_radgraph.csv	548 KB
results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired.csv	76 KB
results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired_stats.csv	4 KB
results/tables/phase26d_metrics/phase26d_evaluation_radgraph_summary.csv	4 KB
results/tables/phase26d/phase26d_maira2_split.csv	4 KB

===== LARGE FILES (>50 MB) =====

In [ ]:
%cd /content/Evidence-State-Radiology

!git add docs/phase26d_lambda_selection_policy.md \
  results/maira2_contrastive/phase26d_evaluation/phase26d_evaluation_generation.csv \
  results/tables/phase26d/phase26d_maira2_split.csv \
  results/tables/phase26d_claim_evaluation/ \
  results/tables/phase26d_master/ \
  results/tables/phase26d_metrics/

!echo "===== STAGED FILES ====="
!git diff --cached --name-status

/content/Evidence-State-Radiology
===== STAGED FILES =====
A	docs/phase26d_lambda_selection_policy.md
A	results/maira2_contrastive/phase26d_evaluation/phase26d_evaluation_generation.csv
A	results/tables/phase26d/phase26d_maira2_split.csv
A	results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary.csv
A	results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary_by_condition.csv
A	results/tables/phase26d_claim_evaluation/phase26d_evaluation_claims.csv
A	results/tables/phase26d_claim_evaluation/phase26d_evaluation_paired_records.csv
A	results/tables/phase26d_claim_evaluation/phase26d_lambda_selection.csv
A	results/tables/phase26d_master/phase26d_master_by_condition.csv
A	results/tables/phase26d_master/phase26d_master_evaluation.csv
A	results/tables/phase26d_master/phase26d_paper_results_table.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_chexpert.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_chexpert_by_condition.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired_stats.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_chexpert_summary.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_radgraph.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_radgraph_by_condition.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired_stats.csv
A	results/tables/phase26d_metrics/phase26d_evaluation_radgraph_summary.csv

In [ ]:
%cd /content/Evidence-State-Radiology

!echo "===== STATUS ====="
!git status --short

!echo ""
!echo "===== STAGED FILE COUNT ====="
!git diff --cached --name-only | wc -l

!echo ""
!echo "===== STAGED SIZE ====="
!git diff --cached --stat

/content/Evidence-State-Radiology
===== STATUS =====
A  docs/phase26d_lambda_selection_policy.md
A  results/maira2_contrastive/phase26d_evaluation/phase26d_evaluation_generation.csv
A  results/tables/phase26d/phase26d_maira2_split.csv
A  results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary.csv
A  results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary_by_condition.csv
A  results/tables/phase26d_claim_evaluation/phase26d_evaluation_claims.csv
A  results/tables/phase26d_claim_evaluation/phase26d_evaluation_paired_records.csv
A  results/tables/phase26d_claim_evaluation/phase26d_lambda_selection.csv
A  results/tables/phase26d_master/phase26d_master_by_condition.csv
A  results/tables/phase26d_master/phase26d_master_evaluation.csv
A  results/tables/phase26d_master/phase26d_paper_results_table.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_chexpert.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_chexpert_by_condition.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired_stats.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_chexpert_summary.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_radgraph.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_radgraph_by_condition.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired_stats.csv
A  results/tables/phase26d_metrics/phase26d_evaluation_radgraph_summary.csv

===== STAGED FILE COUNT =====
21

===== STAGED SIZE =====
 docs/phase26d_lambda_selection_policy.md           |   26 +
 .../phase26d_evaluation_generation.csv             |  961 +++++
 results/tables/phase26d/phase26d_maira2_split.csv  |   97 +
 .../phase26d_evaluation_claim_summary.csv          |    3 +
 ...se26d_evaluation_claim_summary_by_condition.csv |   13 +
 .../phase26d_evaluation_claims.csv                 | 3865 ++++++++++++++++++++
 .../phase26d_evaluation_paired_records.csv         |  481 +++
 .../phase26d_lambda_selection.csv                  |    6 +
 .../phase26d_master_by_condition.csv               |   13 +
 .../phase26d_master/phase26d_master_evaluation.csv |    6 +
 .../phase26d_paper_results_table.csv               |    6 +
 .../phase26d_evaluation_chexpert.csv               |  961 +++++
 .../phase26d_evaluation_chexpert_by_condition.csv  |   13 +
 .../phase26d_evaluation_chexpert_paired.csv        |  481 +++
 .../phase26d_evaluation_chexpert_paired_stats.csv  |    2 +
 .../phase26d_evaluation_chexpert_summary.csv       |    3 +
 .../phase26d_evaluation_radgraph.csv               | 1921 ++++++++++
 .../phase26d_evaluation_radgraph_by_condition.csv  |   13 +
 .../phase26d_evaluation_radgraph_paired.csv        |  481 +++
 .../phase26d_evaluation_radgraph_paired_stats.csv  |    2 +
 .../phase26d_evaluation_radgraph_summary.csv       |    3 +
 21 files changed, 9357 insertions(+)

In [ ]:
%cd /content/Evidence-State-Radiology

!git commit -m "results: add Phase 26D MAIRA-2 evaluation artifacts"

/content/Evidence-State-Radiology
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@873988c3d1b3.(none)')

In [ ]:
%cd /content/Evidence-State-Radiology

!git config user.name "Vasu1912"
!git config user.email "gangavarapuvasu.2005@gmail.com"

print("Git identity:")
!git config user.name
!git config user.email

/content/Evidence-State-Radiology
Git identity:
Vasu1912
gangavarapuvasu.2005@gmail.com

In [ ]:
!git commit -m "results: add Phase 26D MAIRA-2 evaluation artifacts"

[phase25b-maira2-feasibility c660f21] results: add Phase 26D MAIRA-2 evaluation artifacts
 21 files changed, 9357 insertions(+)
 create mode 100644 docs/phase26d_lambda_selection_policy.md
 create mode 100644 results/maira2_contrastive/phase26d_evaluation/phase26d_evaluation_generation.csv
 create mode 100644 results/tables/phase26d/phase26d_maira2_split.csv
 create mode 100644 results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary.csv
 create mode 100644 results/tables/phase26d_claim_evaluation/phase26d_evaluation_claim_summary_by_condition.csv
 create mode 100644 results/tables/phase26d_claim_evaluation/phase26d_evaluation_claims.csv
 create mode 100644 results/tables/phase26d_claim_evaluation/phase26d_evaluation_paired_records.csv
 create mode 100644 results/tables/phase26d_claim_evaluation/phase26d_lambda_selection.csv
 create mode 100644 results/tables/phase26d_master/phase26d_master_by_condition.csv
 create mode 100644 results/tables/phase26d_master/phase26d_master_evaluation.csv
 create mode 100644 results/tables/phase26d_master/phase26d_paper_results_table.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_chexpert.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_chexpert_by_condition.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_chexpert_paired_stats.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_chexpert_summary.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_radgraph.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_radgraph_by_condition.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_radgraph_paired_stats.csv
 create mode 100644 results/tables/phase26d_metrics/phase26d_evaluation_radgraph_summary.csv

In [ ]:
!git status --short
!git log -2 --oneline

c660f21 (HEAD -> phase25b-maira2-feasibility) results: add Phase 26D MAIRA-2 evaluation artifacts
5907f33 (origin/phase25b-maira2-feasibility) feat: add phases 17-25 reliability evaluation and MAIRA-2 feasibility

In [ ]:
%cd /content/Evidence-State-Radiology

!git push origin phase25b-maira2-feasibility

/content/Evidence-State-Radiology
fatal: could not read Username for 'https://github.com': No such device or address

In [ ]:
%cd /content/Evidence-State-Radiology

!git bundle create /content/phase26d_checkpoint.bundle 5907f33..c660f21

!ls -lh /content/phase26d_checkpoint.bundle

/content/Evidence-State-Radiology
fatal: Refusing to create empty bundle.
ls: cannot access '/content/phase26d_checkpoint.bundle': No such file or directory

In [ ]:
%cd /content/Evidence-State-Radiology

!git show --no-patch --format=fuller c660f21
!git rev-parse c660f21^

/content/Evidence-State-Radiology
commit c660f21aba26f24c56e5a791fc9ce873db67e537 (HEAD -> phase25b-maira2-feasibility)
Author:     Vasu1912 <gangavarapuvasu.2005@gmail.com>
AuthorDate: Tue Oct 6 16:24:33 2026 +0000
Commit:     Vasu1912 <gangavarapuvasu.2005@gmail.com>
CommitDate: Tue Oct 6 16:24:33 2026 +0000

    results: add Phase 26D MAIRA-2 evaluation artifacts
5907f338ac290a64bbd01c0610a3f8d2b8f13b37

In [ ]:
%cd /content/Evidence-State-Radiology

!git bundle create /content/phase26d_checkpoint.bundle c660f21aba26f24c56e5a791fc9ce873db67e537
!ls -lh /content/phase26d_checkpoint.bundle

/content/Evidence-State-Radiology
fatal: Refusing to create empty bundle.
ls: cannot access '/content/phase26d_checkpoint.bundle': No such file or directory

In [ ]:
%cd /content/Evidence-State-Radiology

!git format-patch --stdout 5907f338ac290a64bbd01c0610a3f8d2b8f13b37..c660f21aba26f24c56e5a791fc9ce873db67e537 > /content/phase26d_commit.patch

!ls -lh /content/phase26d_commit.patch

/content/Evidence-State-Radiology
-rw-r--r-- 1 root root 1.6M Oct  6 16:32 /content/phase26d_commit.patch

In [ ]:
from google.colab import files
files.download("/content/phase26d_commit.patch")